//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-23
// Command for adding/editing a venue entity with validation, mapping,
// domain events, and cache invalidation.
// Documentation: https://docs.cleanarchitectureblazor.com/features/venue
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings


using CleanArchitecture.Blazor.Application.Features.Venues.Caching;
using CleanArchitecture.Blazor.Application.Features.Venues.DTOs;
namespace CleanArchitecture.Blazor.Application.Features.Venues.Commands.AddEdit;

public class AddEditVenueCommand: ICacheInvalidatorRequest<Result<int>>
{
      [Description("Id")]
      public int Id { get; set; }
          [Description("Name")]
    public string Name {get;set;} 
    [Description("Location")]
    public string? Location {get;set;} 
    [Description("Capacity")]
    public int? Capacity {get;set;} 
    [Description("Venue fee")]
    public decimal? VenueFee {get;set;} 


      public string CacheKey => VenueCacheKey.GetAllCacheKey;
      public IEnumerable<string>? Tags => VenueCacheKey.Tags;
    private class Mapping : Profile
    {
        public Mapping()
        {
            CreateMap<VenueDto, AddEditVenueCommand>(MemberList.None);
            CreateMap<AddEditVenueCommand, Venue>(MemberList.None);
        }
    }
}

public class AddEditVenueCommandHandler : IRequestHandler<AddEditVenueCommand, Result<int>>
{
    private readonly IMapper _mapper;
    private readonly IApplicationDbContext _context;
    public AddEditVenueCommandHandler(
        IMapper mapper,
        IApplicationDbContext context)
    {
        _mapper = mapper;
        _context = context;
    }
    public async Task<Result<int>> Handle(AddEditVenueCommand request, CancellationToken cancellationToken)
    {
        if (request.Id > 0)
        {
            var item = await _context.Venues.FindAsync(request.Id, cancellationToken);
            if (item == null)
            {
                return await Result<int>.FailureAsync($"Venue with id: [{request.Id}] not found.");
            }
            item = _mapper.Map(request, item);
			// raise a update domain event
			item.AddDomainEvent(new VenueUpdatedEvent(item));
            await _context.SaveChangesAsync(cancellationToken);
            return await Result<int>.SuccessAsync(item.Id);
        }
        else
        {
            var item = _mapper.Map<Venue>(request);
            // raise a create domain event
			item.AddDomainEvent(new VenueCreatedEvent(item));
            _context.Venues.Add(item);
            await _context.SaveChangesAsync(cancellationToken);
            return await Result<int>.SuccessAsync(item.Id);
        }
       
    }
}

