//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-09-24
//     Last Modified: 2025-09-24
//     Description: 
//       Defines a query to retrieve a employee by its ID. The result is cached 
//       to optimize performance for repeated retrievals of the same employee.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Employees.DTOs;
using CleanArchitecture.Blazor.Application.Features.Employees.Caching;
using CleanArchitecture.Blazor.Application.Features.Employees.Specifications;

namespace CleanArchitecture.Blazor.Application.Features.Employees.Queries.GetById;

public class GetEmployeeByIdQuery : ICacheableRequest<Result<EmployeeDto>>
{
   public required int Id { get; set; }
   public string CacheKey => EmployeeCacheKey.GetByIdCacheKey($"{Id}");
   public IEnumerable<string>? Tags => EmployeeCacheKey.Tags;
}

public class GetEmployeeByIdQueryHandler :
     IRequestHandler<GetEmployeeByIdQuery, Result<EmployeeDto>>
{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    private readonly IMapper _mapper;
    public GetEmployeeByIdQueryHandler(
        IMapper mapper,
        IApplicationDbContextFactory dbContextFactory)
    {
        _mapper = mapper;
        _dbContextFactory = dbContextFactory;
    }

    public async Task<Result<EmployeeDto>> Handle(GetEmployeeByIdQuery request, CancellationToken cancellationToken)
    {
        await using var _context = await _dbContextFactory.CreateAsync(cancellationToken);
        var data = await _context.Employees.ApplySpecification(new EmployeeByIdSpecification(request.Id))
                                                .ProjectTo<EmployeeDto>(_mapper.ConfigurationProvider)
                                                .FirstAsync(cancellationToken) ?? throw new NotFoundException($"Employee with id: [{request.Id}] not found.");
        return await Result<EmployeeDto>.SuccessAsync(data);
    }
}
