//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Import command & template for equipmentitems.
// Validates Excel data, prevents duplicates, and provides a template for bulk entry.
// Docs: https://docs.cleanarchitectureblazor.com/features/equipmentitem
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.EquipmentItems.DTOs;
using CleanArchitecture.Blazor.Application.Features.EquipmentItems.Caching;

namespace CleanArchitecture.Blazor.Application.Features.EquipmentItems.Commands.Import;

    public class ImportEquipmentItemsCommand: ICacheInvalidatorRequest<Result<int>>
    {
        public string FileName { get; set; }
        public byte[] Data { get; set; }
        public string CacheKey => EquipmentItemCacheKey.GetAllCacheKey;
        public IEnumerable<string>? Tags => EquipmentItemCacheKey.Tags;
        public ImportEquipmentItemsCommand(string fileName,byte[] data)
        {
           FileName = fileName;
           Data = data;
        }
    }
    public record class CreateEquipmentItemsTemplateCommand : IRequest<Result<byte[]>>
    {
 
    }

    public class ImportEquipmentItemsCommandHandler : 
                 IRequestHandler<CreateEquipmentItemsTemplateCommand, Result<byte[]>>,
                 IRequestHandler<ImportEquipmentItemsCommand, Result<int>>
    {
        private readonly IApplicationDbContextFactory _dbContextFactory;
        private readonly IStringLocalizer<ImportEquipmentItemsCommandHandler> _localizer;
        private readonly IExcelService _excelService;
        private readonly EquipmentItemDto _dto = new();
        private readonly IMapper _mapper;
        public ImportEquipmentItemsCommandHandler(
            IApplicationDbContextFactory dbContextFactory,
            IMapper mapper,
            IExcelService excelService,
            IStringLocalizer<ImportEquipmentItemsCommandHandler> localizer)
        {
            _dbContextFactory = dbContextFactory;
            _localizer = localizer;
            _excelService = excelService;
            _mapper = mapper;
        }
        #nullable disable warnings
        public async Task<Result<int>> Handle(ImportEquipmentItemsCommand request, CancellationToken cancellationToken)
        {
        await using var _context = await _dbContextFactory.CreateAsync(cancellationToken);
        var result = await _excelService.ImportAsync(request.Data, mappers: new Dictionary<string, Func<DataRow, EquipmentItemDto, object?>>
            {
                                { _localizer[_dto.GetMemberDescription(x=>x.Name)], (row, item) => item.Name = row[_localizer[_dto.GetMemberDescription(x=>x.Name)]].ToString() }, 
                { _localizer[_dto.GetMemberDescription(x=>x.Category)], (row, item) => item.Category = row[_localizer[_dto.GetMemberDescription(x=>x.Category)]].ToString() }, 
                { _localizer[_dto.GetMemberDescription(x=>x.DailyRate)], (row, item) => item.DailyRate =Convert.ToDecimal(row[_localizer[_dto.GetMemberDescription(x=>x.DailyRate)]]) }, 
                { _localizer[_dto.GetMemberDescription(x=>x.PurchaseCost)], (row, item) => item.PurchaseCost =Convert.ToDecimal(row[_localizer[_dto.GetMemberDescription(x=>x.PurchaseCost)]]) }, 
                { _localizer[_dto.GetMemberDescription(x=>x.VendorId)], (row, item) => item.VendorId =Convert.ToInt32(row[_localizer[_dto.GetMemberDescription(x=>x.VendorId)]]) }, 

            }, _localizer[_dto.GetClassDescription()]);
            if (result.Succeeded && result.Data is not null)
            {
                foreach (var dto in result.Data)
                {
                    var exists = await _context.EquipmentItems.AnyAsync(x => x.Name == dto.Name, cancellationToken);
                    if (!exists)
                    {
                        var item = _mapper.Map<EquipmentItem>(dto);
                        // add create domain events if this entity implement the IHasDomainEvent interface
				        // item.AddDomainEvent(new EquipmentItemCreatedEvent(item));
                        await _context.EquipmentItems.AddAsync(item, cancellationToken);
                    }
                 }
                 await _context.SaveChangesAsync(cancellationToken);
                 return await Result<int>.SuccessAsync(result.Data.Count());
           }
           else
           {
               return await Result<int>.FailureAsync(result.Errors);
           }
        }
        public async Task<Result<byte[]>> Handle(CreateEquipmentItemsTemplateCommand request, CancellationToken cancellationToken)
        {
            // TODO: Implement ImportEquipmentItemsCommandHandler method 
            var fields = new string[] {
                   // TODO: Define the fields that should be generate in the template, for example:
                   _localizer[_dto.GetMemberDescription(x=>x.Name)], 
_localizer[_dto.GetMemberDescription(x=>x.Category)], 
_localizer[_dto.GetMemberDescription(x=>x.DailyRate)], 
_localizer[_dto.GetMemberDescription(x=>x.PurchaseCost)], 
_localizer[_dto.GetMemberDescription(x=>x.VendorId)], 

                };
            var result = await _excelService.CreateTemplateAsync(fields, _localizer[_dto.GetClassDescription()]);
            return await Result<byte[]>.SuccessAsync(result);
        }
    }

