//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Validator for ImportEquipmentItemsCommand: ensures the Data property is non-null and non-empty for equipmentitem import.
// Docs: https://docs.cleanarchitectureblazor.com/features/equipmentitem
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.EquipmentItems.Commands.Import;

public class ImportEquipmentItemsCommandValidator : AbstractValidator<ImportEquipmentItemsCommand>
{
        public ImportEquipmentItemsCommandValidator()
        {
           
           RuleFor(v => v.Data)
                .NotNull()
                .NotEmpty();

        }
}

