//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Validator for UpdateServiceCommand: ensures required fields (e.g., Id, non-empty Name, max length for properties) are valid for updating a service.
// Docs: https://docs.cleanarchitectureblazor.com/features/service
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.Services.Commands.Update;

public class UpdateServiceCommandValidator : AbstractValidator<UpdateServiceCommand>
{
        public UpdateServiceCommandValidator()
        {
           RuleFor(v => v.Id).NotNull();
               RuleFor(v => v.ServiceCategoryId).NotNull(); 
    RuleFor(v => v.Name).MaximumLength(50).NotEmpty(); 
    RuleFor(v => v.Description).MaximumLength(255); 
    RuleFor(v => v.DefaultPricingModel).NotNull(); 

          
        }
    
}

