//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-09-24
//     Last Modified: 2025-09-24
//     Description: 
//       Defines a specification for applying advanced filtering options to the 
//       PurchaseOrder entity, supporting different views and keyword-based searches.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.PurchaseOrders.Specifications;
#nullable disable warnings
/// <summary>
/// Specification class for advanced filtering of PurchaseOrders.
/// </summary>
public class PurchaseOrderAdvancedSpecification : Specification<PurchaseOrder>
{
    public PurchaseOrderAdvancedSpecification(PurchaseOrderAdvancedFilter filter)
    {
        DateTime today = DateTime.UtcNow;
        var todayrange = today.GetDateRange(PurchaseOrderListView.TODAY.ToString(), filter.CurrentUser.LocalTimeOffset);
        var last30daysrange = today.GetDateRange(PurchaseOrderListView.LAST_30_DAYS.ToString(),filter.CurrentUser.LocalTimeOffset);

        Query.Where(q => q.ExternalNumber != null)
             .Where(filter.Keyword,!string.IsNullOrEmpty(filter.Keyword))
             .Where(q => q.CreatedById == filter.CurrentUser.UserId, filter.ListView == PurchaseOrderListView.My && filter.CurrentUser is not null)
             .Where(x => x.CreatedAt >= todayrange.Start && x.CreatedAt < todayrange.End.AddDays(1), filter.ListView == PurchaseOrderListView.TODAY)
             .Where(x => x.CreatedAt >= last30daysrange.Start, filter.ListView == PurchaseOrderListView.LAST_30_DAYS);
       
    }
}
