//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Validator for DeleteQuoteLineCommand: ensures the ID list for quoteline is not null and contains only positive IDs.
// Docs: https://docs.cleanarchitectureblazor.com/features/quoteline
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.QuoteLines.Commands.Delete;

public class DeleteQuoteLineCommandValidator : AbstractValidator<DeleteQuoteLineCommand>
{
        public DeleteQuoteLineCommandValidator()
        {
          
            RuleFor(v => v.Id).NotNull().ForEach(v=>v.GreaterThan(0));
          
        }
}
    

