//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Command and handler for deleting ProjectTask entities.
// Implements cache invalidation and triggers domain events.
// Docs: https://docs.cleanarchitectureblazor.com/features/projecttask
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.ProjectTasks.Caching;

namespace CleanArchitecture.Blazor.Application.Features.ProjectTasks.Commands.Delete;

public class DeleteProjectTaskCommand:  ICacheInvalidatorRequest<Result>
{
  public int[] Id {  get; }
  public string CacheKey => ProjectTaskCacheKey.GetAllCacheKey;
  public IEnumerable<string>? Tags => ProjectTaskCacheKey.Tags;
  public DeleteProjectTaskCommand(int[] id)
  {
    Id = id;
  }
}

public class DeleteProjectTaskCommandHandler : 
             IRequestHandler<DeleteProjectTaskCommand, Result>

{
    private readonly IApplicationDbContext _context;
    public DeleteProjectTaskCommandHandler(
        IApplicationDbContext context)
    {
        _context = context;
    }
    public async Task<Result> Handle(DeleteProjectTaskCommand request, CancellationToken cancellationToken)
    {
        var items = await _context.ProjectTasks.Where(x=>request.Id.Contains(x.Id)).ToListAsync(cancellationToken);
        foreach (var item in items)
        {
		    // raise a delete domain event
			item.AddDomainEvent(new ProjectTaskDeletedEvent(item));
            _context.ProjectTasks.Remove(item);
        }
        await _context.SaveChangesAsync(cancellationToken);
        return await Result.SuccessAsync();
    }

}

