////------------------------------------------------------------------------------
//// <auto-generated>
////     This file is part of the CleanArchitecture.Blazor project.
////     Licensed to the .NET Foundation under one or more agreements.
////     The .NET Foundation licenses this file to you under the MIT license.
////     See the LICENSE file in the project root for more information.
////
////     Author: neozhu
////     Created Date: 2025-03-27
////     Last Modified: 2025-03-27
////     Description: 
////       Handles the `PurchaseItemDeletedEvent` which occurs when a new purchaseitem is deleted.
////       This event handler can be extended to trigger additional actions, such as 
////       sending notifications or updating other systems.
//// </auto-generated>
////------------------------------------------------------------------------------

//namespace CleanArchitecture.Blazor.Application.Features.PurchaseItems.EventHandlers;

//    public class PurchaseItemDeletedEventHandler : INotificationHandler<PurchaseItemDeletedEvent>
//    {
//        private readonly ILogger<PurchaseItemDeletedEventHandler> _logger;

//        public PurchaseItemDeletedEventHandler(
//            ILogger<PurchaseItemDeletedEventHandler> logger
//            )
//        {
//            _logger = logger;
//        }
//        public Task Handle(PurchaseItemDeletedEvent notification, CancellationToken cancellationToken)
//        {
//            _logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
//            return Task.CompletedTask;
//        }
//    }
