//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-09-24
//     Last Modified: 2025-09-24
//     Description: 
//       Defines a query for retrieving purchaseorders with pagination and filtering 
//       options. The result is cached to enhance performance for repeated queries.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.PurchaseOrders.DTOs;
using CleanArchitecture.Blazor.Application.Features.PurchaseOrders.Caching;
using CleanArchitecture.Blazor.Application.Features.PurchaseOrders.Specifications;

namespace CleanArchitecture.Blazor.Application.Features.PurchaseOrders.Queries.Pagination;

public class PurchaseOrdersWithPaginationQuery : PurchaseOrderAdvancedFilter, ICacheableRequest<PaginatedData<PurchaseOrderDto>>
{
    public override string ToString()
    {
        return $"Listview:{ListView}:{CurrentUser?.UserId}, Search:{Keyword}, {OrderBy}, {SortDirection}, {PageNumber}, {PageSize}";
    }
    public string CacheKey => PurchaseOrderCacheKey.GetPaginationCacheKey($"{this}");
    public IEnumerable<string>? Tags => PurchaseOrderCacheKey.Tags;
    public PurchaseOrderAdvancedSpecification Specification => new PurchaseOrderAdvancedSpecification(this);
}
    
public class PurchaseOrdersWithPaginationQueryHandler :
         IRequestHandler<PurchaseOrdersWithPaginationQuery, PaginatedData<PurchaseOrderDto>>
{
        private readonly IApplicationDbContextFactory _dbContextFactory;;
        private readonly IMapper _mapper;
        public PurchaseOrdersWithPaginationQueryHandler(
            IMapper mapper,
            IApplicationDbContext context)
        {
            _mapper = mapper;
            _context = context;
        }

        public async Task<PaginatedData<PurchaseOrderDto>> Handle(PurchaseOrdersWithPaginationQuery request, CancellationToken cancellationToken)
        {
           var data = await _context.PurchaseOrders.OrderBy($"{request.OrderBy} {request.SortDirection}")
                                                   .ProjectToPaginatedDataAsync<PurchaseOrder, PurchaseOrderDto>(request.Specification,
                                                    request.PageNumber,
                                                    request.PageSize,
                                                    _mapper.ConfigurationProvider,
                                                    cancellationToken);
            return data;
        }
}