//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Handles ProjectTaskCreatedEvent: triggered when a new projecttask is created.
// Extendable for additional actions (e.g., notifications, system updates).
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Application.Features.ProjectTasks.EventHandlers;

public class ProjectTaskCreatedEventHandler : INotificationHandler<ProjectTaskCreatedEvent>
{
        private readonly ILogger<ProjectTaskCreatedEventHandler> _logger;

        public ProjectTaskCreatedEventHandler(
            ILogger<ProjectTaskCreatedEventHandler> logger
            )
        {
            _logger = logger;
        }
        public Task Handle(ProjectTaskCreatedEvent notification, CancellationToken cancellationToken)
        {
            _logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
            return Task.CompletedTask;
        }
}
