//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Handles ProjectTaskUpdatedEvent: triggered when a projecttask is updated.
// Extendable for additional actions (e.g., notifications, system updates).
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Application.Features.ProjectTasks.EventHandlers;

    public class ProjectTaskUpdatedEventHandler : INotificationHandler<ProjectTaskUpdatedEvent>
    {
        private readonly ILogger<ProjectTaskUpdatedEventHandler> _logger;

        public ProjectTaskUpdatedEventHandler(
            ILogger<ProjectTaskUpdatedEventHandler> logger
            )
        {
            _logger = logger;
        }
        public Task Handle(ProjectTaskUpdatedEvent notification, CancellationToken cancellationToken)
        {
            _logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
            return Task.CompletedTask;
        }
    }
