//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-23
// Validator for DeleteVenueCommand: ensures the ID list for venue is not null and contains only positive IDs.
// Docs: https://docs.cleanarchitectureblazor.com/features/venue
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.Venues.Commands.Delete;

public class DeleteVenueCommandValidator : AbstractValidator<DeleteVenueCommand>
{
        public DeleteVenueCommandValidator()
        {
          
            RuleFor(v => v.Id).NotNull().ForEach(v=>v.GreaterThan(0));
          
        }
}
    

