//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// QuoteVersionDto: transfers quoteversion data between layers.
// Docs: https://docs.cleanarchitectureblazor.com/features/quoteversion
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings


namespace CleanArchitecture.Blazor.Application.Features.QuoteVersions.DTOs;

[Description("QuoteVersions")]
public class QuoteVersionDto
{
    [Description("Id")]
    public int Id { get; set; }
        [Description("Quote id")]
    public int QuoteId {get;set;} 
    [Description("Quote")]
    public QuoteDto? Quote {get;set;} 
    [Description("Version number")]
    public int VersionNumber {get;set;} 
    [Description("Created at utc")]
    public DateTime? CreatedAtUtc {get;set;} 
    [Description("Created by employee id")]
    public int CreatedByEmployeeId {get;set;} 
    [Description("Created by employee")]
    public EmployeeDto? CreatedByEmployee {get;set;} 
    [Description("Lines")]
    public List<QuoteLineDto>? Lines {get;set;} 


    private class Mapping : Profile
    {
        public Mapping()
        {
            CreateMap<QuoteVersion, QuoteVersionDto>(MemberList.None);
            CreateMap<QuoteVersionDto, QuoteVersion>(MemberList.None)
            .ForMember(dest => dest.Created, opt => opt.Ignore())
            .ForMember(dest => dest.CreatedBy, opt => opt.Ignore())
            .ForMember(dest => dest.LastModified, opt => opt.Ignore())
            .ForMember(dest => dest.LastModifiedBy, opt => opt.Ignore())
            .ForMember(dest => dest.DomainEvents, opt => opt.Ignore());
        }
    }
}

