//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Validator for CreateCostItemCommand: enforces max lengths and required fields for CostItem entities.
// Docs: https://docs.cleanarchitectureblazor.com/features/costitem
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.CostItems.Commands.Create;

public class CreateCostItemCommandValidator : AbstractValidator<CreateCostItemCommand>
{
        public CreateCostItemCommandValidator()
        {
                RuleFor(v => v.ProjectId).NotNull(); 
    RuleFor(v => v.Description).MaximumLength(255); 
    RuleFor(v => v.Quantity).NotNull(); 
    RuleFor(v => v.UnitCost).NotNull(); 
    RuleFor(v => v.TotalCost).NotNull(); 
    RuleFor(v => v.Category).MaximumLength(255); 

        }
       
}

