//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Handles QuoteUpdatedEvent: triggered when a quote is updated.
// Extendable for additional actions (e.g., notifications, system updates).
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Application.Features.Quotes.EventHandlers;

    public class QuoteUpdatedEventHandler : INotificationHandler<QuoteUpdatedEvent>
    {
        private readonly ILogger<QuoteUpdatedEventHandler> _logger;

        public QuoteUpdatedEventHandler(
            ILogger<QuoteUpdatedEventHandler> logger
            )
        {
            _logger = logger;
        }
        public Task Handle(QuoteUpdatedEvent notification, CancellationToken cancellationToken)
        {
            _logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
            return Task.CompletedTask;
        }
    }
