//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Handles QuoteDeletedEvent: triggered when a quote is deleted.
// Extendable for additional actions (e.g., notifications, system updates).
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Application.Features.Quotes.EventHandlers;

    public class QuoteDeletedEventHandler : INotificationHandler<QuoteDeletedEvent>
    {
        private readonly ILogger<QuoteDeletedEventHandler> _logger;

        public QuoteDeletedEventHandler(
            ILogger<QuoteDeletedEventHandler> logger
            )
        {
            _logger = logger;
        }
        public Task Handle(QuoteDeletedEvent notification, CancellationToken cancellationToken)
        {
            _logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
            return Task.CompletedTask;
        }
    }
