//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Handles QuoteCreatedEvent: triggered when a new quote is created.
// Extendable for additional actions (e.g., notifications, system updates).
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Application.Features.Quotes.EventHandlers;

public class QuoteCreatedEventHandler : INotificationHandler<QuoteCreatedEvent>
{
        private readonly ILogger<QuoteCreatedEventHandler> _logger;

        public QuoteCreatedEventHandler(
            ILogger<QuoteCreatedEventHandler> logger
            )
        {
            _logger = logger;
        }
        public Task Handle(QuoteCreatedEvent notification, CancellationToken cancellationToken)
        {
            _logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
            return Task.CompletedTask;
        }
}
