//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Validator for DeleteQuoteAttachmentCommand: ensures the ID list for quoteattachment is not null and contains only positive IDs.
// Docs: https://docs.cleanarchitectureblazor.com/features/quoteattachment
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.QuoteAttachments.Commands.Delete;

public class DeleteQuoteAttachmentCommandValidator : AbstractValidator<DeleteQuoteAttachmentCommand>
{
        public DeleteQuoteAttachmentCommandValidator()
        {
          
            RuleFor(v => v.Id).NotNull().ForEach(v=>v.GreaterThan(0));
          
        }
}
    

