//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under one or more agreements.
//     The .NET Foundation licenses this file to you under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-02-04
//     Last Modified: 2025-02-04
//     Description: 
//       Defines mapping methods between `Step` entities and related DTOs/commands 
//       within the CleanArchitecture.Blazor application. This mapper facilitates 
//       conversions to support different operations, such as creating, updating, 
//       and projecting step data.
// </auto-generated>
//------------------------------------------------------------------------------

using CleanArchitecture.Blazor.Application.Features.Steps.Commands.AddEdit;
using CleanArchitecture.Blazor.Application.Features.Steps.Commands.Create;
using CleanArchitecture.Blazor.Application.Features.Steps.Commands.Update;
using CleanArchitecture.Blazor.Application.Features.Steps.DTOs;

namespace CleanArchitecture.Blazor.Application.Features.Steps.Mappers;

#pragma warning disable RMG020
#pragma warning disable RMG012
[Mapper]
public static partial class StepMapper
{
    public static partial StepDto ToDto(Step source);
    public static partial Step FromDto(StepDto dto);
    public static partial Step FromEditCommand(AddEditStepCommand command);
    public static partial Step FromCreateCommand(CreateStepCommand command);
    public static partial UpdateStepCommand ToUpdateCommand(StepDto dto);
    public static partial AddEditStepCommand CloneFromDto(StepDto dto);
    public static partial void ApplyChangesFrom(UpdateStepCommand source, Step target);
    public static partial void ApplyChangesFrom(AddEditStepCommand source, Step target);
    public static partial IQueryable<StepDto> ProjectTo(this IQueryable<Step> q);
}

