////------------------------------------------------------------------------------
//// <auto-generated>
//// CleanArchitecture.Blazor - MIT Licensed.
//// Author: neozhu
//// Created/Modified: 2025-09-24
//// Import command & template for costitems.
//// Validates Excel data, prevents duplicates, and provides a template for bulk entry.
//// Docs: https://docs.cleanarchitectureblazor.com/features/costitem
//// </auto-generated>
////------------------------------------------------------------------------------
//#nullable enable
//#nullable disable warnings

//using CleanArchitecture.Blazor.Application.Features.CostItems.DTOs;
//using CleanArchitecture.Blazor.Application.Features.CostItems.Caching;

//namespace CleanArchitecture.Blazor.Application.Features.CostItems.Commands.Import;

//    public class ImportCostItemsCommand: ICacheInvalidatorRequest<Result<int>>
//    {
//        public string FileName { get; set; }
//        public byte[] Data { get; set; }
//        public string CacheKey => CostItemCacheKey.GetAllCacheKey;
//        public IEnumerable<string>? Tags => CostItemCacheKey.Tags;
//        public ImportCostItemsCommand(string fileName,byte[] data)
//        {
//           FileName = fileName;
//           Data = data;
//        }
//    }
//    public record class CreateCostItemsTemplateCommand : IRequest<Result<byte[]>>
//    {
 
//    }

//    public class ImportCostItemsCommandHandler : 
//                 IRequestHandler<CreateCostItemsTemplateCommand, Result<byte[]>>,
//                 IRequestHandler<ImportCostItemsCommand, Result<int>>
//    {
//        private readonly IApplicationDbContext _context;
//        private readonly IStringLocalizer<ImportCostItemsCommandHandler> _localizer;
//        private readonly IExcelService _excelService;
//        private readonly CostItemDto _dto = new();
//        private readonly IMapper _mapper;
//        public ImportCostItemsCommandHandler(
//            IApplicationDbContext context,
//            IMapper mapper,
//            IExcelService excelService,
//            IStringLocalizer<ImportCostItemsCommandHandler> localizer)
//        {
//            _context = context;
//            _localizer = localizer;
//            _excelService = excelService;
//            _mapper = mapper;
//        }
//        #nullable disable warnings
//        public async Task<Result<int>> Handle(ImportCostItemsCommand request, CancellationToken cancellationToken)
//        {

//           var result = await _excelService.ImportAsync(request.Data, mappers: new Dictionary<string, Func<DataRow, CostItemDto, object?>>
//            {
//                                { _localizer[_dto.GetMemberDescription(x=>x.ProjectId)], (row, item) => item.ProjectId =Convert.ToInt32(row[_localizer[_dto.GetMemberDescription(x=>x.ProjectId)]]) }, 
//                { _localizer[_dto.GetMemberDescription(x=>x.VendorId)], (row, item) => item.VendorId =Convert.ToInt32(row[_localizer[_dto.GetMemberDescription(x=>x.VendorId)]]) }, 
//                { _localizer[_dto.GetMemberDescription(x=>x.Description)], (row, item) => item.Description = row[_localizer[_dto.GetMemberDescription(x=>x.Description)]].ToString() }, 
//                { _localizer[_dto.GetMemberDescription(x=>x.Quantity)], (row, item) => item.Quantity =Convert.ToDecimal(row[_localizer[_dto.GetMemberDescription(x=>x.Quantity)]]) }, 
//                { _localizer[_dto.GetMemberDescription(x=>x.UnitCost)], (row, item) => item.UnitCost =Convert.ToDecimal(row[_localizer[_dto.GetMemberDescription(x=>x.UnitCost)]]) }, 
//                { _localizer[_dto.GetMemberDescription(x=>x.TotalCost)], (row, item) => item.TotalCost =Convert.ToDecimal(row[_localizer[_dto.GetMemberDescription(x=>x.TotalCost)]]) }, 
//                { _localizer[_dto.GetMemberDescription(x=>x.Category)], (row, item) => item.Category = row[_localizer[_dto.GetMemberDescription(x=>x.Category)]].ToString() }, 

//            }, _localizer[_dto.GetClassDescription()]);
//            if (result.Succeeded && result.Data is not null)
//            {
//                foreach (var dto in result.Data)
//                {
//                    var exists = await _context.CostItems.AnyAsync(x => x.Name == dto.Name, cancellationToken);
//                    if (!exists)
//                    {
//                        var item = _mapper.Map<CostItem>(dto);
//                        // add create domain events if this entity implement the IHasDomainEvent interface
//				        // item.AddDomainEvent(new CostItemCreatedEvent(item));
//                        await _context.CostItems.AddAsync(item, cancellationToken);
//                    }
//                 }
//                 await _context.SaveChangesAsync(cancellationToken);
//                 return await Result<int>.SuccessAsync(result.Data.Count());
//           }
//           else
//           {
//               return await Result<int>.FailureAsync(result.Errors);
//           }
//        }
//        public async Task<Result<byte[]>> Handle(CreateCostItemsTemplateCommand request, CancellationToken cancellationToken)
//        {
//            // TODO: Implement ImportCostItemsCommandHandler method 
//            var fields = new string[] {
//                   // TODO: Define the fields that should be generate in the template, for example:
//                   _localizer[_dto.GetMemberDescription(x=>x.ProjectId)], 
//_localizer[_dto.GetMemberDescription(x=>x.VendorId)], 
//_localizer[_dto.GetMemberDescription(x=>x.Description)], 
//_localizer[_dto.GetMemberDescription(x=>x.Quantity)], 
//_localizer[_dto.GetMemberDescription(x=>x.UnitCost)], 
//_localizer[_dto.GetMemberDescription(x=>x.TotalCost)], 
//_localizer[_dto.GetMemberDescription(x=>x.Category)], 

//                };
//            var result = await _excelService.CreateTemplateAsync(fields, _localizer[_dto.GetClassDescription()]);
//            return await Result<byte[]>.SuccessAsync(result);
//        }
//    }

