//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-09-24
//     Last Modified: 2025-09-24
//     Description: 
//       Defines a query for retrieving quotes with pagination and filtering 
//       options. The result is cached to enhance performance for repeated queries.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Quotes.DTOs;
using CleanArchitecture.Blazor.Application.Features.Quotes.Caching;
using CleanArchitecture.Blazor.Application.Features.Quotes.Specifications;

namespace CleanArchitecture.Blazor.Application.Features.Quotes.Queries.Pagination;

public class QuotesWithPaginationQuery : QuoteAdvancedFilter, ICacheableRequest<PaginatedData<QuoteDto>>
{
    public override string ToString()
    {
        return $"Listview:{ListView}:{CurrentUser?.UserId}, Search:{Keyword}, {OrderBy}, {SortDirection}, {PageNumber}, {PageSize}";
    }
    public string CacheKey => QuoteCacheKey.GetPaginationCacheKey($"{this}");
    public IEnumerable<string>? Tags => QuoteCacheKey.Tags;
    public QuoteAdvancedSpecification Specification => new QuoteAdvancedSpecification(this);
}
    
public class QuotesWithPaginationQueryHandler :
         IRequestHandler<QuotesWithPaginationQuery, PaginatedData<QuoteDto>>
{
        private readonly IApplicationDbContextFactory _dbContextFactory;
        private readonly IMapper _mapper;
        public QuotesWithPaginationQueryHandler(
            IMapper mapper,
            IApplicationDbContextFactory dbContextFactory)
        {
            _mapper = mapper;
            _dbContextFactory = dbContextFactory;
        }   

        public async Task<PaginatedData<QuoteDto>> Handle(QuotesWithPaginationQuery request, CancellationToken cancellationToken)
        {
        await using var _context = await _dbContextFactory.CreateAsync(cancellationToken);
        var data = await _context.Quotes.OrderBy($"{request.OrderBy} {request.SortDirection}")
                                                   .ProjectToPaginatedDataAsync<Quote, QuoteDto>(request.Specification,
                                                    request.PageNumber,
                                                    request.PageSize,
                                                    _mapper.ConfigurationProvider,
                                                    cancellationToken);
            return data;
        }
}