//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Validator for UpdatePricingModelCommand: ensures required fields (e.g., Id, non-empty Name, max length for properties) are valid for updating a pricingmodel.
// Docs: https://docs.cleanarchitectureblazor.com/features/pricingmodel
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.PricingModels.Commands.Update;

public class UpdatePricingModelCommandValidator : AbstractValidator<UpdatePricingModelCommand>
{
        public UpdatePricingModelCommandValidator()
        {
           RuleFor(v => v.Id).NotNull();
               RuleFor(v => v.Name).MaximumLength(50).NotEmpty(); 
    RuleFor(v => v.Type).NotNull(); 
    RuleFor(v => v.FormulaExpression).MaximumLength(255); 
    RuleFor(v => v.Notes).MaximumLength(255); 

          
        }
    
}

