//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Validator for CreateQuoteVersionCommand: enforces max lengths and required fields for QuoteVersion entities.
// Docs: https://docs.cleanarchitectureblazor.com/features/quoteversion
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.QuoteVersions.Commands.Create;

public class CreateQuoteVersionCommandValidator : AbstractValidator<CreateQuoteVersionCommand>
{
        public CreateQuoteVersionCommandValidator()
        {
                RuleFor(v => v.QuoteId).NotNull(); 
    RuleFor(v => v.VersionNumber).NotNull(); 
    RuleFor(v => v.CreatedAtUtc).NotNull(); 
    RuleFor(v => v.CreatedByEmployeeId).NotNull(); 

        }
       
}

