//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Validator for CreateEmployeeCommand: enforces max lengths and required fields for Employee entities.
// Docs: https://docs.cleanarchitectureblazor.com/features/employee
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.Employees.Commands.Create;

public class CreateEmployeeCommandValidator : AbstractValidator<CreateEmployeeCommand>
{
        public CreateEmployeeCommandValidator()
        {
                RuleFor(v => v.FirstName).MaximumLength(255); 
    RuleFor(v => v.LastName).MaximumLength(255); 
    RuleFor(v => v.Email).MaximumLength(255); 
    RuleFor(v => v.Phone).MaximumLength(255); 
    RuleFor(v => v.Position).MaximumLength(255); 

        }
       
}

