//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Handles PurchaseOrderCreatedEvent: triggered when a new purchaseorder is created.
// Extendable for additional actions (e.g., notifications, system updates).
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Application.Features.PurchaseOrders.EventHandlers;

public class PurchaseOrderCreatedEventHandler : INotificationHandler<PurchaseOrderCreatedEvent>
{
        private readonly ILogger<PurchaseOrderCreatedEventHandler> _logger;

        public PurchaseOrderCreatedEventHandler(
            ILogger<PurchaseOrderCreatedEventHandler> logger
            )
        {
            _logger = logger;
        }
        public Task Handle(PurchaseOrderCreatedEvent notification, CancellationToken cancellationToken)
        {
            _logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
            return Task.CompletedTask;
        }
}
