//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Handles PurchaseOrderDeletedEvent: triggered when a purchaseorder is deleted.
// Extendable for additional actions (e.g., notifications, system updates).
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Application.Features.PurchaseOrders.EventHandlers;

    public class PurchaseOrderDeletedEventHandler : INotificationHandler<PurchaseOrderDeletedEvent>
    {
        private readonly ILogger<PurchaseOrderDeletedEventHandler> _logger;

        public PurchaseOrderDeletedEventHandler(
            ILogger<PurchaseOrderDeletedEventHandler> logger
            )
        {
            _logger = logger;
        }
        public Task Handle(PurchaseOrderDeletedEvent notification, CancellationToken cancellationToken)
        {
            _logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
            return Task.CompletedTask;
        }
    }
