//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Validator for UpdateQuoteAttachmentCommand: ensures required fields (e.g., Id, non-empty Name, max length for properties) are valid for updating a quoteattachment.
// Docs: https://docs.cleanarchitectureblazor.com/features/quoteattachment
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.QuoteAttachments.Commands.Update;

public class UpdateQuoteAttachmentCommandValidator : AbstractValidator<UpdateQuoteAttachmentCommand>
{
        public UpdateQuoteAttachmentCommandValidator()
        {
           RuleFor(v => v.Id).NotNull();
               RuleFor(v => v.QuoteId).NotNull(); 
    RuleFor(v => v.FileName).MaximumLength(255); 
    RuleFor(v => v.FilePath).MaximumLength(255); 
    RuleFor(v => v.UploadedAtUtc).NotNull(); 

          
        }
    
}

