//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-09-24
//     Last Modified: 2025-09-24
//     Description: 
//       Defines a query to export service data to an Excel file. This query 
//       applies advanced filtering options and generates an Excel file with 
//       the specified service details.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Services.DTOs;
using CleanArchitecture.Blazor.Application.Features.Services.Caching;
using CleanArchitecture.Blazor.Application.Features.Services.Specifications;

namespace CleanArchitecture.Blazor.Application.Features.Services.Queries.Export;

public class ExportServicesQuery : ServiceAdvancedFilter, ICacheableRequest<Result<byte[]>>
{
      public ServiceAdvancedSpecification Specification => new ServiceAdvancedSpecification(this);
      public IEnumerable<string>? Tags => ServiceCacheKey.Tags;
    public override string ToString()
    {
        return $"Listview:{ListView}:{CurrentUser?.UserId}, Search:{Keyword}, {OrderBy}, {SortDirection}";
    }
    public string CacheKey => ServiceCacheKey.GetExportCacheKey($"{this}");
}
    
public class ExportServicesQueryHandler :
         IRequestHandler<ExportServicesQuery, Result<byte[]>>
{
        private readonly IMapper _mapper;
        private readonly IApplicationDbContextFactory _dbContextFactory;;
        private readonly IExcelService _excelService;
        private readonly IStringLocalizer<ExportServicesQueryHandler> _localizer;
        private readonly ServiceDto _dto = new();
        public ExportServicesQueryHandler(
            IMapper mapper,
            IApplicationDbContext context,
            IExcelService excelService,
            IStringLocalizer<ExportServicesQueryHandler> localizer
            )
        {
            _mapper = mapper;
            _context = context;
            _excelService = excelService;
            _localizer = localizer;
        }
        #nullable disable warnings
        public async Task<Result<byte[]>> Handle(ExportServicesQuery request, CancellationToken cancellationToken)
        {
            var data = await _context.Services.ApplySpecification(request.Specification)
                       .OrderBy($"{request.OrderBy} {request.SortDirection}")
                       .ProjectTo<ServiceDto>(_mapper.ConfigurationProvider)
                       .AsNoTracking()
                       .ToListAsync(cancellationToken);
            var result = await _excelService.ExportAsync(data,
                new Dictionary<string, Func<ServiceDto, object?>>()
                {
                    // TODO: Define the fields that should be exported, for example:
                                     {_localizer[_dto.GetMemberDescription(x=>x.ServiceCategoryId)],item => item.ServiceCategoryId}, 
                 {_localizer[_dto.GetMemberDescription(x=>x.Name)],item => item.Name}, 
                 {_localizer[_dto.GetMemberDescription(x=>x.Description)],item => item.Description}, 
                    {_localizer[_dto.GetMemberDescription(x=>x.DefaultPricingModel)],item => item.DefaultPricingModel?.ToString()}, 

                }
                , _localizer[_dto.GetClassDescription()]);
            return await Result<byte[]>.SuccessAsync(result);
        }
}
