//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-09-24
//     Last Modified: 2025-09-24
//     Description: 
//       Defines a query to retrieve all equipmentitems from the database. The result 
//       is cached to improve performance and reduce database load for repeated 
//       queries.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.EquipmentItems.DTOs;
using CleanArchitecture.Blazor.Application.Features.EquipmentItems.Caching;

namespace CleanArchitecture.Blazor.Application.Features.EquipmentItems.Queries.GetAll;

public class GetAllEquipmentItemsQuery : ICacheableRequest<IEnumerable<EquipmentItemDto>>
{
   public string CacheKey => EquipmentItemCacheKey.GetAllCacheKey;
   public IEnumerable<string>? Tags => EquipmentItemCacheKey.Tags;
}

public class GetAllEquipmentItemsQueryHandler :
     IRequestHandler<GetAllEquipmentItemsQuery, IEnumerable<EquipmentItemDto>>
{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    private readonly IMapper _mapper;
    public GetAllEquipmentItemsQueryHandler(
        IMapper mapper,
        IApplicationDbContextFactory dbContextFactory)
    {
        _mapper = mapper;
        _dbContextFactory = dbContextFactory;
    }

    public async Task<IEnumerable<EquipmentItemDto>> Handle(GetAllEquipmentItemsQuery request, CancellationToken cancellationToken)
    {
        await using var _context = await _dbContextFactory.CreateAsync(cancellationToken);
        var data = await _context.EquipmentItems.ProjectTo<EquipmentItemDto>(_mapper.ConfigurationProvider)
                                                .AsNoTracking()
                                                .ToListAsync(cancellationToken);
        return data;
    }
}


