//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-09-23
//     Last Modified: 2025-09-23
//     Description: 
//       Defines the available views for filtering companys and provides advanced 
//       filtering options for company lists. This includes pagination and various 
//       filters such as view types and user-specific filters.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.Companies.Specifications;

#nullable disable warnings
/// <summary>
/// Specifies the different views available for the Company list.
/// </summary>
public enum CompanyListView
{
    [Description("All")]
    All,
    [Description("My")]
    My,
    [Description("Created Toady")]
    TODAY,
    [Description("Created within the last 30 days")]
    LAST_30_DAYS
}
/// <summary>
/// A class for applying advanced filtering options to Company lists.
/// </summary>
public class CompanyAdvancedFilter: PaginationFilter
{
    public CompanyListView ListView { get; set; } = CompanyListView.All;
    public UserProfile? CurrentUser { get; set; }
}