//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-09-24
//     Last Modified: 2025-09-24
//     Description: 
//       Defines a query to retrieve a vendor by its ID. The result is cached 
//       to optimize performance for repeated retrievals of the same vendor.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Vendors.DTOs;
using CleanArchitecture.Blazor.Application.Features.Vendors.Caching;
using CleanArchitecture.Blazor.Application.Features.Vendors.Specifications;

namespace CleanArchitecture.Blazor.Application.Features.Vendors.Queries.GetById;

public class GetVendorByIdQuery : ICacheableRequest<Result<VendorDto>>
{
   public required int Id { get; set; }
   public string CacheKey => VendorCacheKey.GetByIdCacheKey($"{Id}");
   public IEnumerable<string>? Tags => VendorCacheKey.Tags;
}

public class GetVendorByIdQueryHandler :
     IRequestHandler<GetVendorByIdQuery, Result<VendorDto>>
{
    private readonly IApplicationDbContext _context;
    private readonly IMapper _mapper;
    public GetVendorByIdQueryHandler(
        IMapper mapper,
        IApplicationDbContext context)
    {
        _mapper = mapper;
        _context = context;
    }

    public async Task<Result<VendorDto>> Handle(GetVendorByIdQuery request, CancellationToken cancellationToken)
    {
        var data = await _context.Vendors.ApplySpecification(new VendorByIdSpecification(request.Id))
                                                .ProjectTo<VendorDto>(_mapper.ConfigurationProvider)
                                                .FirstAsync(cancellationToken) ?? throw new NotFoundException($"Vendor with id: [{request.Id}] not found.");
        return await Result<VendorDto>.SuccessAsync(data);
    }
}
