//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Handles QuoteLineCreatedEvent: triggered when a new quoteline is created.
// Extendable for additional actions (e.g., notifications, system updates).
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Application.Features.QuoteLines.EventHandlers;

public class QuoteLineCreatedEventHandler : INotificationHandler<QuoteLineCreatedEvent>
{
        private readonly ILogger<QuoteLineCreatedEventHandler> _logger;

        public QuoteLineCreatedEventHandler(
            ILogger<QuoteLineCreatedEventHandler> logger
            )
        {
            _logger = logger;
        }
        public Task Handle(QuoteLineCreatedEvent notification, CancellationToken cancellationToken)
        {
            _logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
            return Task.CompletedTask;
        }
}
