//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-23
// UpdateVenueCommand & handler: updates an existing Venue with cache invalidation and raises VenueUpdatedEvent.
// Docs: https://docs.cleanarchitectureblazor.com/features/venue
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Venues.DTOs;
using CleanArchitecture.Blazor.Application.Features.Venues.Caching;

namespace CleanArchitecture.Blazor.Application.Features.Venues.Commands.Update;

public class UpdateVenueCommand: ICacheInvalidatorRequest<Result<int>>
{
      [Description("Id")]
      public int Id { get; set; }
          [Description("Name")]
    public string Name {get;set;} 
    [Description("Location")]
    public string? Location {get;set;} 
    [Description("Capacity")]
    public int? Capacity {get;set;} 
    [Description("Venue fee")]
    public decimal? VenueFee {get;set;} 

      public string CacheKey => VenueCacheKey.GetAllCacheKey;
      public IEnumerable<string>? Tags => VenueCacheKey.Tags;

    private class Mapping : Profile
    {
        public Mapping()
        {
            CreateMap<UpdateVenueCommand, Venue>(MemberList.None);
            CreateMap<VenueDto,UpdateVenueCommand>(MemberList.None);
        }
    }

}

public class UpdateVenueCommandHandler : IRequestHandler<UpdateVenueCommand, Result<int>>
{
    private readonly IApplicationDbContext _context;
    private readonly IMapper _mapper;
    public UpdateVenueCommandHandler(
        IMapper mapper,
        IApplicationDbContext context)
    {
        _context = context;
        _mapper = mapper;
    }
    public async Task<Result<int>> Handle(UpdateVenueCommand request, CancellationToken cancellationToken)
    {

       var item = await _context.Venues.FindAsync(request.Id, cancellationToken);
       if (item == null)
       {
           return await Result<int>.FailureAsync($"Venue with id: [{request.Id}] not found.");
       }
       item = _mapper.Map(request, item);
	    // raise a update domain event
	   item.AddDomainEvent(new VenueUpdatedEvent(item));
       await _context.SaveChangesAsync(cancellationToken);
       return await Result<int>.SuccessAsync(item.Id);
    }
}

