//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-23
// Validator for UpdateVenueCommand: ensures required fields (e.g., Id, non-empty Name, max length for properties) are valid for updating a venue.
// Docs: https://docs.cleanarchitectureblazor.com/features/venue
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.Venues.Commands.Update;

public class UpdateVenueCommandValidator : AbstractValidator<UpdateVenueCommand>
{
        public UpdateVenueCommandValidator()
        {
           RuleFor(v => v.Id).NotNull();
               RuleFor(v => v.Name).MaximumLength(50).NotEmpty(); 
    RuleFor(v => v.Location).MaximumLength(255); 

          
        }
    
}

