//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Validator for AddEditQuoteApprovalCommand: enforces field length and required property rules for QuoteApproval entities.
// Docs: https://docs.cleanarchitectureblazor.com/features/quoteapproval
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings


namespace CleanArchitecture.Blazor.Application.Features.QuoteApprovals.Commands.AddEdit;

public class AddEditQuoteApprovalCommandValidator : AbstractValidator<AddEditQuoteApprovalCommand>
{
    public AddEditQuoteApprovalCommandValidator()
    {
                RuleFor(v => v.QuoteId).NotNull(); 
    RuleFor(v => v.ApproverId).NotNull(); 
    RuleFor(v => v.Status).NotNull(); 
    RuleFor(v => v.Comment).MaximumLength(255); 

     }

}

