//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-03-27
//     Last Modified: 2025-03-27
//     Description: 
//       Defines a specification for filtering a PurchaseItem entity by its ID.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanArchitecture.Blazor.Application.Features.PurchaseItems.Specifications;
#nullable disable warnings
/// <summary>
/// Specification class for filtering PurchaseItems by their ID.
/// </summary>
public class PurchaseItemByIdSpecification : Specification<PurchaseItem>
{
    public PurchaseItemByIdSpecification(int id)
    {
       Query.Where(q => q.Id == id);
    }
}