//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Validator for CreateQuoteAttachmentCommand: enforces max lengths and required fields for QuoteAttachment entities.
// Docs: https://docs.cleanarchitectureblazor.com/features/quoteattachment
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.QuoteAttachments.Commands.Create;

public class CreateQuoteAttachmentCommandValidator : AbstractValidator<CreateQuoteAttachmentCommand>
{
        public CreateQuoteAttachmentCommandValidator()
        {
                RuleFor(v => v.QuoteId).NotNull(); 
    RuleFor(v => v.FileName).MaximumLength(255); 
    RuleFor(v => v.FilePath).MaximumLength(255); 
    RuleFor(v => v.UploadedAtUtc).NotNull(); 

        }
       
}

