//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Command and handler for creating a new QuoteAttachment.
// Uses caching invalidation and domain events for data consistency.
// Docs: https://docs.cleanarchitectureblazor.com/features/quoteattachment
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.QuoteAttachments.Caching;

namespace CleanArchitecture.Blazor.Application.Features.QuoteAttachments.Commands.Create;

public class CreateQuoteAttachmentCommand: ICacheInvalidatorRequest<Result<int>>
{
      [Description("Id")]
      public int Id { get; set; }
          [Description("Quote id")]
    public int QuoteId {get;set;} 
    [Description("Quote")]
    public QuoteDto? Quote {get;set;} 
    [Description("File name")]
    public string? FileName {get;set;} 
    [Description("File path")]
    public string? FilePath {get;set;} 
    [Description("Uploaded at utc")]
    public DateTime? UploadedAtUtc {get;set;} 

      public string CacheKey => QuoteAttachmentCacheKey.GetAllCacheKey;
      public IEnumerable<string>? Tags => QuoteAttachmentCacheKey.Tags;
      private class Mapping : Profile
    {
        public Mapping()
        {
            CreateMap<CreateQuoteAttachmentCommand, QuoteAttachment>(MemberList.None);
        }
    }
}
    
    public class CreateQuoteAttachmentCommandHandler : IRequestHandler<CreateQuoteAttachmentCommand, Result<int>>
    {
        private readonly IMapper _mapper;
        private readonly IApplicationDbContext _context;
        public CreateQuoteAttachmentCommandHandler(
            IMapper mapper,
            IApplicationDbContext context)
        {
            _mapper = mapper;
            _context = context;
        }
        public async Task<Result<int>> Handle(CreateQuoteAttachmentCommand request, CancellationToken cancellationToken)
        {
           var item = _mapper.Map<QuoteAttachment>(request);
           // raise a create domain event
	       item.AddDomainEvent(new QuoteAttachmentCreatedEvent(item));
           _context.QuoteAttachments.Add(item);
           await _context.SaveChangesAsync(cancellationToken);
           return  await Result<int>.SuccessAsync(item.Id);
        }
    }

