//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under one or more agreements.
//     The .NET Foundation licenses this file to you under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-03-27
//     Last Modified: 2025-03-27
//     Description: 
//       This file defines the Data Transfer Object (DTO) for the PurchaseInvoice entity 
//       used within the CleanArchitecture.Blazor application. The PurchaseInvoiceDto is 
//       responsible for transferring data between layers while maintaining the 
//       structure and format required by application features like commands, queries, 
//       and views.
//     
//     Documentation:
//       https://docs.cleanarchitectureblazor.com/features/purchaseinvoice
// </auto-generated>
//------------------------------------------------------------------------------

// Usage:
// The `PurchaseInvoiceDto` class is used to represent purchaseinvoice data throughout the CleanArchitecture.Blazor
// application, providing a well-defined contract for passing purchaseinvoice information between different 
// layers and services. Each property includes a description for better understandability during 
// serialization and documentation generation.

using CleanArchitecture.Blazor.Application.Features.PurchaseItems.DTOs;
using CleanArchitecture.Blazor.Application.Features.Suppliers.DTOs;

namespace CleanArchitecture.Blazor.Application.Features.PurchaseInvoices.DTOs;

[Description("PurchaseInvoices")]
public class PurchaseInvoiceDto
{
    [Description("Id")]
    public int Id { get; set; }
        [Description("Supplier id")]
    public int SupplierId {get;set;} 
    [Description("Invoice number")]
    public string? InvoiceNumber {get;set;} 
    [Description("Invoice date")]
    public DateTime InvoiceDate {get;set;} 
    [Description("Invoice type")]
    public string? InvoiceType {get;set;} 
    [Description("Total amount")]
    public decimal TotalAmount {get;set;} 
    [Description("Vat amount")]
    public decimal VATAmount {get;set;} 
    [Description("Payment status")]
    public string? PaymentStatus {get;set;} 
    [Description("Payment method")]
    public string? PaymentMethod {get;set;} 
    [Description("Iban")]
    public string? IBAN {get;set;} 
    [Description("Swift")]
    public string? SWIFT {get;set;} 
    [Description("Notes")]
    public string? Notes {get;set;}
    [Description("Supplier")]
    public SupplierDto Supplier { get; set; }
    [Description("Items")]
    public List<PurchaseItemDto>? Items {get;set;} 


}

