//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Command and handler for deleting EquipmentItem entities.
// Implements cache invalidation and triggers domain events.
// Docs: https://docs.cleanarchitectureblazor.com/features/equipmentitem
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.EquipmentItems.Caching;

namespace CleanArchitecture.Blazor.Application.Features.EquipmentItems.Commands.Delete;

public class DeleteEquipmentItemCommand:  ICacheInvalidatorRequest<Result>
{
  public int[] Id {  get; }
  public string CacheKey => EquipmentItemCacheKey.GetAllCacheKey;
  public IEnumerable<string>? Tags => EquipmentItemCacheKey.Tags;
  public DeleteEquipmentItemCommand(int[] id)
  {
    Id = id;
  }
}

public class DeleteEquipmentItemCommandHandler : 
             IRequestHandler<DeleteEquipmentItemCommand, Result>

{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    public DeleteEquipmentItemCommandHandler(
        IApplicationDbContextFactory dbContextFactory)
    {
        _dbContextFactory = dbContextFactory;
    }
    public async Task<Result> Handle(DeleteEquipmentItemCommand request, CancellationToken cancellationToken)
    {
        await using var _context = await _dbContextFactory.CreateAsync(cancellationToken);
        var items = await _context.EquipmentItems.Where(x=>request.Id.Contains(x.Id)).ToListAsync(cancellationToken);
        foreach (var item in items)
        {
		    // raise a delete domain event
			item.AddDomainEvent(new EquipmentItemDeletedEvent(item));
            _context.EquipmentItems.Remove(item);
        }
        await _context.SaveChangesAsync(cancellationToken);
        return await Result.SuccessAsync();
    }

}

