//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Command for adding/editing a projecttask entity with validation, mapping,
// domain events, and cache invalidation.
// Documentation: https://docs.cleanarchitectureblazor.com/features/projecttask
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings


using CleanArchitecture.Blazor.Application.Features.ProjectTasks.Caching;
using CleanArchitecture.Blazor.Application.Features.ProjectTasks.DTOs;
namespace CleanArchitecture.Blazor.Application.Features.ProjectTasks.Commands.AddEdit;

public class AddEditProjectTaskCommand: ICacheInvalidatorRequest<Result<int>>
{
      [Description("Id")]
      public int Id { get; set; }
          [Description("Project id")]
    public int ProjectId {get;set;} 
    [Description("Project")]
    public ProjectDto? Project {get;set;} 
    [Description("Assigned to id")]
    public int? AssignedToId {get;set;} 
    [Description("Assigned to")]
    public EmployeeDto? AssignedTo {get;set;} 
    [Description("Title")]
    public string? Title {get;set;} 
    [Description("Description")]
    public string? Description {get;set;} 
    [Description("Deadline")]
    public DateTime? Deadline {get;set;} 
    [Description("Status")]
    public CleanArchitecture.Blazor.Domain.Entities.TaskStatus? Status {get;set;} 
    [Description("Priority")]
    public TaskPriority? Priority {get;set;} 


      public string CacheKey => ProjectTaskCacheKey.GetAllCacheKey;
      public IEnumerable<string>? Tags => ProjectTaskCacheKey.Tags;
    private class Mapping : Profile
    {
        public Mapping()
        {
            CreateMap<ProjectTaskDto, AddEditProjectTaskCommand>(MemberList.None);
            CreateMap<AddEditProjectTaskCommand, ProjectTask>(MemberList.None);
        }
    }
}

public class AddEditProjectTaskCommandHandler : IRequestHandler<AddEditProjectTaskCommand, Result<int>>
{
    private readonly IMapper _mapper;
    private readonly IApplicationDbContextFactory _dbContextFactory;
    public AddEditProjectTaskCommandHandler(
        IMapper mapper,
        IApplicationDbContextFactory dbContextFactory)
    {
        _mapper = mapper;
        _dbContextFactory = dbContextFactory;
    }
    public async Task<Result<int>> Handle(AddEditProjectTaskCommand request, CancellationToken cancellationToken)
    {
        if (request.Id > 0)
        {
            await using var _context = await _dbContextFactory.CreateAsync(cancellationToken);
            var item = await _context.ProjectTasks.FindAsync(request.Id, cancellationToken);
            if (item == null)
            {
                return await Result<int>.FailureAsync($"ProjectTask with id: [{request.Id}] not found.");
            }
            item = _mapper.Map(request, item);
			// raise a update domain event
			item.AddDomainEvent(new ProjectTaskUpdatedEvent(item));
            await _context.SaveChangesAsync(cancellationToken);
            return await Result<int>.SuccessAsync(item.Id);
        }
        else
        {
            await using var _context = await _dbContextFactory.CreateAsync(cancellationToken);
            var item = _mapper.Map<ProjectTask>(request);
            // raise a create domain event
			item.AddDomainEvent(new ProjectTaskCreatedEvent(item));
            _context.ProjectTasks.Add(item);
            await _context.SaveChangesAsync(cancellationToken);
            return await Result<int>.SuccessAsync(item.Id);
        }
       
    }
}

