//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Validator for AddEditProjectTaskCommand: enforces field length and required property rules for ProjectTask entities.
// Docs: https://docs.cleanarchitectureblazor.com/features/projecttask
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings


namespace CleanArchitecture.Blazor.Application.Features.ProjectTasks.Commands.AddEdit;

public class AddEditProjectTaskCommandValidator : AbstractValidator<AddEditProjectTaskCommand>
{
    public AddEditProjectTaskCommandValidator()
    {
                RuleFor(v => v.ProjectId).NotNull(); 
    RuleFor(v => v.Title).MaximumLength(255); 
    RuleFor(v => v.Description).MaximumLength(255); 
    RuleFor(v => v.Status).NotNull(); 
    RuleFor(v => v.Priority).NotNull(); 

     }

}

