//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-09-24
//     Last Modified: 2025-09-24
//     Description: 
//       Defines a query to retrieve a service by its ID. The result is cached 
//       to optimize performance for repeated retrievals of the same service.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Services.DTOs;
using CleanArchitecture.Blazor.Application.Features.Services.Caching;
using CleanArchitecture.Blazor.Application.Features.Services.Specifications;

namespace CleanArchitecture.Blazor.Application.Features.Services.Queries.GetById;

public class GetServiceByIdQuery : ICacheableRequest<Result<ServiceDto>>
{
   public required int Id { get; set; }
   public string CacheKey => ServiceCacheKey.GetByIdCacheKey($"{Id}");
   public IEnumerable<string>? Tags => ServiceCacheKey.Tags;
}

public class GetServiceByIdQueryHandler :
     IRequestHandler<GetServiceByIdQuery, Result<ServiceDto>>
{
    private readonly IApplicationDbContext _context;
    private readonly IMapper _mapper;
    public GetServiceByIdQueryHandler(
        IMapper mapper,
        IApplicationDbContext context)
    {
        _mapper = mapper;
        _context = context;
    }

    public async Task<Result<ServiceDto>> Handle(GetServiceByIdQuery request, CancellationToken cancellationToken)
    {
        var data = await _context.Services.ApplySpecification(new ServiceByIdSpecification(request.Id))
                                                .ProjectTo<ServiceDto>(_mapper.ConfigurationProvider)
                                                .FirstAsync(cancellationToken) ?? throw new NotFoundException($"Service with id: [{request.Id}] not found.");
        return await Result<ServiceDto>.SuccessAsync(data);
    }
}
