//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-09-24
//     Last Modified: 2025-09-24
//     Description: 
//       Defines a query to export quoteapproval data to an Excel file. This query 
//       applies advanced filtering options and generates an Excel file with 
//       the specified quoteapproval details.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.QuoteApprovals.DTOs;
using CleanArchitecture.Blazor.Application.Features.QuoteApprovals.Caching;
using CleanArchitecture.Blazor.Application.Features.QuoteApprovals.Specifications;

namespace CleanArchitecture.Blazor.Application.Features.QuoteApprovals.Queries.Export;

public class ExportQuoteApprovalsQuery : QuoteApprovalAdvancedFilter, ICacheableRequest<Result<byte[]>>
{
      public QuoteApprovalAdvancedSpecification Specification => new QuoteApprovalAdvancedSpecification(this);
      public IEnumerable<string>? Tags => QuoteApprovalCacheKey.Tags;
    public override string ToString()
    {
        return $"Listview:{ListView}:{CurrentUser?.UserId}, Search:{Keyword}, {OrderBy}, {SortDirection}";
    }
    public string CacheKey => QuoteApprovalCacheKey.GetExportCacheKey($"{this}");
}
    
public class ExportQuoteApprovalsQueryHandler :
         IRequestHandler<ExportQuoteApprovalsQuery, Result<byte[]>>
{
        private readonly IMapper _mapper;
        private readonly IApplicationDbContextFactory _dbContextFactory;
        private readonly IExcelService _excelService;
        private readonly IStringLocalizer<ExportQuoteApprovalsQueryHandler> _localizer;
        private readonly QuoteApprovalDto _dto = new();
        public ExportQuoteApprovalsQueryHandler(
            IMapper mapper,
            IApplicationDbContextFactory dbContextFactory,
            IExcelService excelService,
            IStringLocalizer<ExportQuoteApprovalsQueryHandler> localizer
            )
        {
            _mapper = mapper;
            _dbContextFactory = dbContextFactory;
            _excelService = excelService;
            _localizer = localizer;
        }
        #nullable disable warnings
        public async Task<Result<byte[]>> Handle(ExportQuoteApprovalsQuery request, CancellationToken cancellationToken)
        {
        await using var _context = await _dbContextFactory.CreateAsync(cancellationToken);
        var data = await _context.QuoteApprovals.ApplySpecification(request.Specification)
                       .OrderBy($"{request.OrderBy} {request.SortDirection}")
                       .ProjectTo<QuoteApprovalDto>(_mapper.ConfigurationProvider)
                       .AsNoTracking()
                       .ToListAsync(cancellationToken);
            var result = await _excelService.ExportAsync(data,
                new Dictionary<string, Func<QuoteApprovalDto, object?>>()
                {
                    // TODO: Define the fields that should be exported, for example:
                                     {_localizer[_dto.GetMemberDescription(x=>x.QuoteId)],item => item.QuoteId}, 
                 {_localizer[_dto.GetMemberDescription(x=>x.ApproverId)],item => item.ApproverId}, 
                    {_localizer[_dto.GetMemberDescription(x=>x.Status)],item => item.Status?.ToString()}, 
                 {_localizer[_dto.GetMemberDescription(x=>x.ApprovedAtUtc)],item => item.ApprovedAtUtc}, 
                 {_localizer[_dto.GetMemberDescription(x=>x.Comment)],item => item.Comment}, 

                }
                , _localizer[_dto.GetClassDescription()]);
            return await Result<byte[]>.SuccessAsync(result);
        }
}
