//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-09-23
//     Last Modified: 2025-09-23
//     Description: 
//       Defines a query to retrieve all companys from the database. The result 
//       is cached to improve performance and reduce database load for repeated 
//       queries.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Companies.DTOs;
using CleanArchitecture.Blazor.Application.Features.Companies.Caching;

namespace CleanArchitecture.Blazor.Application.Features.Companies.Queries.GetAll;

public class GetAllCompaniesQuery : ICacheableRequest<IEnumerable<CompanyDto>>
{
   public string CacheKey => CompanyCacheKey.GetAllCacheKey;
   public IEnumerable<string>? Tags => CompanyCacheKey.Tags;
}

public class GetAllCompaniesQueryHandler :
     IRequestHandler<GetAllCompaniesQuery, IEnumerable<CompanyDto>>
{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    private readonly IMapper _mapper;
    public GetAllCompaniesQueryHandler(
        IMapper mapper,
        IApplicationDbContextFactory dbContextFactory)
    {
        _mapper = mapper;
        _dbContextFactory = dbContextFactory;
    }

    public async Task<IEnumerable<CompanyDto>> Handle(GetAllCompaniesQuery request, CancellationToken cancellationToken)
    {
        await using var _context = await _dbContextFactory.CreateAsync(cancellationToken);
        var data = await _context.Companies.ProjectTo<CompanyDto>(_mapper.ConfigurationProvider)
                                                .AsNoTracking()
                                                .ToListAsync(cancellationToken);
        return data;
    }
}


