//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-23
// Handles CompanyCreatedEvent: triggered when a new company is created.
// Extendable for additional actions (e.g., notifications, system updates).
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Application.Features.Companies.EventHandlers;

public class CompanyCreatedEventHandler : INotificationHandler<CompanyCreatedEvent>
{
        private readonly ILogger<CompanyCreatedEventHandler> _logger;

        public CompanyCreatedEventHandler(
            ILogger<CompanyCreatedEventHandler> logger
            )
        {
            _logger = logger;
        }
        public Task Handle(CompanyCreatedEvent notification, CancellationToken cancellationToken)
        {
            _logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
            return Task.CompletedTask;
        }
}
