//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-23
// Handles CompanyUpdatedEvent: triggered when a company is updated.
// Extendable for additional actions (e.g., notifications, system updates).
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Application.Features.Companies.EventHandlers;

    public class CompanyUpdatedEventHandler : INotificationHandler<CompanyUpdatedEvent>
    {
        private readonly ILogger<CompanyUpdatedEventHandler> _logger;

        public CompanyUpdatedEventHandler(
            ILogger<CompanyUpdatedEventHandler> logger
            )
        {
            _logger = logger;
        }
        public Task Handle(CompanyUpdatedEvent notification, CancellationToken cancellationToken)
        {
            _logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
            return Task.CompletedTask;
        }
    }
