//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Handles ServiceCategoryDeletedEvent: triggered when a servicecategory is deleted.
// Extendable for additional actions (e.g., notifications, system updates).
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Application.Features.ServiceCategories.EventHandlers;

    public class ServiceCategoryDeletedEventHandler : INotificationHandler<ServiceCategoryDeletedEvent>
    {
        private readonly ILogger<ServiceCategoryDeletedEventHandler> _logger;

        public ServiceCategoryDeletedEventHandler(
            ILogger<ServiceCategoryDeletedEventHandler> logger
            )
        {
            _logger = logger;
        }
        public Task Handle(ServiceCategoryDeletedEvent notification, CancellationToken cancellationToken)
        {
            _logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
            return Task.CompletedTask;
        }
    }
