//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Validator for UpdateEquipmentItemCommand: ensures required fields (e.g., Id, non-empty Name, max length for properties) are valid for updating a equipmentitem.
// Docs: https://docs.cleanarchitectureblazor.com/features/equipmentitem
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.EquipmentItems.Commands.Update;

public class UpdateEquipmentItemCommandValidator : AbstractValidator<UpdateEquipmentItemCommand>
{
        public UpdateEquipmentItemCommandValidator()
        {
           RuleFor(v => v.Id).NotNull();
               RuleFor(v => v.Name).MaximumLength(50).NotEmpty(); 
    RuleFor(v => v.Category).MaximumLength(255); 

          
        }
    
}

