//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-09-24
//     Last Modified: 2025-09-24
//     Description: 
//       Configures the properties and behaviors for the `Employee` entity in the 
//       database. Specifies property constraints such as maximum length and required fields.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace CleanArchitecture.Blazor.Infrastructure.Persistence.Configurations;

#nullable disable
public class EmployeeConfiguration : IEntityTypeConfiguration<Employee>
{
    public void Configure(EntityTypeBuilder<Employee> builder)
    {
            builder.Property(x => x.FirstName).HasMaxLength(255); 
    builder.Property(x => x.LastName).HasMaxLength(255); 
    builder.Property(x => x.Email).HasMaxLength(255); 
    builder.Property(x => x.Phone).HasMaxLength(255); 
    builder.Property(x => x.Position).HasMaxLength(255); 

        builder.Ignore(e => e.DomainEvents);
    }
}


