//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-09-24
//     Last Modified: 2025-09-24
//     Description: 
//       Configures the properties and behaviors for the `EquipmentItem` entity in the 
//       database. Specifies property constraints such as maximum length and required fields.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace CleanArchitecture.Blazor.Infrastructure.Persistence.Configurations;

#nullable disable
public class EquipmentItemConfiguration : IEntityTypeConfiguration<EquipmentItem>
{
    public void Configure(EntityTypeBuilder<EquipmentItem> builder)
    {
            builder.HasIndex(x => x.Name); 
    builder.Property(x => x.Name).HasMaxLength(50).IsRequired(); 
    builder.Property(x => x.Category).HasMaxLength(255); 
    builder.HasOne(x => x.Vendor).WithMany().HasForeignKey(x => x.VendorId); 

        builder.Ignore(e => e.DomainEvents);
    }
}


