//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-09-24
//     Last Modified: 2025-09-24
//     Description: 
//       Configures the properties and behaviors for the `Quote` entity in the 
//       database. Specifies property constraints such as maximum length and required fields.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace CleanArchitecture.Blazor.Infrastructure.Persistence.Configurations;

#nullable disable
public class QuoteConfiguration : IEntityTypeConfiguration<Quote>
{
    public void Configure(EntityTypeBuilder<Quote> builder)
    {
            builder.HasOne(x => x.Company).WithMany().HasForeignKey(x => x.CompanyId); 
    builder.Property(x => x.Title).HasMaxLength(255); 
    builder.HasOne(x => x.Owner).WithMany().HasForeignKey(x => x.OwnerId); 
    builder.HasIndex(x => x.Status); 
    builder.Property(t => t.Status).HasConversion<string>().HasMaxLength(50); 
    builder.Property(x => x.Currency).HasMaxLength(255); 

        builder.Ignore(e => e.DomainEvents);
    }
}


