//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-09-24
//     Last Modified: 2025-09-24
//     Description: 
//       Configures the properties and behaviors for the `Vendor` entity in the 
//       database. Specifies property constraints such as maximum length and required fields.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace CleanArchitecture.Blazor.Infrastructure.Persistence.Configurations;

#nullable disable
public class VendorConfiguration : IEntityTypeConfiguration<Vendor>
{
    public void Configure(EntityTypeBuilder<Vendor> builder)
    {
            builder.HasOne(x => x.Company).WithMany().HasForeignKey(x => x.CompanyId); 
    builder.HasOne(x => x.ServiceCategory).WithMany().HasForeignKey(x => x.ServiceCategoryId); 
    builder.Property(x => x.Terms).HasMaxLength(255); 

        builder.Ignore(e => e.DomainEvents);
    }
}


