//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-09-24
//     Last Modified: 2025-09-24
//     Description: 
//       Defines a query to export costitem data to an Excel file. This query 
//       applies advanced filtering options and generates an Excel file with 
//       the specified costitem details.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.CostItems.DTOs;
using CleanArchitecture.Blazor.Application.Features.CostItems.Caching;
using CleanArchitecture.Blazor.Application.Features.CostItems.Specifications;

namespace CleanArchitecture.Blazor.Application.Features.CostItems.Queries.Export;

public class ExportCostItemsQuery : CostItemAdvancedFilter, ICacheableRequest<Result<byte[]>>
{
      public CostItemAdvancedSpecification Specification => new CostItemAdvancedSpecification(this);
      public IEnumerable<string>? Tags => CostItemCacheKey.Tags;
    public override string ToString()
    {
        return $"Listview:{ListView}:{CurrentUser?.UserId}, Search:{Keyword}, {OrderBy}, {SortDirection}";
    }
    public string CacheKey => CostItemCacheKey.GetExportCacheKey($"{this}");
}
    
public class ExportCostItemsQueryHandler :
         IRequestHandler<ExportCostItemsQuery, Result<byte[]>>
{
        private readonly IMapper _mapper;
        private readonly IApplicationDbContext _context;
        private readonly IExcelService _excelService;
        private readonly IStringLocalizer<ExportCostItemsQueryHandler> _localizer;
        private readonly CostItemDto _dto = new();
        public ExportCostItemsQueryHandler(
            IMapper mapper,
            IApplicationDbContext context,
            IExcelService excelService,
            IStringLocalizer<ExportCostItemsQueryHandler> localizer
            )
        {
            _mapper = mapper;
            _context = context;
            _excelService = excelService;
            _localizer = localizer;
        }
        #nullable disable warnings
        public async Task<Result<byte[]>> Handle(ExportCostItemsQuery request, CancellationToken cancellationToken)
        {
            var data = await _context.CostItems.ApplySpecification(request.Specification)
                       .OrderBy($"{request.OrderBy} {request.SortDirection}")
                       .ProjectTo<CostItemDto>(_mapper.ConfigurationProvider)
                       .AsNoTracking()
                       .ToListAsync(cancellationToken);
            var result = await _excelService.ExportAsync(data,
                new Dictionary<string, Func<CostItemDto, object?>>()
                {
                    // TODO: Define the fields that should be exported, for example:
                                     {_localizer[_dto.GetMemberDescription(x=>x.ProjectId)],item => item.ProjectId}, 
                 {_localizer[_dto.GetMemberDescription(x=>x.VendorId)],item => item.VendorId}, 
                 {_localizer[_dto.GetMemberDescription(x=>x.Description)],item => item.Description}, 
                 {_localizer[_dto.GetMemberDescription(x=>x.Quantity)],item => item.Quantity}, 
                 {_localizer[_dto.GetMemberDescription(x=>x.UnitCost)],item => item.UnitCost}, 
                 {_localizer[_dto.GetMemberDescription(x=>x.TotalCost)],item => item.TotalCost}, 
                 {_localizer[_dto.GetMemberDescription(x=>x.Category)],item => item.Category}, 

                }
                , _localizer[_dto.GetClassDescription()]);
            return await Result<byte[]>.SuccessAsync(result);
        }
}
