//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Import command & template for quoteattachments.
// Validates Excel data, prevents duplicates, and provides a template for bulk entry.
// Docs: https://docs.cleanarchitectureblazor.com/features/quoteattachment
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.QuoteAttachments.DTOs;
using CleanArchitecture.Blazor.Application.Features.QuoteAttachments.Caching;

namespace CleanArchitecture.Blazor.Application.Features.QuoteAttachments.Commands.Import;

    public class ImportQuoteAttachmentsCommand: ICacheInvalidatorRequest<Result<int>>
    {
        public string FileName { get; set; }
        public byte[] Data { get; set; }
        public string CacheKey => QuoteAttachmentCacheKey.GetAllCacheKey;
        public IEnumerable<string>? Tags => QuoteAttachmentCacheKey.Tags;
        public ImportQuoteAttachmentsCommand(string fileName,byte[] data)
        {
           FileName = fileName;
           Data = data;
        }
    }
    public record class CreateQuoteAttachmentsTemplateCommand : IRequest<Result<byte[]>>
    {
 
    }

    public class ImportQuoteAttachmentsCommandHandler : 
                 IRequestHandler<CreateQuoteAttachmentsTemplateCommand, Result<byte[]>>,
                 IRequestHandler<ImportQuoteAttachmentsCommand, Result<int>>
    {
        private readonly IApplicationDbContext _context;
        private readonly IStringLocalizer<ImportQuoteAttachmentsCommandHandler> _localizer;
        private readonly IExcelService _excelService;
        private readonly QuoteAttachmentDto _dto = new();
        private readonly IMapper _mapper;
        public ImportQuoteAttachmentsCommandHandler(
            IApplicationDbContext context,
            IMapper mapper,
            IExcelService excelService,
            IStringLocalizer<ImportQuoteAttachmentsCommandHandler> localizer)
        {
            _context = context;
            _localizer = localizer;
            _excelService = excelService;
            _mapper = mapper;
        }
        #nullable disable warnings
        public async Task<Result<int>> Handle(ImportQuoteAttachmentsCommand request, CancellationToken cancellationToken)
        {

           var result = await _excelService.ImportAsync(request.Data, mappers: new Dictionary<string, Func<DataRow, QuoteAttachmentDto, object?>>
            {
                                { _localizer[_dto.GetMemberDescription(x=>x.QuoteId)], (row, item) => item.QuoteId =Convert.ToInt32(row[_localizer[_dto.GetMemberDescription(x=>x.QuoteId)]]) }, 
                { _localizer[_dto.GetMemberDescription(x=>x.FileName)], (row, item) => item.FileName = row[_localizer[_dto.GetMemberDescription(x=>x.FileName)]].ToString() }, 
                { _localizer[_dto.GetMemberDescription(x=>x.FilePath)], (row, item) => item.FilePath = row[_localizer[_dto.GetMemberDescription(x=>x.FilePath)]].ToString() }, 
                { _localizer[_dto.GetMemberDescription(x=>x.UploadedAtUtc)], (row, item) => item.UploadedAtUtc =DateTime.Parse(row[_localizer[_dto.GetMemberDescription(x=>x.UploadedAtUtc)]].ToString()) }, 

            }, _localizer[_dto.GetClassDescription()]);
            if (result.Succeeded && result.Data is not null)
            {
                foreach (var dto in result.Data)
                {
                    var exists = await _context.QuoteAttachments.AnyAsync(x => x.Name == dto.Name, cancellationToken);
                    if (!exists)
                    {
                        var item = _mapper.Map<QuoteAttachment>(dto);
                        // add create domain events if this entity implement the IHasDomainEvent interface
				        // item.AddDomainEvent(new QuoteAttachmentCreatedEvent(item));
                        await _context.QuoteAttachments.AddAsync(item, cancellationToken);
                    }
                 }
                 await _context.SaveChangesAsync(cancellationToken);
                 return await Result<int>.SuccessAsync(result.Data.Count());
           }
           else
           {
               return await Result<int>.FailureAsync(result.Errors);
           }
        }
        public async Task<Result<byte[]>> Handle(CreateQuoteAttachmentsTemplateCommand request, CancellationToken cancellationToken)
        {
            // TODO: Implement ImportQuoteAttachmentsCommandHandler method 
            var fields = new string[] {
                   // TODO: Define the fields that should be generate in the template, for example:
                   _localizer[_dto.GetMemberDescription(x=>x.QuoteId)], 
_localizer[_dto.GetMemberDescription(x=>x.FileName)], 
_localizer[_dto.GetMemberDescription(x=>x.FilePath)], 
_localizer[_dto.GetMemberDescription(x=>x.UploadedAtUtc)], 

                };
            var result = await _excelService.CreateTemplateAsync(fields, _localizer[_dto.GetClassDescription()]);
            return await Result<byte[]>.SuccessAsync(result);
        }
    }

