//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Validator for ImportQuoteAttachmentsCommand: ensures the Data property is non-null and non-empty for quoteattachment import.
// Docs: https://docs.cleanarchitectureblazor.com/features/quoteattachment
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.QuoteAttachments.Commands.Import;

public class ImportQuoteAttachmentsCommandValidator : AbstractValidator<ImportQuoteAttachmentsCommand>
{
        public ImportQuoteAttachmentsCommandValidator()
        {
           
           RuleFor(v => v.Data)
                .NotNull()
                .NotEmpty();

        }
}

