//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-09-24
//     Last Modified: 2025-09-24
//     Description: 
//       Defines a query for retrieving vendors with pagination and filtering 
//       options. The result is cached to enhance performance for repeated queries.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Vendors.DTOs;
using CleanArchitecture.Blazor.Application.Features.Vendors.Caching;
using CleanArchitecture.Blazor.Application.Features.Vendors.Specifications;

namespace CleanArchitecture.Blazor.Application.Features.Vendors.Queries.Pagination;

public class VendorsWithPaginationQuery : VendorAdvancedFilter, ICacheableRequest<PaginatedData<VendorDto>>
{
    public override string ToString()
    {
        return $"Listview:{ListView}:{CurrentUser?.UserId}, Search:{Keyword}, {OrderBy}, {SortDirection}, {PageNumber}, {PageSize}";
    }
    public string CacheKey => VendorCacheKey.GetPaginationCacheKey($"{this}");
    public IEnumerable<string>? Tags => VendorCacheKey.Tags;
    public VendorAdvancedSpecification Specification => new VendorAdvancedSpecification(this);
}
    
public class VendorsWithPaginationQueryHandler :
         IRequestHandler<VendorsWithPaginationQuery, PaginatedData<VendorDto>>
{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    private readonly IMapper _mapper;
        public VendorsWithPaginationQueryHandler(
            IMapper mapper,
            IApplicationDbContextFactory dbContextFactory)
        {
            _mapper = mapper;
            _dbContextFactory = dbContextFactory;
        }

        public async Task<PaginatedData<VendorDto>> Handle(VendorsWithPaginationQuery request, CancellationToken cancellationToken)
        {

            try
            {
                await using var _context = await _dbContextFactory.CreateAsync(cancellationToken);
                var data = await _context.Vendors.OrderBy($"{request.OrderBy} {request.SortDirection}")
                                                       .ProjectToPaginatedDataAsync<Vendor, VendorDto>(request.Specification,
                                                        request.PageNumber,
                                                        request.PageSize,
                                                        _mapper.ConfigurationProvider,
                                                        cancellationToken);
                return data;
            }
            catch (Exception ex)
            {
               var msg = ex.Message;
            throw;
            }
           
        }
}