//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under one or more agreements.
//     The .NET Foundation licenses this file to you under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-03-21
//     Last Modified: 2025-03-21
//     Description: 
//       This file defines the validation rules for the UpdateSubCategoryCommand within 
//       the CleanArchitecture.Blazor application. It ensures that the command has 
//       all required fields properly populated and validates constraints such as 
//       maximum length and non-null requirements before proceeding with updating 
//       a subcategory.
//     
//     Documentation:
//       https://docs.cleanarchitectureblazor.com/features/subcategory
// </auto-generated>
//------------------------------------------------------------------------------

// Usage:
// The `UpdateSubCategoryCommandValidator` is used to validate that an `UpdateSubCategoryCommand` 
// contains valid and complete data before processing the update. It enforces rules such as 
// ensuring that the `Id` is provided, the `Name` is not empty, and certain properties 
// (e.g., ...) do not exceed their maximum 
// allowed length.

namespace CleanArchitecture.Blazor.Application.Features.SubCategories.Commands.Update;

public class UpdateSubCategoryCommandValidator : AbstractValidator<UpdateSubCategoryCommand>
{
        public UpdateSubCategoryCommandValidator()
        {
           RuleFor(v => v.Id).NotNull();
               RuleFor(v => v.Name).MaximumLength(50).NotEmpty(); 

          
        }
    
}

