//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-09-24
//     Last Modified: 2025-09-24
//     Description: 
//       Defines a query for retrieving equipmentitems with pagination and filtering 
//       options. The result is cached to enhance performance for repeated queries.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.EquipmentItems.DTOs;
using CleanArchitecture.Blazor.Application.Features.EquipmentItems.Caching;
using CleanArchitecture.Blazor.Application.Features.EquipmentItems.Specifications;

namespace CleanArchitecture.Blazor.Application.Features.EquipmentItems.Queries.Pagination;

public class EquipmentItemsWithPaginationQuery : EquipmentItemAdvancedFilter, ICacheableRequest<PaginatedData<EquipmentItemDto>>
{
    public override string ToString()
    {
        return $"Listview:{ListView}:{CurrentUser?.UserId}, Search:{Keyword}, {OrderBy}, {SortDirection}, {PageNumber}, {PageSize}";
    }
    public string CacheKey => EquipmentItemCacheKey.GetPaginationCacheKey($"{this}");
    public IEnumerable<string>? Tags => EquipmentItemCacheKey.Tags;
    public EquipmentItemAdvancedSpecification Specification => new EquipmentItemAdvancedSpecification(this);
}
    
public class EquipmentItemsWithPaginationQueryHandler :
         IRequestHandler<EquipmentItemsWithPaginationQuery, PaginatedData<EquipmentItemDto>>
{
        private readonly IApplicationDbContextFactory _dbContextFactory;
        private readonly IMapper _mapper;
        public EquipmentItemsWithPaginationQueryHandler(
            IMapper mapper,
            IApplicationDbContextFactory dbContextFactory)
        {
            _mapper = mapper;
            _dbContextFactory = dbContextFactory;
    }

        public async Task<PaginatedData<EquipmentItemDto>> Handle(EquipmentItemsWithPaginationQuery request, CancellationToken cancellationToken)
        {
        await using var _context = await _dbContextFactory.CreateAsync(cancellationToken);
        var data = await _context.EquipmentItems.OrderBy($"{request.OrderBy} {request.SortDirection}")
                                                   .ProjectToPaginatedDataAsync<EquipmentItem, EquipmentItemDto>(request.Specification,
                                                    request.PageNumber,
                                                    request.PageSize,
                                                    _mapper.ConfigurationProvider,
                                                    cancellationToken);
            return data;
        }
}