//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Command for adding/editing a servicevariant entity with validation, mapping,
// domain events, and cache invalidation.
// Documentation: https://docs.cleanarchitectureblazor.com/features/servicevariant
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings


using CleanArchitecture.Blazor.Application.Features.ServiceVariants.Caching;
using CleanArchitecture.Blazor.Application.Features.ServiceVariants.DTOs;
namespace CleanArchitecture.Blazor.Application.Features.ServiceVariants.Commands.AddEdit;

public class AddEditServiceVariantCommand: ICacheInvalidatorRequest<Result<int>>
{
      [Description("Id")]
      public int Id { get; set; }
          [Description("Service id")]
    public int ServiceId {get;set;} 
    [Description("Service")]
    public ServiceDto? Service {get;set;} 
    [Description("Name")]
    public string Name {get;set;} 
    [Description("Unit")]
    public string? Unit {get;set;} 
    [Description("Complexity level")]
    public int? ComplexityLevel {get;set;} 
    [Description("Base price")]
    public decimal? BasePrice {get;set;} 


      public string CacheKey => ServiceVariantCacheKey.GetAllCacheKey;
      public IEnumerable<string>? Tags => ServiceVariantCacheKey.Tags;
    private class Mapping : Profile
    {
        public Mapping()
        {
            CreateMap<ServiceVariantDto, AddEditServiceVariantCommand>(MemberList.None);
            CreateMap<AddEditServiceVariantCommand, ServiceVariant>(MemberList.None);
        }
    }
}

public class AddEditServiceVariantCommandHandler : IRequestHandler<AddEditServiceVariantCommand, Result<int>>
{
    private readonly IMapper _mapper;
    private readonly IApplicationDbContextFactory _dbContextFactory;
    public AddEditServiceVariantCommandHandler(
        IMapper mapper,
        IApplicationDbContextFactory dbContextFactory)
    {
        _mapper = mapper;
        _dbContextFactory = dbContextFactory;
    }
    public async Task<Result<int>> Handle(AddEditServiceVariantCommand request, CancellationToken cancellationToken)
    {
        if (request.Id > 0)
        {
            await using var _context = await _dbContextFactory.CreateAsync(cancellationToken);
            var item = await _context.ServiceVariants.FindAsync(request.Id, cancellationToken);
            if (item == null)
            {
                return await Result<int>.FailureAsync($"ServiceVariant with id: [{request.Id}] not found.");
            }
            item = _mapper.Map(request, item);
			// raise a update domain event
			item.AddDomainEvent(new ServiceVariantUpdatedEvent(item));
            await _context.SaveChangesAsync(cancellationToken);
            return await Result<int>.SuccessAsync(item.Id);
        }
        else
        {
            await using var _context = await _dbContextFactory.CreateAsync(cancellationToken);
            var item = _mapper.Map<ServiceVariant>(request);
            // raise a create domain event
			item.AddDomainEvent(new ServiceVariantCreatedEvent(item));
            _context.ServiceVariants.Add(item);
            await _context.SaveChangesAsync(cancellationToken);
            return await Result<int>.SuccessAsync(item.Id);
        }
       
    }
}

