//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Command and handler for deleting QuoteVersion entities.
// Implements cache invalidation and triggers domain events.
// Docs: https://docs.cleanarchitectureblazor.com/features/quoteversion
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.QuoteVersions.Caching;

namespace CleanArchitecture.Blazor.Application.Features.QuoteVersions.Commands.Delete;

public class DeleteQuoteVersionCommand:  ICacheInvalidatorRequest<Result>
{
  public int[] Id {  get; }
  public string CacheKey => QuoteVersionCacheKey.GetAllCacheKey;
  public IEnumerable<string>? Tags => QuoteVersionCacheKey.Tags;
  public DeleteQuoteVersionCommand(int[] id)
  {
    Id = id;
  }
}

public class DeleteQuoteVersionCommandHandler : 
             IRequestHandler<DeleteQuoteVersionCommand, Result>

{
    private readonly IApplicationDbContext _context;
    public DeleteQuoteVersionCommandHandler(
        IApplicationDbContext context)
    {
        _context = context;
    }
    public async Task<Result> Handle(DeleteQuoteVersionCommand request, CancellationToken cancellationToken)
    {
        var items = await _context.QuoteVersions.Where(x=>request.Id.Contains(x.Id)).ToListAsync(cancellationToken);
        foreach (var item in items)
        {
		    // raise a delete domain event
			item.AddDomainEvent(new QuoteVersionDeletedEvent(item));
            _context.QuoteVersions.Remove(item);
        }
        await _context.SaveChangesAsync(cancellationToken);
        return await Result.SuccessAsync();
    }

}

