//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Command and handler for creating a new Service.
// Uses caching invalidation and domain events for data consistency.
// Docs: https://docs.cleanarchitectureblazor.com/features/service
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Services.Caching;

namespace CleanArchitecture.Blazor.Application.Features.Services.Commands.Create;

public class CreateServiceCommand: ICacheInvalidatorRequest<Result<int>>
{
      [Description("Id")]
      public int Id { get; set; }
          [Description("Service category id")]
    public int ServiceCategoryId {get;set;} 
    [Description("Category")]
    public ServiceCategoryDto? Category {get;set;} 
    [Description("Name")]
    public string Name {get;set;} 
    [Description("Description")]
    public string? Description {get;set;} 
    [Description("Default pricing model")]
    public PricingModelType? DefaultPricingModel {get;set;} 

      public string CacheKey => ServiceCacheKey.GetAllCacheKey;
      public IEnumerable<string>? Tags => ServiceCacheKey.Tags;
      private class Mapping : Profile
    {
        public Mapping()
        {
            CreateMap<CreateServiceCommand, Service>(MemberList.None);
        }
    }
}
    
    public class CreateServiceCommandHandler : IRequestHandler<CreateServiceCommand, Result<int>>
    {
        private readonly IMapper _mapper;
        private readonly IApplicationDbContextFactory _dbContextFactory;
        public CreateServiceCommandHandler(
            IMapper mapper,
            IApplicationDbContextFactory dbContextFactory)
        {
            _mapper = mapper;
            _dbContextFactory = dbContextFactory;
        }
        public async Task<Result<int>> Handle(CreateServiceCommand request, CancellationToken cancellationToken)
        {
        await using var _context = await _dbContextFactory.CreateAsync(cancellationToken);
        var item = _mapper.Map<Service>(request);
           // raise a create domain event
	       item.AddDomainEvent(new ServiceCreatedEvent(item));
           _context.Services.Add(item);
           await _context.SaveChangesAsync(cancellationToken);
           return  await Result<int>.SuccessAsync(item.Id);
        }
    }

