//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Validator for CreateServiceCommand: enforces max lengths and required fields for Service entities.
// Docs: https://docs.cleanarchitectureblazor.com/features/service
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.Services.Commands.Create;

public class CreateServiceCommandValidator : AbstractValidator<CreateServiceCommand>
{
        public CreateServiceCommandValidator()
        {
                RuleFor(v => v.ServiceCategoryId).NotNull(); 
    RuleFor(v => v.Name).MaximumLength(50).NotEmpty(); 
    RuleFor(v => v.Description).MaximumLength(255); 
    RuleFor(v => v.DefaultPricingModel).NotNull(); 

        }
       
}

