//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Command and handler for creating a new ProjectTask.
// Uses caching invalidation and domain events for data consistency.
// Docs: https://docs.cleanarchitectureblazor.com/features/projecttask
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.ProjectTasks.Caching;

namespace CleanArchitecture.Blazor.Application.Features.ProjectTasks.Commands.Create;

public class CreateProjectTaskCommand: ICacheInvalidatorRequest<Result<int>>
{
      [Description("Id")]
      public int Id { get; set; }
          [Description("Project id")]
    public int ProjectId {get;set;} 
    [Description("Project")]
    public ProjectDto? Project {get;set;} 
    [Description("Assigned to id")]
    public int? AssignedToId {get;set;} 
    [Description("Assigned to")]
    public EmployeeDto? AssignedTo {get;set;} 
    [Description("Title")]
    public string? Title {get;set;} 
    [Description("Description")]
    public string? Description {get;set;} 
    [Description("Deadline")]
    public DateTime? Deadline {get;set;} 
    [Description("Status")]
    public CleanArchitecture.Blazor.Domain.Entities.TaskStatus? Status {get;set;} 
    [Description("Priority")]
    public TaskPriority? Priority {get;set;} 

      public string CacheKey => ProjectTaskCacheKey.GetAllCacheKey;
      public IEnumerable<string>? Tags => ProjectTaskCacheKey.Tags;
      private class Mapping : Profile
    {
        public Mapping()
        {
            CreateMap<CreateProjectTaskCommand, ProjectTask>(MemberList.None);
        }
    }
}
    
    public class CreateProjectTaskCommandHandler : IRequestHandler<CreateProjectTaskCommand, Result<int>>
    {
        private readonly IMapper _mapper;
        private readonly IApplicationDbContextFactory _dbContextFactory;;
        public CreateProjectTaskCommandHandler(
            IMapper mapper,
            IApplicationDbContext context)
        {
            _mapper = mapper;
            _context = context;
        }
        public async Task<Result<int>> Handle(CreateProjectTaskCommand request, CancellationToken cancellationToken)
        {
           var item = _mapper.Map<ProjectTask>(request);
           // raise a create domain event
	       item.AddDomainEvent(new ProjectTaskCreatedEvent(item));
           _context.ProjectTasks.Add(item);
           await _context.SaveChangesAsync(cancellationToken);
           return  await Result<int>.SuccessAsync(item.Id);
        }
    }

