//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-09-24
//     Last Modified: 2025-09-24
//     Description: 
//       Defines a query to retrieve a servicevariant by its ID. The result is cached 
//       to optimize performance for repeated retrievals of the same servicevariant.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.ServiceVariants.DTOs;
using CleanArchitecture.Blazor.Application.Features.ServiceVariants.Caching;
using CleanArchitecture.Blazor.Application.Features.ServiceVariants.Specifications;

namespace CleanArchitecture.Blazor.Application.Features.ServiceVariants.Queries.GetById;

public class GetServiceVariantByIdQuery : ICacheableRequest<Result<ServiceVariantDto>>
{
   public required int Id { get; set; }
   public string CacheKey => ServiceVariantCacheKey.GetByIdCacheKey($"{Id}");
   public IEnumerable<string>? Tags => ServiceVariantCacheKey.Tags;
}

public class GetServiceVariantByIdQueryHandler :
     IRequestHandler<GetServiceVariantByIdQuery, Result<ServiceVariantDto>>
{
    private readonly IApplicationDbContext _context;
    private readonly IMapper _mapper;
    public GetServiceVariantByIdQueryHandler(
        IMapper mapper,
        IApplicationDbContext context)
    {
        _mapper = mapper;
        _context = context;
    }

    public async Task<Result<ServiceVariantDto>> Handle(GetServiceVariantByIdQuery request, CancellationToken cancellationToken)
    {
        var data = await _context.ServiceVariants.ApplySpecification(new ServiceVariantByIdSpecification(request.Id))
                                                .ProjectTo<ServiceVariantDto>(_mapper.ConfigurationProvider)
                                                .FirstAsync(cancellationToken) ?? throw new NotFoundException($"ServiceVariant with id: [{request.Id}] not found.");
        return await Result<ServiceVariantDto>.SuccessAsync(data);
    }
}
