//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-09-24
//     Last Modified: 2025-09-24
//     Description: 
//       Defines a query to retrieve all servicevariants from the database. The result 
//       is cached to improve performance and reduce database load for repeated 
//       queries.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.ServiceVariants.DTOs;
using CleanArchitecture.Blazor.Application.Features.ServiceVariants.Caching;

namespace CleanArchitecture.Blazor.Application.Features.ServiceVariants.Queries.GetAll;

public class GetAllServiceVariantsQuery : ICacheableRequest<IEnumerable<ServiceVariantDto>>
{
   public string CacheKey => ServiceVariantCacheKey.GetAllCacheKey;
   public IEnumerable<string>? Tags => ServiceVariantCacheKey.Tags;
}

public class GetAllServiceVariantsQueryHandler :
     IRequestHandler<GetAllServiceVariantsQuery, IEnumerable<ServiceVariantDto>>
{
    private readonly IApplicationDbContext _context;
    private readonly IMapper _mapper;
    public GetAllServiceVariantsQueryHandler(
        IMapper mapper,
        IApplicationDbContext context)
    {
        _mapper = mapper;
        _context = context;
    }

    public async Task<IEnumerable<ServiceVariantDto>> Handle(GetAllServiceVariantsQuery request, CancellationToken cancellationToken)
    {
        var data = await _context.ServiceVariants.ProjectTo<ServiceVariantDto>(_mapper.ConfigurationProvider)
                                                .AsNoTracking()
                                                .ToListAsync(cancellationToken);
        return data;
    }
}


