//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-09-24
//     Last Modified: 2025-09-24
//     Description: 
//       Defines a query for retrieving quoteversions with pagination and filtering 
//       options. The result is cached to enhance performance for repeated queries.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.QuoteVersions.DTOs;
using CleanArchitecture.Blazor.Application.Features.QuoteVersions.Caching;
using CleanArchitecture.Blazor.Application.Features.QuoteVersions.Specifications;

namespace CleanArchitecture.Blazor.Application.Features.QuoteVersions.Queries.Pagination;

public class QuoteVersionsWithPaginationQuery : QuoteVersionAdvancedFilter, ICacheableRequest<PaginatedData<QuoteVersionDto>>
{
    public override string ToString()
    {
        return $"Listview:{ListView}:{CurrentUser?.UserId}, Search:{Keyword}, {OrderBy}, {SortDirection}, {PageNumber}, {PageSize}";
    }
    public string CacheKey => QuoteVersionCacheKey.GetPaginationCacheKey($"{this}");
    public IEnumerable<string>? Tags => QuoteVersionCacheKey.Tags;
    public QuoteVersionAdvancedSpecification Specification => new QuoteVersionAdvancedSpecification(this);
}
    
public class QuoteVersionsWithPaginationQueryHandler :
         IRequestHandler<QuoteVersionsWithPaginationQuery, PaginatedData<QuoteVersionDto>>
{
        private readonly IApplicationDbContext _context;
        private readonly IMapper _mapper;
        public QuoteVersionsWithPaginationQueryHandler(
            IMapper mapper,
            IApplicationDbContext context)
        {
            _mapper = mapper;
            _context = context;
        }

        public async Task<PaginatedData<QuoteVersionDto>> Handle(QuoteVersionsWithPaginationQuery request, CancellationToken cancellationToken)
        {
           var data = await _context.QuoteVersions.OrderBy($"{request.OrderBy} {request.SortDirection}")
                                                   .ProjectToPaginatedDataAsync<QuoteVersion, QuoteVersionDto>(request.Specification,
                                                    request.PageNumber,
                                                    request.PageSize,
                                                    _mapper.ConfigurationProvider,
                                                    cancellationToken);
            return data;
        }
}