//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-09-24
//     Last Modified: 2025-09-24
//     Description: 
//       Defines a query to retrieve all quoteversions from the database. The result 
//       is cached to improve performance and reduce database load for repeated 
//       queries.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.QuoteVersions.DTOs;
using CleanArchitecture.Blazor.Application.Features.QuoteVersions.Caching;

namespace CleanArchitecture.Blazor.Application.Features.QuoteVersions.Queries.GetAll;

public class GetAllQuoteVersionsQuery : ICacheableRequest<IEnumerable<QuoteVersionDto>>
{
   public string CacheKey => QuoteVersionCacheKey.GetAllCacheKey;
   public IEnumerable<string>? Tags => QuoteVersionCacheKey.Tags;
}

public class GetAllQuoteVersionsQueryHandler :
     IRequestHandler<GetAllQuoteVersionsQuery, IEnumerable<QuoteVersionDto>>
{
    private readonly IApplicationDbContext _context;
    private readonly IMapper _mapper;
    public GetAllQuoteVersionsQueryHandler(
        IMapper mapper,
        IApplicationDbContext context)
    {
        _mapper = mapper;
        _context = context;
    }

    public async Task<IEnumerable<QuoteVersionDto>> Handle(GetAllQuoteVersionsQuery request, CancellationToken cancellationToken)
    {
        var data = await _context.QuoteVersions.ProjectTo<QuoteVersionDto>(_mapper.ConfigurationProvider)
                                                .AsNoTracking()
                                                .ToListAsync(cancellationToken);
        return data;
    }
}


