//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Validator for AddEditServiceCategoryCommand: enforces field length and required property rules for ServiceCategory entities.
// Docs: https://docs.cleanarchitectureblazor.com/features/servicecategory
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings


namespace CleanArchitecture.Blazor.Application.Features.ServiceCategories.Commands.AddEdit;

public class AddEditServiceCategoryCommandValidator : AbstractValidator<AddEditServiceCategoryCommand>
{
    public AddEditServiceCategoryCommandValidator()
    {
                RuleFor(v => v.Name).MaximumLength(50).NotEmpty(); 
    RuleFor(v => v.Description).MaximumLength(255); 

     }

}

