//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-09-24
//     Last Modified: 2025-09-24
//     Description: 
//       Defines a query to retrieve all servicecategorys from the database. The result 
//       is cached to improve performance and reduce database load for repeated 
//       queries.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.ServiceCategories.DTOs;
using CleanArchitecture.Blazor.Application.Features.ServiceCategories.Caching;

namespace CleanArchitecture.Blazor.Application.Features.ServiceCategories.Queries.GetAll;

public class GetAllServiceCategoriesQuery : ICacheableRequest<IEnumerable<ServiceCategoryDto>>
{
   public string CacheKey => ServiceCategoryCacheKey.GetAllCacheKey;
   public IEnumerable<string>? Tags => ServiceCategoryCacheKey.Tags;
}

public class GetAllServiceCategoriesQueryHandler :
     IRequestHandler<GetAllServiceCategoriesQuery, IEnumerable<ServiceCategoryDto>>
{
    private readonly IApplicationDbContext _context;
    private readonly IMapper _mapper;
    public GetAllServiceCategoriesQueryHandler(
        IMapper mapper,
        IApplicationDbContext context)
    {
        _mapper = mapper;
        _context = context;
    }

    public async Task<IEnumerable<ServiceCategoryDto>> Handle(GetAllServiceCategoriesQuery request, CancellationToken cancellationToken)
    {
        var data = await _context.ServiceCategories.ProjectTo<ServiceCategoryDto>(_mapper.ConfigurationProvider)
                                                .AsNoTracking()
                                                .ToListAsync(cancellationToken);
        return data;
    }
}


