////------------------------------------------------------------------------------
//// <auto-generated>
//// CleanArchitecture.Blazor - MIT Licensed.
//// Author: neozhu
//// Created/Modified: 2025-09-24
//// Defines permission constants for purchaseorder operations (view, create, edit, delete, etc.).
//// </auto-generated>
////------------------------------------------------------------------------------


//using System.ComponentModel;

//namespace CleanArchitecture.Blazor.Infrastructure.PermissionSet;

//public static partial class Permissions
//{
//    [DisplayName("PurchaseOrder Permissions")]
//    [Description("Set permissions for purchaseorder operations.")]
//    public static class PurchaseOrders
//    {
//        [Description("Allows viewing purchaseorder details.")]
//        public const string View = "Permissions.PurchaseOrders.View";
//        [Description("Allows creating purchaseorder details.")]
//        public const string Create = "Permissions.PurchaseOrders.Create";
//        [Description("Allows editing purchaseorder details.")]
//        public const string Edit = "Permissions.PurchaseOrders.Edit";
//        [Description("Allows deleting purchaseorder details.")]
//        public const string Delete = "Permissions.PurchaseOrders.Delete";
//        [Description("Allows printing purchaseorder details.")]
//        public const string Print = "Permissions.PurchaseOrders.Print";
//        [Description("Allows searching purchaseorder details.")]
//        public const string Search = "Permissions.PurchaseOrders.Search";
//        [Description("Allows exporting purchaseorder details.")]
//        public const string Export = "Permissions.PurchaseOrders.Export";
//        [Description("Allows importing purchaseorder details.")]
//        public const string Import = "Permissions.PurchaseOrders.Import";
//    }
//}

//public class PurchaseOrdersAccessRights
//{
//    public bool View { get; set; }
//    public bool Create { get; set; }
//    public bool Edit { get; set; }
//    public bool Delete { get; set; }
//    public bool Print { get; set; }
//    public bool Search { get; set; }
//    public bool Export { get; set; }
//    public bool Import { get; set; }
//}
