//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-03-21
//     Last Modified: 2025-03-21
//     Description: 
//       Defines permission constants for subcategory-related operations, such as 
//       viewing, creating, editing, deleting, and more. These permissions are 
//       used to manage access control within the application.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace CleanArchitecture.Blazor.Infrastructure.PermissionSet;

public static partial class Permissions
{
    [DisplayName("SubCategory Permissions")]
    [Description("Set permissions for subcategory operations.")]
    public static class SubCategories
    {
        [Description("Allows viewing subcategory details.")]
        public const string View = "Permissions.SubCategories.View";
        [Description("Allows creating subcategory details.")]
        public const string Create = "Permissions.SubCategories.Create";
        [Description("Allows editing subcategory details.")]
        public const string Edit = "Permissions.SubCategories.Edit";
        [Description("Allows deleting subcategory details.")]
        public const string Delete = "Permissions.SubCategories.Delete";
        [Description("Allows printing subcategory details.")]
        public const string Print = "Permissions.SubCategories.Print";
        [Description("Allows searching subcategory details.")]
        public const string Search = "Permissions.SubCategories.Search";
        [Description("Allows exporting subcategory details.")]
        public const string Export = "Permissions.SubCategories.Export";
        [Description("Allows importing subcategory details.")]
        public const string Import = "Permissions.SubCategories.Import";
    }
}

