//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Validator for DeleteCostItemCommand: ensures the ID list for costitem is not null and contains only positive IDs.
// Docs: https://docs.cleanarchitectureblazor.com/features/costitem
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.CostItems.Commands.Delete;

public class DeleteCostItemCommandValidator : AbstractValidator<DeleteCostItemCommand>
{
        public DeleteCostItemCommandValidator()
        {
          
            RuleFor(v => v.Id).NotNull().ForEach(v=>v.GreaterThan(0));
          
        }
}
    

