//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Command and handler for deleting CostItem entities.
// Implements cache invalidation and triggers domain events.
// Docs: https://docs.cleanarchitectureblazor.com/features/costitem
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.CostItems.Caching;

namespace CleanArchitecture.Blazor.Application.Features.CostItems.Commands.Delete;

public class DeleteCostItemCommand:  ICacheInvalidatorRequest<Result>
{
  public int[] Id {  get; }
  public string CacheKey => CostItemCacheKey.GetAllCacheKey;
  public IEnumerable<string>? Tags => CostItemCacheKey.Tags;
  public DeleteCostItemCommand(int[] id)
  {
    Id = id;
  }
}

public class DeleteCostItemCommandHandler : 
             IRequestHandler<DeleteCostItemCommand, Result>

{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    public DeleteCostItemCommandHandler(
        IApplicationDbContextFactory dbContextFactory)
    {
        _dbContextFactory = dbContextFactory;
    }
    public async Task<Result> Handle(DeleteCostItemCommand request, CancellationToken cancellationToken)
    {
        await using var _context = await _dbContextFactory.CreateAsync(cancellationToken);
        var items = await _context.CostItems.Where(x=>request.Id.Contains(x.Id)).ToListAsync(cancellationToken);
        foreach (var item in items)
        {
		    // raise a delete domain event
			item.AddDomainEvent(new CostItemDeletedEvent(item));
            _context.CostItems.Remove(item);
        }
        await _context.SaveChangesAsync(cancellationToken);
        return await Result.SuccessAsync();
    }

}

