////------------------------------------------------------------------------------
//// <auto-generated>
//// CleanArchitecture.Blazor - MIT Licensed.
//// Author: neozhu
//// Created/Modified: 2025-09-24
//// Validator for ImportDocumentsCommand: ensures the Data property is non-null and non-empty for document import.
//// Docs: https://docs.cleanarchitectureblazor.com/features/document
//// </auto-generated>
////------------------------------------------------------------------------------
//#nullable enable
//#nullable disable warnings

//namespace CleanArchitecture.Blazor.Application.Features.Documents.Commands.Import;

//public class ImportDocumentsCommandValidator : AbstractValidator<ImportDocumentsCommand>
//{
//        public ImportDocumentsCommandValidator()
//        {
           
//           RuleFor(v => v.Data)
//                .NotNull()
//                .NotEmpty();

//        }
//}

