//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Command for adding/editing a employee entity with validation, mapping,
// domain events, and cache invalidation.
// Documentation: https://docs.cleanarchitectureblazor.com/features/employee
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings


using CleanArchitecture.Blazor.Application.Features.Employees.Caching;
using CleanArchitecture.Blazor.Application.Features.Employees.DTOs;
namespace CleanArchitecture.Blazor.Application.Features.Employees.Commands.AddEdit;

public class AddEditEmployeeCommand: ICacheInvalidatorRequest<Result<int>>
{
      [Description("Id")]
      public int Id { get; set; }
          [Description("First name")]
    public string? FirstName {get;set;} 
    [Description("Last name")]
    public string? LastName {get;set;} 
    [Description("Email")]
    public string? Email {get;set;} 
    [Description("Phone")]
    public string? Phone {get;set;} 
    [Description("Position")]
    public string? Position {get;set;} 


      public string CacheKey => EmployeeCacheKey.GetAllCacheKey;
      public IEnumerable<string>? Tags => EmployeeCacheKey.Tags;
    private class Mapping : Profile
    {
        public Mapping()
        {
            CreateMap<EmployeeDto, AddEditEmployeeCommand>(MemberList.None);
            CreateMap<AddEditEmployeeCommand, Employee>(MemberList.None);
        }
    }
}

public class AddEditEmployeeCommandHandler : IRequestHandler<AddEditEmployeeCommand, Result<int>>
{
    private readonly IMapper _mapper;
    private readonly IApplicationDbContextFactory _dbContextFactory;
    public AddEditEmployeeCommandHandler(
        IMapper mapper,
        IApplicationDbContextFactory dbContextFactory)
    {
        _mapper = mapper;
        _dbContextFactory = dbContextFactory;
    }
    public async Task<Result<int>> Handle(AddEditEmployeeCommand request, CancellationToken cancellationToken)
    {
        if (request.Id > 0)
        {
            await using var _context = await _dbContextFactory.CreateAsync(cancellationToken);
            var item = await _context.Employees.FindAsync(request.Id, cancellationToken);
            if (item == null)
            {
                return await Result<int>.FailureAsync($"Employee with id: [{request.Id}] not found.");
            }
            item = _mapper.Map(request, item);
			// raise a update domain event
			item.AddDomainEvent(new EmployeeUpdatedEvent(item));
            await _context.SaveChangesAsync(cancellationToken);
            return await Result<int>.SuccessAsync(item.Id);
        }
        else
        {
            await using var _context = await _dbContextFactory.CreateAsync(cancellationToken);
            var item = _mapper.Map<Employee>(request);
            // raise a create domain event
			item.AddDomainEvent(new EmployeeCreatedEvent(item));
            _context.Employees.Add(item);
            await _context.SaveChangesAsync(cancellationToken);
            return await Result<int>.SuccessAsync(item.Id);
        }
       
    }
}

