//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Validator for AddEditEmployeeCommand: enforces field length and required property rules for Employee entities.
// Docs: https://docs.cleanarchitectureblazor.com/features/employee
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings


namespace CleanArchitecture.Blazor.Application.Features.Employees.Commands.AddEdit;

public class AddEditEmployeeCommandValidator : AbstractValidator<AddEditEmployeeCommand>
{
    public AddEditEmployeeCommandValidator()
    {
                RuleFor(v => v.FirstName).MaximumLength(255); 
    RuleFor(v => v.LastName).MaximumLength(255); 
    RuleFor(v => v.Email).MaximumLength(255); 
    RuleFor(v => v.Phone).MaximumLength(255); 
    RuleFor(v => v.Position).MaximumLength(255); 

     }

}

