//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under one or more agreements.
//     The .NET Foundation licenses this file to you under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-03-27
//     Last Modified: 2025-03-27
//     Description: 
//       This file defines the validation rules for the AddEditPurchaseItemCommand 
//       used to add or edit PurchaseItem entities within the CleanArchitecture.Blazor 
//       application. It enforces maximum field lengths and required properties 
//       to maintain data integrity and validation standards.
//     
//     Documentation:
//       https://docs.cleanarchitectureblazor.com/features/purchaseitem
// </auto-generated>
//------------------------------------------------------------------------------

// Usage:
// This validator enforces constraints on the AddEditPurchaseItemCommand, such as
// maximum field length for ...

namespace CleanArchitecture.Blazor.Application.Features.PurchaseItems.Commands.AddEdit;

public class AddEditPurchaseItemCommandValidator : AbstractValidator<AddEditPurchaseItemCommand>
{
    public AddEditPurchaseItemCommandValidator()
    {
                RuleFor(v => v.InvoiceId).NotNull(); 
    RuleFor(v => v.ItemCode).MaximumLength(255); 
    RuleFor(v => v.ItemDescription).MaximumLength(255); 
    RuleFor(v => v.Quantity).NotNull(); 
    RuleFor(v => v.Unit).MaximumLength(255); 
    RuleFor(v => v.Color).MaximumLength(255); 
    RuleFor(v => v.UnitPrice).NotNull(); 
    RuleFor(v => v.VATPercentage).NotNull(); 
    RuleFor(v => v.VATAmount).NotNull(); 
    RuleFor(v => v.TotalAmount).NotNull(); 

     }

}

