//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Validator for UpdateVendorCommand: ensures required fields (e.g., Id, non-empty Name, max length for properties) are valid for updating a vendor.
// Docs: https://docs.cleanarchitectureblazor.com/features/vendor
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.Vendors.Commands.Update;

public class UpdateVendorCommandValidator : AbstractValidator<UpdateVendorCommand>
{
        public UpdateVendorCommandValidator()
        {
           RuleFor(v => v.Id).NotNull();
               RuleFor(v => v.CompanyId).NotNull(); 
    RuleFor(v => v.Terms).MaximumLength(255); 

          
        }
    
}

