//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-09-24
//     Last Modified: 2025-09-24
//     Description: 
//       Defines a query to export servicevariant data to an Excel file. This query 
//       applies advanced filtering options and generates an Excel file with 
//       the specified servicevariant details.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.ServiceVariants.DTOs;
using CleanArchitecture.Blazor.Application.Features.ServiceVariants.Caching;
using CleanArchitecture.Blazor.Application.Features.ServiceVariants.Specifications;

namespace CleanArchitecture.Blazor.Application.Features.ServiceVariants.Queries.Export;

public class ExportServiceVariantsQuery : ServiceVariantAdvancedFilter, ICacheableRequest<Result<byte[]>>
{
      public ServiceVariantAdvancedSpecification Specification => new ServiceVariantAdvancedSpecification(this);
      public IEnumerable<string>? Tags => ServiceVariantCacheKey.Tags;
    public override string ToString()
    {
        return $"Listview:{ListView}:{CurrentUser?.UserId}, Search:{Keyword}, {OrderBy}, {SortDirection}";
    }
    public string CacheKey => ServiceVariantCacheKey.GetExportCacheKey($"{this}");
}
    
public class ExportServiceVariantsQueryHandler :
         IRequestHandler<ExportServiceVariantsQuery, Result<byte[]>>
{
        private readonly IMapper _mapper;
        private readonly IApplicationDbContext _context;
        private readonly IExcelService _excelService;
        private readonly IStringLocalizer<ExportServiceVariantsQueryHandler> _localizer;
        private readonly ServiceVariantDto _dto = new();
        public ExportServiceVariantsQueryHandler(
            IMapper mapper,
            IApplicationDbContext context,
            IExcelService excelService,
            IStringLocalizer<ExportServiceVariantsQueryHandler> localizer
            )
        {
            _mapper = mapper;
            _context = context;
            _excelService = excelService;
            _localizer = localizer;
        }
        #nullable disable warnings
        public async Task<Result<byte[]>> Handle(ExportServiceVariantsQuery request, CancellationToken cancellationToken)
        {
            var data = await _context.ServiceVariants.ApplySpecification(request.Specification)
                       .OrderBy($"{request.OrderBy} {request.SortDirection}")
                       .ProjectTo<ServiceVariantDto>(_mapper.ConfigurationProvider)
                       .AsNoTracking()
                       .ToListAsync(cancellationToken);
            var result = await _excelService.ExportAsync(data,
                new Dictionary<string, Func<ServiceVariantDto, object?>>()
                {
                    // TODO: Define the fields that should be exported, for example:
                                     {_localizer[_dto.GetMemberDescription(x=>x.ServiceId)],item => item.ServiceId}, 
                 {_localizer[_dto.GetMemberDescription(x=>x.Name)],item => item.Name}, 
                 {_localizer[_dto.GetMemberDescription(x=>x.Unit)],item => item.Unit}, 
                 {_localizer[_dto.GetMemberDescription(x=>x.ComplexityLevel)],item => item.ComplexityLevel}, 
                 {_localizer[_dto.GetMemberDescription(x=>x.BasePrice)],item => item.BasePrice}, 

                }
                , _localizer[_dto.GetClassDescription()]);
            return await Result<byte[]>.SuccessAsync(result);
        }
}
