//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-09-24
//     Last Modified: 2025-09-24
//     Description: 
//       Defines a query for retrieving servicecategorys with pagination and filtering 
//       options. The result is cached to enhance performance for repeated queries.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.ServiceCategories.DTOs;
using CleanArchitecture.Blazor.Application.Features.ServiceCategories.Caching;
using CleanArchitecture.Blazor.Application.Features.ServiceCategories.Specifications;

namespace CleanArchitecture.Blazor.Application.Features.ServiceCategories.Queries.Pagination;

public class ServiceCategoriesWithPaginationQuery : ServiceCategoryAdvancedFilter, ICacheableRequest<PaginatedData<ServiceCategoryDto>>
{
    public override string ToString()
    {
        return $"Listview:{ListView}:{CurrentUser?.UserId}, Search:{Keyword}, {OrderBy}, {SortDirection}, {PageNumber}, {PageSize}";
    }
    public string CacheKey => ServiceCategoryCacheKey.GetPaginationCacheKey($"{this}");
    public IEnumerable<string>? Tags => ServiceCategoryCacheKey.Tags;
    public ServiceCategoryAdvancedSpecification Specification => new ServiceCategoryAdvancedSpecification(this);
}
    
public class ServiceCategoriesWithPaginationQueryHandler :
         IRequestHandler<ServiceCategoriesWithPaginationQuery, PaginatedData<ServiceCategoryDto>>
{
        private readonly IApplicationDbContextFactory _dbContextFactory;;
        private readonly IMapper _mapper;
        public ServiceCategoriesWithPaginationQueryHandler(
            IMapper mapper,
            IApplicationDbContext context)
        {
            _mapper = mapper;
            _context = context;
        }

        public async Task<PaginatedData<ServiceCategoryDto>> Handle(ServiceCategoriesWithPaginationQuery request, CancellationToken cancellationToken)
        {
           var data = await _context.ServiceCategories.OrderBy($"{request.OrderBy} {request.SortDirection}")
                                                   .ProjectToPaginatedDataAsync<ServiceCategory, ServiceCategoryDto>(request.Specification,
                                                    request.PageNumber,
                                                    request.PageSize,
                                                    _mapper.ConfigurationProvider,
                                                    cancellationToken);
            return data;
        }
}