//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Handles EquipmentItemCreatedEvent: triggered when a new equipmentitem is created.
// Extendable for additional actions (e.g., notifications, system updates).
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Application.Features.EquipmentItems.EventHandlers;

public class EquipmentItemCreatedEventHandler : INotificationHandler<EquipmentItemCreatedEvent>
{
        private readonly ILogger<EquipmentItemCreatedEventHandler> _logger;

        public EquipmentItemCreatedEventHandler(
            ILogger<EquipmentItemCreatedEventHandler> logger
            )
        {
            _logger = logger;
        }
        public Task Handle(EquipmentItemCreatedEvent notification, CancellationToken cancellationToken)
        {
            _logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
            return Task.CompletedTask;
        }
}
