//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Handles EquipmentItemUpdatedEvent: triggered when a equipmentitem is updated.
// Extendable for additional actions (e.g., notifications, system updates).
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Application.Features.EquipmentItems.EventHandlers;

    public class EquipmentItemUpdatedEventHandler : INotificationHandler<EquipmentItemUpdatedEvent>
    {
        private readonly ILogger<EquipmentItemUpdatedEventHandler> _logger;

        public EquipmentItemUpdatedEventHandler(
            ILogger<EquipmentItemUpdatedEventHandler> logger
            )
        {
            _logger = logger;
        }
        public Task Handle(EquipmentItemUpdatedEvent notification, CancellationToken cancellationToken)
        {
            _logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
            return Task.CompletedTask;
        }
    }
