//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Validator for AddEditCostItemCommand: enforces field length and required property rules for CostItem entities.
// Docs: https://docs.cleanarchitectureblazor.com/features/costitem
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings


namespace CleanArchitecture.Blazor.Application.Features.CostItems.Commands.AddEdit;

public class AddEditCostItemCommandValidator : AbstractValidator<AddEditCostItemCommand>
{
    public AddEditCostItemCommandValidator()
    {
                RuleFor(v => v.ProjectId).NotNull(); 
    RuleFor(v => v.Description).MaximumLength(255); 
    RuleFor(v => v.Quantity).NotNull(); 
    RuleFor(v => v.UnitCost).NotNull(); 
    RuleFor(v => v.TotalCost).NotNull(); 
    RuleFor(v => v.Category).MaximumLength(255); 

     }

}

