////------------------------------------------------------------------------------
//// <auto-generated>
//// CleanArchitecture.Blazor - MIT Licensed.
//// Author: neozhu
//// Created/Modified: 2025-09-23
//// Import command & template for assignments.
//// Validates Excel data, prevents duplicates, and provides a template for bulk entry.
//// Docs: https://docs.cleanarchitectureblazor.com/features/assignment
//// </auto-generated>
////------------------------------------------------------------------------------
//#nullable enable
//#nullable disable warnings

//using CleanArchitecture.Blazor.Application.Features.Assignments.DTOs;
//using CleanArchitecture.Blazor.Application.Features.Assignments.Caching;

//namespace CleanArchitecture.Blazor.Application.Features.Assignments.Commands.Import;

//    public class ImportAssignmentsCommand: ICacheInvalidatorRequest<Result<int>>
//    {
//        public string FileName { get; set; }
//        public byte[] Data { get; set; }
//        public string CacheKey => AssignmentCacheKey.GetAllCacheKey;
//        public IEnumerable<string>? Tags => AssignmentCacheKey.Tags;
//        public ImportAssignmentsCommand(string fileName,byte[] data)
//        {
//           FileName = fileName;
//           Data = data;
//        }
//    }
//    public record class CreateAssignmentsTemplateCommand : IRequest<Result<byte[]>>
//    {
 
//    }

//    public class ImportAssignmentsCommandHandler : 
//                 IRequestHandler<CreateAssignmentsTemplateCommand, Result<byte[]>>,
//                 IRequestHandler<ImportAssignmentsCommand, Result<int>>
//    {
//        private readonly IApplicationDbContext _context;
//        private readonly IStringLocalizer<ImportAssignmentsCommandHandler> _localizer;
//        private readonly IExcelService _excelService;
//        private readonly AssignmentDto _dto = new();
//        private readonly IMapper _mapper;
//        public ImportAssignmentsCommandHandler(
//            IApplicationDbContext context,
//            IMapper mapper,
//            IExcelService excelService,
//            IStringLocalizer<ImportAssignmentsCommandHandler> localizer)
//        {
//            _context = context;
//            _localizer = localizer;
//            _excelService = excelService;
//            _mapper = mapper;
//        }
//        #nullable disable warnings
//        public async Task<Result<int>> Handle(ImportAssignmentsCommand request, CancellationToken cancellationToken)
//        {

//           var result = await _excelService.ImportAsync(request.Data, mappers: new Dictionary<string, Func<DataRow, AssignmentDto, object?>>
//            {
//                                { _localizer[_dto.GetMemberDescription(x=>x.ProjectId)], (row, item) => item.ProjectId =Convert.ToInt32(row[_localizer[_dto.GetMemberDescription(x=>x.ProjectId)]]) }, 
//                { _localizer[_dto.GetMemberDescription(x=>x.EmployeeId)], (row, item) => item.EmployeeId =Convert.ToInt32(row[_localizer[_dto.GetMemberDescription(x=>x.EmployeeId)]]) }, 
//                { _localizer[_dto.GetMemberDescription(x=>x.Role)], (row, item) => item.Role = row[_localizer[_dto.GetMemberDescription(x=>x.Role)]].ToString() }, 
//                { _localizer[_dto.GetMemberDescription(x=>x.StartDate)], (row, item) => item.StartDate =DateTime.Parse(row[_localizer[_dto.GetMemberDescription(x=>x.StartDate)]].ToString()) }, 
//                { _localizer[_dto.GetMemberDescription(x=>x.EndDate)], (row, item) => item.EndDate =DateTime.Parse(row[_localizer[_dto.GetMemberDescription(x=>x.EndDate)]].ToString()) }, 

//            }, _localizer[_dto.GetClassDescription()]);
//            if (result.Succeeded && result.Data is not null)
//            {
//                foreach (var dto in result.Data)
//                {
//                    var exists = await _context.Assignments.AnyAsync(x => x.Name == dto.Name, cancellationToken);
//                    if (!exists)
//                    {
//                        var item = _mapper.Map<Assignment>(dto);
//                        // add create domain events if this entity implement the IHasDomainEvent interface
//				        // item.AddDomainEvent(new AssignmentCreatedEvent(item));
//                        await _context.Assignments.AddAsync(item, cancellationToken);
//                    }
//                 }
//                 await _context.SaveChangesAsync(cancellationToken);
//                 return await Result<int>.SuccessAsync(result.Data.Count());
//           }
//           else
//           {
//               return await Result<int>.FailureAsync(result.Errors);
//           }
//        }
//        public async Task<Result<byte[]>> Handle(CreateAssignmentsTemplateCommand request, CancellationToken cancellationToken)
//        {
//            // TODO: Implement ImportAssignmentsCommandHandler method 
//            var fields = new string[] {
//                   // TODO: Define the fields that should be generate in the template, for example:
//                   _localizer[_dto.GetMemberDescription(x=>x.ProjectId)], 
//_localizer[_dto.GetMemberDescription(x=>x.EmployeeId)], 
//_localizer[_dto.GetMemberDescription(x=>x.Role)], 
//_localizer[_dto.GetMemberDescription(x=>x.StartDate)], 
//_localizer[_dto.GetMemberDescription(x=>x.EndDate)], 

//                };
//            var result = await _excelService.CreateTemplateAsync(fields, _localizer[_dto.GetClassDescription()]);
//            return await Result<byte[]>.SuccessAsync(result);
//        }
//    }

