////------------------------------------------------------------------------------
//// <auto-generated>
////     This file is part of the CleanArchitecture.Blazor project.
////     Licensed to the .NET Foundation under one or more agreements.
////     The .NET Foundation licenses this file to you under the MIT license.
////     See the LICENSE file in the project root for more information.
////
////     Author: neozhu
////     Created Date: 2025-03-27
////     Last Modified: 2025-03-27
////     Description: 
////       Handles the `PurchaseInvoiceDeletedEvent` which occurs when a new purchaseinvoice is deleted.
////       This event handler can be extended to trigger additional actions, such as 
////       sending notifications or updating other systems.
//// </auto-generated>
////------------------------------------------------------------------------------

//namespace CleanArchitecture.Blazor.Application.Features.PurchaseInvoices.EventHandlers;

//    public class PurchaseInvoiceDeletedEventHandler : INotificationHandler<PurchaseInvoiceDeletedEvent>
//    {
//        private readonly ILogger<PurchaseInvoiceDeletedEventHandler> _logger;

//        public PurchaseInvoiceDeletedEventHandler(
//            ILogger<PurchaseInvoiceDeletedEventHandler> logger
//            )
//        {
//            _logger = logger;
//        }
//        public Task Handle(PurchaseInvoiceDeletedEvent notification, CancellationToken cancellationToken)
//        {
//            _logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
//            return Task.CompletedTask;
//        }
//    }
