//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-09-23
//     Last Modified: 2025-09-23
//     Description: 
//       Defines a query to export assignment data to an Excel file. This query 
//       applies advanced filtering options and generates an Excel file with 
//       the specified assignment details.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Assignments.DTOs;
using CleanArchitecture.Blazor.Application.Features.Assignments.Caching;
using CleanArchitecture.Blazor.Application.Features.Assignments.Specifications;

namespace CleanArchitecture.Blazor.Application.Features.Assignments.Queries.Export;

public class ExportAssignmentsQuery : AssignmentAdvancedFilter, ICacheableRequest<Result<byte[]>>
{
      public AssignmentAdvancedSpecification Specification => new AssignmentAdvancedSpecification(this);
      public IEnumerable<string>? Tags => AssignmentCacheKey.Tags;
    public override string ToString()
    {
        return $"Listview:{ListView}:{CurrentUser?.UserId}, Search:{Keyword}, {OrderBy}, {SortDirection}";
    }
    public string CacheKey => AssignmentCacheKey.GetExportCacheKey($"{this}");
}
    
public class ExportAssignmentsQueryHandler :
         IRequestHandler<ExportAssignmentsQuery, Result<byte[]>>
{
        private readonly IMapper _mapper;
        private readonly IApplicationDbContext _context;
        private readonly IExcelService _excelService;
        private readonly IStringLocalizer<ExportAssignmentsQueryHandler> _localizer;
        private readonly AssignmentDto _dto = new();
        public ExportAssignmentsQueryHandler(
            IMapper mapper,
            IApplicationDbContext context,
            IExcelService excelService,
            IStringLocalizer<ExportAssignmentsQueryHandler> localizer
            )
        {
            _mapper = mapper;
            _context = context;
            _excelService = excelService;
            _localizer = localizer;
        }
        #nullable disable warnings
        public async Task<Result<byte[]>> Handle(ExportAssignmentsQuery request, CancellationToken cancellationToken)
        {
            var data = await _context.Assignments.ApplySpecification(request.Specification)
                       .OrderBy($"{request.OrderBy} {request.SortDirection}")
                       .ProjectTo<AssignmentDto>(_mapper.ConfigurationProvider)
                       .AsNoTracking()
                       .ToListAsync(cancellationToken);
            var result = await _excelService.ExportAsync(data,
                new Dictionary<string, Func<AssignmentDto, object?>>()
                {
                    // TODO: Define the fields that should be exported, for example:
                                     {_localizer[_dto.GetMemberDescription(x=>x.ProjectId)],item => item.ProjectId}, 
                 {_localizer[_dto.GetMemberDescription(x=>x.EmployeeId)],item => item.EmployeeId}, 
                 {_localizer[_dto.GetMemberDescription(x=>x.Role)],item => item.Role}, 
                 {_localizer[_dto.GetMemberDescription(x=>x.StartDate)],item => item.StartDate}, 
                 {_localizer[_dto.GetMemberDescription(x=>x.EndDate)],item => item.EndDate}, 

                }
                , _localizer[_dto.GetClassDescription()]);
            return await Result<byte[]>.SuccessAsync(result);
        }
}
