//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-09-24
//     Last Modified: 2025-09-24
//     Description: 
//       Defines a query to retrieve a quoteversion by its ID. The result is cached 
//       to optimize performance for repeated retrievals of the same quoteversion.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.QuoteVersions.DTOs;
using CleanArchitecture.Blazor.Application.Features.QuoteVersions.Caching;
using CleanArchitecture.Blazor.Application.Features.QuoteVersions.Specifications;

namespace CleanArchitecture.Blazor.Application.Features.QuoteVersions.Queries.GetById;

public class GetQuoteVersionByIdQuery : ICacheableRequest<Result<QuoteVersionDto>>
{
   public required int Id { get; set; }
   public string CacheKey => QuoteVersionCacheKey.GetByIdCacheKey($"{Id}");
   public IEnumerable<string>? Tags => QuoteVersionCacheKey.Tags;
}

public class GetQuoteVersionByIdQueryHandler :
     IRequestHandler<GetQuoteVersionByIdQuery, Result<QuoteVersionDto>>
{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    private readonly IMapper _mapper;
    public GetQuoteVersionByIdQueryHandler(
        IMapper mapper,
        IApplicationDbContextFactory dbContextFactory)
    {
        _mapper = mapper;
        _dbContextFactory = dbContextFactory;
    }

    public async Task<Result<QuoteVersionDto>> Handle(GetQuoteVersionByIdQuery request, CancellationToken cancellationToken)
    {
        await using var _context = await _dbContextFactory.CreateAsync(cancellationToken);
        var data = await _context.QuoteVersions.ApplySpecification(new QuoteVersionByIdSpecification(request.Id))
                                                .ProjectTo<QuoteVersionDto>(_mapper.ConfigurationProvider)
                                                .FirstAsync(cancellationToken) ?? throw new NotFoundException($"QuoteVersion with id: [{request.Id}] not found.");
        return await Result<QuoteVersionDto>.SuccessAsync(data);
    }
}
