//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-03-27
//     Last Modified: 2025-03-27
//     Description: 
//       Defines a query for retrieving purchaseinvoices with pagination and filtering 
//       options. The result is cached to enhance performance for repeated queries.
// </auto-generated>
//------------------------------------------------------------------------------

using CleanArchitecture.Blazor.Application.Features.PurchaseInvoices.DTOs;
using CleanArchitecture.Blazor.Application.Features.PurchaseInvoices.Caching;
using CleanArchitecture.Blazor.Application.Features.PurchaseInvoices.Mappers;
using CleanArchitecture.Blazor.Application.Features.PurchaseInvoices.Specifications;

namespace CleanArchitecture.Blazor.Application.Features.PurchaseInvoices.Queries.Pagination;

public class PurchaseInvoicesWithPaginationQuery : PurchaseInvoiceAdvancedFilter, ICacheableRequest<PaginatedData<PurchaseInvoiceDto>>
{
    public override string ToString()
    {
        return $"Listview:{ListView}:{CurrentUser?.UserId}-{LocalTimezoneOffset.TotalHours}, Search:{Keyword}, {OrderBy}, {SortDirection}, {PageNumber}, {PageSize}";
    }
    public string CacheKey => PurchaseInvoiceCacheKey.GetPaginationCacheKey($"{this}");
    public IEnumerable<string>? Tags => PurchaseInvoiceCacheKey.Tags;
    public PurchaseInvoiceAdvancedSpecification Specification => new PurchaseInvoiceAdvancedSpecification(this);
}
    
public class PurchaseInvoicesWithPaginationQueryHandler :
         IRequestHandler<PurchaseInvoicesWithPaginationQuery, PaginatedData<PurchaseInvoiceDto>>
{
        private readonly IApplicationDbContext _context;

        public PurchaseInvoicesWithPaginationQueryHandler(
            IApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<PaginatedData<PurchaseInvoiceDto>> Handle(PurchaseInvoicesWithPaginationQuery request, CancellationToken cancellationToken)
        {
           var data = await _context.PurchaseInvoices.OrderBy($"{request.OrderBy} {request.SortDirection}")
                                                   .ProjectToPaginatedDataAsync(request.Specification, 
                                                                                request.PageNumber, 
                                                                                request.PageSize, 
                                                                                PurchaseInvoiceMapper.ToDto, 
                                                                                cancellationToken);
            return data;
        }
}