//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Command and handler for deleting ServiceVariant entities.
// Implements cache invalidation and triggers domain events.
// Docs: https://docs.cleanarchitectureblazor.com/features/servicevariant
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.ServiceVariants.Caching;

namespace CleanArchitecture.Blazor.Application.Features.ServiceVariants.Commands.Delete;

public class DeleteServiceVariantCommand:  ICacheInvalidatorRequest<Result>
{
  public int[] Id {  get; }
  public string CacheKey => ServiceVariantCacheKey.GetAllCacheKey;
  public IEnumerable<string>? Tags => ServiceVariantCacheKey.Tags;
  public DeleteServiceVariantCommand(int[] id)
  {
    Id = id;
  }
}

public class DeleteServiceVariantCommandHandler : 
             IRequestHandler<DeleteServiceVariantCommand, Result>

{
    private readonly IApplicationDbContext _context;
    public DeleteServiceVariantCommandHandler(
        IApplicationDbContext context)
    {
        _context = context;
    }
    public async Task<Result> Handle(DeleteServiceVariantCommand request, CancellationToken cancellationToken)
    {
        var items = await _context.ServiceVariants.Where(x=>request.Id.Contains(x.Id)).ToListAsync(cancellationToken);
        foreach (var item in items)
        {
		    // raise a delete domain event
			item.AddDomainEvent(new ServiceVariantDeletedEvent(item));
            _context.ServiceVariants.Remove(item);
        }
        await _context.SaveChangesAsync(cancellationToken);
        return await Result.SuccessAsync();
    }

}

