//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-09-24
//     Last Modified: 2025-09-24
//     Description: 
//       Defines a query to retrieve all quoteattachments from the database. The result 
//       is cached to improve performance and reduce database load for repeated 
//       queries.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.QuoteAttachments.DTOs;
using CleanArchitecture.Blazor.Application.Features.QuoteAttachments.Caching;

namespace CleanArchitecture.Blazor.Application.Features.QuoteAttachments.Queries.GetAll;

public class GetAllQuoteAttachmentsQuery : ICacheableRequest<IEnumerable<QuoteAttachmentDto>>
{
   public string CacheKey => QuoteAttachmentCacheKey.GetAllCacheKey;
   public IEnumerable<string>? Tags => QuoteAttachmentCacheKey.Tags;
}

public class GetAllQuoteAttachmentsQueryHandler :
     IRequestHandler<GetAllQuoteAttachmentsQuery, IEnumerable<QuoteAttachmentDto>>
{
    private readonly IApplicationDbContext _context;
    private readonly IMapper _mapper;
    public GetAllQuoteAttachmentsQueryHandler(
        IMapper mapper,
        IApplicationDbContext context)
    {
        _mapper = mapper;
        _context = context;
    }

    public async Task<IEnumerable<QuoteAttachmentDto>> Handle(GetAllQuoteAttachmentsQuery request, CancellationToken cancellationToken)
    {
        var data = await _context.QuoteAttachments.ProjectTo<QuoteAttachmentDto>(_mapper.ConfigurationProvider)
                                                .AsNoTracking()
                                                .ToListAsync(cancellationToken);
        return data;
    }
}


