//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Validator for CreateServiceVariantCommand: enforces max lengths and required fields for ServiceVariant entities.
// Docs: https://docs.cleanarchitectureblazor.com/features/servicevariant
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.ServiceVariants.Commands.Create;

public class CreateServiceVariantCommandValidator : AbstractValidator<CreateServiceVariantCommand>
{
        public CreateServiceVariantCommandValidator()
        {
                RuleFor(v => v.ServiceId).NotNull(); 
    RuleFor(v => v.Name).MaximumLength(50).NotEmpty(); 
    RuleFor(v => v.Unit).MaximumLength(255); 

        }
       
}

