//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-23
// Command and handler for deleting Assignment entities.
// Implements cache invalidation and triggers domain events.
// Docs: https://docs.cleanarchitectureblazor.com/features/assignment
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Assignments.Caching;

namespace CleanArchitecture.Blazor.Application.Features.Assignments.Commands.Delete;

public class DeleteAssignmentCommand:  ICacheInvalidatorRequest<Result>
{
  public int[] Id {  get; }
  public string CacheKey => AssignmentCacheKey.GetAllCacheKey;
  public IEnumerable<string>? Tags => AssignmentCacheKey.Tags;
  public DeleteAssignmentCommand(int[] id)
  {
    Id = id;
  }
}

public class DeleteAssignmentCommandHandler : 
             IRequestHandler<DeleteAssignmentCommand, Result>

{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    public DeleteAssignmentCommandHandler(
        IApplicationDbContextFactory dbContextFactory)
    {
        _dbContextFactory = dbContextFactory;
    }
    public async Task<Result> Handle(DeleteAssignmentCommand request, CancellationToken cancellationToken)
    {
        await using var _context = await _dbContextFactory.CreateAsync(cancellationToken);
        var items = await _context.Assignments.Where(x=>request.Id.Contains(x.Id)).ToListAsync(cancellationToken);
        foreach (var item in items)
        {
		    // raise a delete domain event
			item.AddDomainEvent(new AssignmentDeletedEvent(item));
            _context.Assignments.Remove(item);
        }
        await _context.SaveChangesAsync(cancellationToken);
        return await Result.SuccessAsync();
    }

}

