//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Handles QuoteAttachmentUpdatedEvent: triggered when a quoteattachment is updated.
// Extendable for additional actions (e.g., notifications, system updates).
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Application.Features.QuoteAttachments.EventHandlers;

    public class QuoteAttachmentUpdatedEventHandler : INotificationHandler<QuoteAttachmentUpdatedEvent>
    {
        private readonly ILogger<QuoteAttachmentUpdatedEventHandler> _logger;

        public QuoteAttachmentUpdatedEventHandler(
            ILogger<QuoteAttachmentUpdatedEventHandler> logger
            )
        {
            _logger = logger;
        }
        public Task Handle(QuoteAttachmentUpdatedEvent notification, CancellationToken cancellationToken)
        {
            _logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
            return Task.CompletedTask;
        }
    }
