//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Handles QuoteAttachmentDeletedEvent: triggered when a quoteattachment is deleted.
// Extendable for additional actions (e.g., notifications, system updates).
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Application.Features.QuoteAttachments.EventHandlers;

    public class QuoteAttachmentDeletedEventHandler : INotificationHandler<QuoteAttachmentDeletedEvent>
    {
        private readonly ILogger<QuoteAttachmentDeletedEventHandler> _logger;

        public QuoteAttachmentDeletedEventHandler(
            ILogger<QuoteAttachmentDeletedEventHandler> logger
            )
        {
            _logger = logger;
        }
        public Task Handle(QuoteAttachmentDeletedEvent notification, CancellationToken cancellationToken)
        {
            _logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
            return Task.CompletedTask;
        }
    }
