//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// QuoteApprovalDto: transfers quoteapproval data between layers.
// Docs: https://docs.cleanarchitectureblazor.com/features/quoteapproval
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings


namespace CleanArchitecture.Blazor.Application.Features.QuoteApprovals.DTOs;

[Description("QuoteApprovals")]
public class QuoteApprovalDto
{
    [Description("Id")]
    public int Id { get; set; }
        [Description("Quote id")]
    public int QuoteId {get;set;} 
    [Description("Quote")]
    public QuoteDto? Quote {get;set;} 
    [Description("Approver id")]
    public int ApproverId {get;set;} 
    [Description("Approver")]
    public EmployeeDto? Approver {get;set;} 
    [Description("Status")]
    public ApprovalStatus? Status {get;set;} 
    [Description("Approved at utc")]
    public DateTime? ApprovedAtUtc {get;set;} 
    [Description("Comment")]
    public string? Comment {get;set;} 


    private class Mapping : Profile
    {
        public Mapping()
        {
            CreateMap<QuoteApproval, QuoteApprovalDto>(MemberList.None);
            CreateMap<QuoteApprovalDto, QuoteApproval>(MemberList.None)
            .ForMember(dest => dest.Created, opt => opt.Ignore())
            .ForMember(dest => dest.CreatedBy, opt => opt.Ignore())
            .ForMember(dest => dest.LastModified, opt => opt.Ignore())
            .ForMember(dest => dest.LastModifiedBy, opt => opt.Ignore())
            .ForMember(dest => dest.DomainEvents, opt => opt.Ignore());
        }
    }
}

