//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-09-24
//     Last Modified: 2025-09-24
//     Description: 
//       Defines a query to retrieve all vendors from the database. The result 
//       is cached to improve performance and reduce database load for repeated 
//       queries.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Vendors.DTOs;
using CleanArchitecture.Blazor.Application.Features.Vendors.Caching;

namespace CleanArchitecture.Blazor.Application.Features.Vendors.Queries.GetAll;

public class GetAllVendorsQuery : ICacheableRequest<IEnumerable<VendorDto>>
{
   public string CacheKey => VendorCacheKey.GetAllCacheKey;
   public IEnumerable<string>? Tags => VendorCacheKey.Tags;
}

public class GetAllVendorsQueryHandler :
     IRequestHandler<GetAllVendorsQuery, IEnumerable<VendorDto>>
{
    private readonly IApplicationDbContext _context;
    private readonly IMapper _mapper;
    public GetAllVendorsQueryHandler(
        IMapper mapper,
        IApplicationDbContext context)
    {
        _mapper = mapper;
        _context = context;
    }

    public async Task<IEnumerable<VendorDto>> Handle(GetAllVendorsQuery request, CancellationToken cancellationToken)
    {
        var data = await _context.Vendors.ProjectTo<VendorDto>(_mapper.ConfigurationProvider)
                                                .AsNoTracking()
                                                .ToListAsync(cancellationToken);
        return data;
    }
}


