//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under one or more agreements.
//     The .NET Foundation licenses this file to you under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-03-21
//     Last Modified: 2025-03-21
//     Description: 
//       This file defines the validation rules for the DeleteSubCategoryCommand used
//       to delete SubCategory entities within the CleanArchitecture.Blazor application. 
//       It ensures that the command has valid input, particularly verifying that the 
//       list of subcategory IDs to delete is not null and contains only positive IDs.
//     
//     Documentation:
//       https://docs.cleanarchitectureblazor.com/features/subcategory
// </auto-generated>
//------------------------------------------------------------------------------

// Usage:
// This validator ensures that the DeleteSubCategoryCommand is valid before attempting 
// to delete subcategory records from the system. It verifies that the ID list is not 
// null and that all IDs are greater than zero.

namespace CleanArchitecture.Blazor.Application.Features.SubCategories.Commands.Delete;

public class DeleteSubCategoryCommandValidator : AbstractValidator<DeleteSubCategoryCommand>
{
        public DeleteSubCategoryCommandValidator()
        {
          
            RuleFor(v => v.Id).NotNull().ForEach(v=>v.GreaterThan(0));
          
        }
}
    

