//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under one or more agreements.
//     The .NET Foundation licenses this file to you under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-03-21
//     Last Modified: 2025-03-21
//     Description: 
//       This file defines the command and its handler for deleting one or more
//       SubCategory entities from the CleanArchitecture.Blazor application. It
//       implements caching invalidation logic to ensure that data consistency is
//       maintained. Domain events are triggered for deleted entities to support 
//       integration with other parts of the system.
//       for separation of concerns and encapsulation.
//     
//     Documentation:
//       https://docs.cleanarchitectureblazor.com/features/subcategory
// </auto-generated>
//------------------------------------------------------------------------------

// Usage:
// This command can be used to delete multiple SubCategories from the system by specifying
// their IDs. The handler also raises domain events for each deleted subcategory to
// notify other bounded contexts and invalidate relevant cache entries.

using CleanArchitecture.Blazor.Application.Features.SubCategories.Caching;


namespace CleanArchitecture.Blazor.Application.Features.SubCategories.Commands.Delete;

public class DeleteSubCategoryCommand:  ICacheInvalidatorRequest<Result<int>>
{
  public int[] Id {  get; }
  public string CacheKey => SubCategoryCacheKey.GetAllCacheKey;
  public IEnumerable<string>? Tags => SubCategoryCacheKey.Tags;
  public DeleteSubCategoryCommand(int[] id)
  {
    Id = id;
  }
}

public class DeleteSubCategoryCommandHandler : 
             IRequestHandler<DeleteSubCategoryCommand, Result<int>>

{
    private readonly IApplicationDbContext _context;
    public DeleteSubCategoryCommandHandler(
        IApplicationDbContext context)
    {
        _context = context;
    }
    public async Task<Result<int>> Handle(DeleteSubCategoryCommand request, CancellationToken cancellationToken)
    {
        var items = await _context.SubCategories.Where(x=>request.Id.Contains(x.Id)).ToListAsync(cancellationToken);
        foreach (var item in items)
        {
            _context.SubCategories.Remove(item);
        }
        var result = await _context.SaveChangesAsync(cancellationToken);
        return await Result<int>.SuccessAsync(result);
    }

}

