//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-09-24
//     Last Modified: 2025-09-24
//     Description: 
//       Defines a query to retrieve a costitem by its ID. The result is cached 
//       to optimize performance for repeated retrievals of the same costitem.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.CostItems.DTOs;
using CleanArchitecture.Blazor.Application.Features.CostItems.Caching;
using CleanArchitecture.Blazor.Application.Features.CostItems.Specifications;

namespace CleanArchitecture.Blazor.Application.Features.CostItems.Queries.GetById;

public class GetCostItemByIdQuery : ICacheableRequest<Result<CostItemDto>>
{
   public required int Id { get; set; }
   public string CacheKey => CostItemCacheKey.GetByIdCacheKey($"{Id}");
   public IEnumerable<string>? Tags => CostItemCacheKey.Tags;
}

public class GetCostItemByIdQueryHandler :
     IRequestHandler<GetCostItemByIdQuery, Result<CostItemDto>>
{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    private readonly IMapper _mapper;
    public GetCostItemByIdQueryHandler(
        IMapper mapper,
        IApplicationDbContextFactory dbContextFactory)
    {
        _mapper = mapper;
        _dbContextFactory = dbContextFactory;
    }

    public async Task<Result<CostItemDto>> Handle(GetCostItemByIdQuery request, CancellationToken cancellationToken)
    {
        await using var _context = await _dbContextFactory.CreateAsync(cancellationToken);
        var data = await _context.CostItems.ApplySpecification(new CostItemByIdSpecification(request.Id))
                                                .ProjectTo<CostItemDto>(_mapper.ConfigurationProvider)
                                                .FirstAsync(cancellationToken) ?? throw new NotFoundException($"CostItem with id: [{request.Id}] not found.");
        return await Result<CostItemDto>.SuccessAsync(data);
    }
}
