//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-23
// Validator for UpdateCompanyCommand: ensures required fields (e.g., Id, non-empty Name, max length for properties) are valid for updating a company.
// Docs: https://docs.cleanarchitectureblazor.com/features/company
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.Companies.Commands.Update;

public class UpdateCompanyCommandValidator : AbstractValidator<UpdateCompanyCommand>
{
        public UpdateCompanyCommandValidator()
        {
           RuleFor(v => v.Id).NotNull();
               RuleFor(v => v.Name).MaximumLength(50).NotEmpty(); 
    RuleFor(v => v.VatNumber).MaximumLength(255); 
    RuleFor(v => v.Address).MaximumLength(255); 
    RuleFor(v => v.Country).MaximumLength(255); 
    RuleFor(v => v.Website).MaximumLength(255); 
    RuleFor(v => v.Industry).MaximumLength(255); 

          
        }
    
}

