//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Handles ProjectDeletedEvent: triggered when a project is deleted.
// Extendable for additional actions (e.g., notifications, system updates).
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Application.Features.Projects.EventHandlers;

    public class ProjectDeletedEventHandler : INotificationHandler<ProjectDeletedEvent>
    {
        private readonly ILogger<ProjectDeletedEventHandler> _logger;

        public ProjectDeletedEventHandler(
            ILogger<ProjectDeletedEventHandler> logger
            )
        {
            _logger = logger;
        }
        public Task Handle(ProjectDeletedEvent notification, CancellationToken cancellationToken)
        {
            _logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
            return Task.CompletedTask;
        }
    }
