//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Handles ProjectUpdatedEvent: triggered when a project is updated.
// Extendable for additional actions (e.g., notifications, system updates).
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Application.Features.Projects.EventHandlers;

    public class ProjectUpdatedEventHandler : INotificationHandler<ProjectUpdatedEvent>
    {
        private readonly ILogger<ProjectUpdatedEventHandler> _logger;

        public ProjectUpdatedEventHandler(
            ILogger<ProjectUpdatedEventHandler> logger
            )
        {
            _logger = logger;
        }
        public Task Handle(ProjectUpdatedEvent notification, CancellationToken cancellationToken)
        {
            _logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
            return Task.CompletedTask;
        }
    }
