//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-09-24
//     Last Modified: 2025-09-24
//     Description: 
//       Defines a query to retrieve all quotelines from the database. The result 
//       is cached to improve performance and reduce database load for repeated 
//       queries.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.QuoteLines.DTOs;
using CleanArchitecture.Blazor.Application.Features.QuoteLines.Caching;

namespace CleanArchitecture.Blazor.Application.Features.QuoteLines.Queries.GetAll;

public class GetAllQuoteLinesQuery : ICacheableRequest<IEnumerable<QuoteLineDto>>
{
   public string CacheKey => QuoteLineCacheKey.GetAllCacheKey;
   public IEnumerable<string>? Tags => QuoteLineCacheKey.Tags;
}

public class GetAllQuoteLinesQueryHandler :
     IRequestHandler<GetAllQuoteLinesQuery, IEnumerable<QuoteLineDto>>
{
    private readonly IApplicationDbContext _context;
    private readonly IMapper _mapper;
    public GetAllQuoteLinesQueryHandler(
        IMapper mapper,
        IApplicationDbContext context)
    {
        _mapper = mapper;
        _context = context;
    }

    public async Task<IEnumerable<QuoteLineDto>> Handle(GetAllQuoteLinesQuery request, CancellationToken cancellationToken)
    {
        var data = await _context.QuoteLines.ProjectTo<QuoteLineDto>(_mapper.ConfigurationProvider)
                                                .AsNoTracking()
                                                .ToListAsync(cancellationToken);
        return data;
    }
}


