//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-09-24
//     Last Modified: 2025-09-24
//     Description: 
//       Defines a query to retrieve all quotes from the database. The result 
//       is cached to improve performance and reduce database load for repeated 
//       queries.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Quotes.DTOs;
using CleanArchitecture.Blazor.Application.Features.Quotes.Caching;

namespace CleanArchitecture.Blazor.Application.Features.Quotes.Queries.GetAll;

public class GetAllQuotesQuery : ICacheableRequest<IEnumerable<QuoteDto>>
{
   public string CacheKey => QuoteCacheKey.GetAllCacheKey;
   public IEnumerable<string>? Tags => QuoteCacheKey.Tags;
}

public class GetAllQuotesQueryHandler :
     IRequestHandler<GetAllQuotesQuery, IEnumerable<QuoteDto>>
{
    private readonly IApplicationDbContextFactory _dbContextFactory;;
    private readonly IMapper _mapper;
    public GetAllQuotesQueryHandler(
        IMapper mapper,
        IApplicationDbContext context)
    {
        _mapper = mapper;
        _context = context;
    }

    public async Task<IEnumerable<QuoteDto>> Handle(GetAllQuotesQuery request, CancellationToken cancellationToken)
    {
        var data = await _context.Quotes.ProjectTo<QuoteDto>(_mapper.ConfigurationProvider)
                                                .AsNoTracking()
                                                .ToListAsync(cancellationToken);
        return data;
    }
}


