////------------------------------------------------------------------------------
//// <auto-generated>
////     This file is part of the CleanArchitecture.Blazor project.
////     Licensed to the .NET Foundation under the MIT license.
////     See the LICENSE file in the project root for more information.
////
////     Author: neozhu
////     Created Date: 2025-03-27
////     Last Modified: 2025-03-27
////     Description: 
////       Defines a query to export purchaseitem data to an Excel file. This query 
////       applies advanced filtering options and generates an Excel file with 
////       the specified purchaseitem details.
//// </auto-generated>
////------------------------------------------------------------------------------

//using CleanArchitecture.Blazor.Application.Features.PurchaseItems.DTOs;
//using CleanArchitecture.Blazor.Application.Features.PurchaseItems.Mappers;
//using CleanArchitecture.Blazor.Application.Features.PurchaseItems.Caching;
//using CleanArchitecture.Blazor.Application.Features.PurchaseItems.Specifications;

//namespace CleanArchitecture.Blazor.Application.Features.PurchaseItems.Queries.Export;

//public class ExportPurchaseItemsQuery : PurchaseItemAdvancedFilter, ICacheableRequest<Result<byte[]>>
//{
//      public PurchaseItemAdvancedSpecification Specification => new PurchaseItemAdvancedSpecification(this);
//      public IEnumerable<string>? Tags => PurchaseItemCacheKey.Tags;
//    public override string ToString()
//    {
//        return $"Listview:{ListView}:{CurrentUser?.UserId}-{LocalTimezoneOffset.TotalHours}, Search:{Keyword}, {OrderBy}, {SortDirection}";
//    }
//    public string CacheKey => PurchaseItemCacheKey.GetExportCacheKey($"{this}");
//}
    
//public class ExportPurchaseItemsQueryHandler :
//         IRequestHandler<ExportPurchaseItemsQuery, Result<byte[]>>
//{
//        private readonly IApplicationDbContext _context;
//        private readonly IExcelService _excelService;
//        private readonly IStringLocalizer<ExportPurchaseItemsQueryHandler> _localizer;
//        private readonly PurchaseItemDto _dto = new();
//        public ExportPurchaseItemsQueryHandler(
//            IApplicationDbContext context,
//            IExcelService excelService,
//            IStringLocalizer<ExportPurchaseItemsQueryHandler> localizer
//            )
//        {
//            _context = context;
//            _excelService = excelService;
//            _localizer = localizer;
//        }
//        #nullable disable warnings
//        public async Task<Result<byte[]>> Handle(ExportPurchaseItemsQuery request, CancellationToken cancellationToken)
//        {
//            var data = await _context.PurchaseItems.ApplySpecification(request.Specification)
//                       .OrderBy($"{request.OrderBy} {request.SortDirection}")
//                       .ProjectTo()
//                       .AsNoTracking()
//                       .ToListAsync(cancellationToken);
//            var result = await _excelService.ExportAsync(data,
//                new Dictionary<string, Func<PurchaseItemDto, object?>>()
//                {
//                    // TODO: Define the fields that should be exported, for example:
//                    {_localizer[_dto.GetMemberDescription(x=>x.InvoiceId)],item => item.InvoiceId}, 
//{_localizer[_dto.GetMemberDescription(x=>x.ItemCode)],item => item.ItemCode}, 
//{_localizer[_dto.GetMemberDescription(x=>x.ItemDescription)],item => item.ItemDescription}, 
//{_localizer[_dto.GetMemberDescription(x=>x.Quantity)],item => item.Quantity}, 
//{_localizer[_dto.GetMemberDescription(x=>x.Unit)],item => item.Unit}, 
//{_localizer[_dto.GetMemberDescription(x=>x.Color)],item => item.Color}, 
//{_localizer[_dto.GetMemberDescription(x=>x.UnitPrice)],item => item.UnitPrice}, 
//{_localizer[_dto.GetMemberDescription(x=>x.VATPercentage)],item => item.VATPercentage}, 
//{_localizer[_dto.GetMemberDescription(x=>x.VATAmount)],item => item.VATAmount}, 
//{_localizer[_dto.GetMemberDescription(x=>x.TotalAmount)],item => item.TotalAmount}, 

//                }
//                , _localizer[_dto.GetClassDescription()]);
//            return await Result<byte[]>.SuccessAsync(result);
//        }
//}
