//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Validator for CreateProjectCommand: enforces max lengths and required fields for Project entities.
// Docs: https://docs.cleanarchitectureblazor.com/features/project
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.Projects.Commands.Create;

public class CreateProjectCommandValidator : AbstractValidator<CreateProjectCommand>
{
        public CreateProjectCommandValidator()
        {
                RuleFor(v => v.Name).MaximumLength(50).NotEmpty(); 
    RuleFor(v => v.Status).NotNull(); 
    RuleFor(v => v.OwnerId).NotNull(); 

        }
       
}

