//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Validator for UpdateProjectCommand: ensures required fields (e.g., Id, non-empty Name, max length for properties) are valid for updating a project.
// Docs: https://docs.cleanarchitectureblazor.com/features/project
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.Projects.Commands.Update;

public class UpdateProjectCommandValidator : AbstractValidator<UpdateProjectCommand>
{
        public UpdateProjectCommandValidator()
        {
           RuleFor(v => v.Id).NotNull();
               RuleFor(v => v.Name).MaximumLength(50).NotEmpty(); 
    RuleFor(v => v.Status).NotNull(); 
    RuleFor(v => v.OwnerId).NotNull(); 

          
        }
    
}

