//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Handles VendorUpdatedEvent: triggered when a vendor is updated.
// Extendable for additional actions (e.g., notifications, system updates).
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Application.Features.Vendors.EventHandlers;

    public class VendorUpdatedEventHandler : INotificationHandler<VendorUpdatedEvent>
    {
        private readonly ILogger<VendorUpdatedEventHandler> _logger;

        public VendorUpdatedEventHandler(
            ILogger<VendorUpdatedEventHandler> logger
            )
        {
            _logger = logger;
        }
        public Task Handle(VendorUpdatedEvent notification, CancellationToken cancellationToken)
        {
            _logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
            return Task.CompletedTask;
        }
    }
