//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// UpdateDocumentCommand & handler: updates an existing Document with cache invalidation and raises DocumentUpdatedEvent.
// Docs: https://docs.cleanarchitectureblazor.com/features/document
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Documents.DTOs;
using CleanArchitecture.Blazor.Application.Features.Documents.Caching;

namespace CleanArchitecture.Blazor.Application.Features.Documents.Commands.Update;

public class UpdateDocumentCommand: ICacheInvalidatorRequest<Result<int>>
{
      [Description("Id")]
      public int Id { get; set; }
          [Description("Title")]
    public string? Title {get;set;} 
    [Description("Description")]
    public string? Description {get;set;} 
    [Description("Status")]
    public JobStatus? Status {get;set;} 
    [Description("Content")]
    public string? Content {get;set;} 
    [Description("Is public")]
    public bool IsPublic {get;set;} 
    [Description("Url")]
    public string? URL {get;set;} 
    [Description("Document type")]
    public DocumentType? DocumentType {get;set;} 
    [Description("Tenant")]
    public TenantDto? Tenant {get;set;} 
    [Description("Tenant id")]
    public string? TenantId {get;set;} 

      public string CacheKey => DocumentCacheKey.GetAllCacheKey;
      public IEnumerable<string>? Tags => DocumentCacheKey.Tags;

    private class Mapping : Profile
    {
        public Mapping()
        {
            CreateMap<UpdateDocumentCommand, Document>(MemberList.None);
            CreateMap<DocumentDto,UpdateDocumentCommand>(MemberList.None);
        }
    }

}

public class UpdateDocumentCommandHandler : IRequestHandler<UpdateDocumentCommand, Result<int>>
{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    private readonly IMapper _mapper;
    public UpdateDocumentCommandHandler(
        IMapper mapper,
        IApplicationDbContextFactory dbContextFactory)
    {
        _dbContextFactory = dbContextFactory;
        _mapper = mapper;
    }
    public async Task<Result<int>> Handle(UpdateDocumentCommand request, CancellationToken cancellationToken)
    {
        await using var _context = await _dbContextFactory.CreateAsync(cancellationToken);
        var item = await _context.Documents.FindAsync(request.Id, cancellationToken);
       if (item == null)
       {
           return await Result<int>.FailureAsync($"Document with id: [{request.Id}] not found.");
       }
       item = _mapper.Map(request, item);
	    // raise a update domain event
	   item.AddDomainEvent(new DocumentUpdatedEvent(item));
       await _context.SaveChangesAsync(cancellationToken);
       return await Result<int>.SuccessAsync(item.Id);
    }
}

