//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// PricingModelDto: transfers pricingmodel data between layers.
// Docs: https://docs.cleanarchitectureblazor.com/features/pricingmodel
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings


namespace CleanArchitecture.Blazor.Application.Features.PricingModels.DTOs;

[Description("PricingModels")]
public class PricingModelDto
{
    [Description("Id")]
    public int Id { get; set; }
        [Description("Name")]
    public string Name {get;set;} 
    [Description("Type")]
    public PricingModelType? Type {get;set;} 
    [Description("Formula expression")]
    public string? FormulaExpression {get;set;} 
    [Description("Min fee")]
    public decimal? MinFee {get;set;} 
    [Description("Notes")]
    public string? Notes {get;set;} 


    private class Mapping : Profile
    {
        public Mapping()
        {
            CreateMap<PricingModel, PricingModelDto>(MemberList.None);
            CreateMap<PricingModelDto, PricingModel>(MemberList.None)
           
            .ForMember(dest => dest.DomainEvents, opt => opt.Ignore());
        }
    }
}

