//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-09-24
//     Last Modified: 2025-09-24
//     Description: 
//       Defines a query for retrieving projecttasks with pagination and filtering 
//       options. The result is cached to enhance performance for repeated queries.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.ProjectTasks.DTOs;
using CleanArchitecture.Blazor.Application.Features.ProjectTasks.Caching;
using CleanArchitecture.Blazor.Application.Features.ProjectTasks.Specifications;

namespace CleanArchitecture.Blazor.Application.Features.ProjectTasks.Queries.Pagination;

public class ProjectTasksWithPaginationQuery : ProjectTaskAdvancedFilter, ICacheableRequest<PaginatedData<ProjectTaskDto>>
{
    public override string ToString()
    {
        return $"Listview:{ListView}:{CurrentUser?.UserId}, Search:{Keyword}, {OrderBy}, {SortDirection}, {PageNumber}, {PageSize}";
    }
    public string CacheKey => ProjectTaskCacheKey.GetPaginationCacheKey($"{this}");
    public IEnumerable<string>? Tags => ProjectTaskCacheKey.Tags;
    public ProjectTaskAdvancedSpecification Specification => new ProjectTaskAdvancedSpecification(this);
}
    
public class ProjectTasksWithPaginationQueryHandler :
         IRequestHandler<ProjectTasksWithPaginationQuery, PaginatedData<ProjectTaskDto>>
{
        private readonly IApplicationDbContext _context;
        private readonly IMapper _mapper;
        public ProjectTasksWithPaginationQueryHandler(
            IMapper mapper,
            IApplicationDbContext context)
        {
            _mapper = mapper;
            _context = context;
        }

        public async Task<PaginatedData<ProjectTaskDto>> Handle(ProjectTasksWithPaginationQuery request, CancellationToken cancellationToken)
        {
           var data = await _context.ProjectTasks.OrderBy($"{request.OrderBy} {request.SortDirection}")
                                                   .ProjectToPaginatedDataAsync<ProjectTask, ProjectTaskDto>(request.Specification,
                                                    request.PageNumber,
                                                    request.PageSize,
                                                    _mapper.ConfigurationProvider,
                                                    cancellationToken);
            return data;
        }
}