//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under one or more agreements.
//     The .NET Foundation licenses this file to you under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-03-21
//     Last Modified: 2025-03-21
//     Description: 
//       This file defines the validation rules for the AddEditSubCategoryCommand 
//       used to add or edit SubCategory entities within the CleanArchitecture.Blazor 
//       application. It enforces maximum field lengths and required properties 
//       to maintain data integrity and validation standards.
//     
//     Documentation:
//       https://docs.cleanarchitectureblazor.com/features/subcategory
// </auto-generated>
//------------------------------------------------------------------------------

// Usage:
// This validator enforces constraints on the AddEditSubCategoryCommand, such as
// maximum field length for ...

namespace CleanArchitecture.Blazor.Application.Features.SubCategories.Commands.AddEdit;

public class AddEditSubCategoryCommandValidator : AbstractValidator<AddEditSubCategoryCommand>
{
    public AddEditSubCategoryCommandValidator()
    {
                RuleFor(v => v.Name).MaximumLength(50).NotEmpty(); 

     }

}

