//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-23
// Validator for UpdateAssignmentCommand: ensures required fields (e.g., Id, non-empty Name, max length for properties) are valid for updating a assignment.
// Docs: https://docs.cleanarchitectureblazor.com/features/assignment
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.Assignments.Commands.Update;

public class UpdateAssignmentCommandValidator : AbstractValidator<UpdateAssignmentCommand>
{
        public UpdateAssignmentCommandValidator()
        {
           RuleFor(v => v.Id).NotNull();
               RuleFor(v => v.ProjectId).NotNull(); 
    RuleFor(v => v.EmployeeId).NotNull(); 
    RuleFor(v => v.Role).MaximumLength(255); 

          
        }
    
}

