//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Command and handler for creating a new PurchaseOrder.
// Uses caching invalidation and domain events for data consistency.
// Docs: https://docs.cleanarchitectureblazor.com/features/purchaseorder
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.PurchaseOrders.Caching;

namespace CleanArchitecture.Blazor.Application.Features.PurchaseOrders.Commands.Create;

public class CreatePurchaseOrderCommand: ICacheInvalidatorRequest<Result<int>>
{
      [Description("Id")]
      public int Id { get; set; }
          [Description("Vendor id")]
    public int VendorId {get;set;} 
    [Description("Vendor")]
    public VendorDto? Vendor {get;set;} 
    [Description("Project id")]
    public int ProjectId {get;set;} 
    [Description("Project")]
    public ProjectDto? Project {get;set;} 
    [Description("Amount")]
    public decimal Amount {get;set;} 
    [Description("Date")]
    public DateTime? Date {get;set;} 
    [Description("Status")]
    public PurchaseOrderStatus? Status {get;set;} 
    [Description("External number")]
    public string? ExternalNumber {get;set;} 
    [Description("Notes")]
    public string? Notes {get;set;} 

      public string CacheKey => PurchaseOrderCacheKey.GetAllCacheKey;
      public IEnumerable<string>? Tags => PurchaseOrderCacheKey.Tags;
      private class Mapping : Profile
    {
        public Mapping()
        {
            CreateMap<CreatePurchaseOrderCommand, PurchaseOrder>(MemberList.None);
        }
    }
}
    
    public class CreatePurchaseOrderCommandHandler : IRequestHandler<CreatePurchaseOrderCommand, Result<int>>
    {
        private readonly IMapper _mapper;
        private readonly IApplicationDbContext _context;
        public CreatePurchaseOrderCommandHandler(
            IMapper mapper,
            IApplicationDbContext context)
        {
            _mapper = mapper;
            _context = context;
        }
        public async Task<Result<int>> Handle(CreatePurchaseOrderCommand request, CancellationToken cancellationToken)
        {
           var item = _mapper.Map<PurchaseOrder>(request);
           // raise a create domain event
	       item.AddDomainEvent(new PurchaseOrderCreatedEvent(item));
           _context.PurchaseOrders.Add(item);
           await _context.SaveChangesAsync(cancellationToken);
           return  await Result<int>.SuccessAsync(item.Id);
        }
    }

