//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-23
// Domain event for when a company is updated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Domain.Events;


    public class CompanyUpdatedEvent : DomainEvent
    {
        public CompanyUpdatedEvent(Company item)
        {
            Item = item;
        }

        public Company Item { get; }
    }

