//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Domain event for when a costitem is deleted.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Domain.Events;

    public class CostItemDeletedEvent : DomainEvent
    {
        public CostItemDeletedEvent(CostItem item)
        {
            Item = item;
        }

        public CostItem Item { get; }
    }

