//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Domain event for when a document is deleted.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Domain.Events;

    public class DocumentDeletedEvent : DomainEvent
    {
        public DocumentDeletedEvent(Document item)
        {
            Item = item;
        }

        public Document Item { get; }
    }

