//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Domain event for when a document is updated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Domain.Events;


    public class DocumentUpdatedEvent : DomainEvent
    {
        public DocumentUpdatedEvent(Document item)
        {
            Item = item;
        }

        public Document Item { get; }
    }

