//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Domain event for when a employee is deleted.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Domain.Events;

    public class EmployeeDeletedEvent : DomainEvent
    {
        public EmployeeDeletedEvent(Employee item)
        {
            Item = item;
        }

        public Employee Item { get; }
    }

