//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Domain event for when a employee is updated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Domain.Events;


    public class EmployeeUpdatedEvent : DomainEvent
    {
        public EmployeeUpdatedEvent(Employee item)
        {
            Item = item;
        }

        public Employee Item { get; }
    }

