//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Domain event for when a new pricingmodel is created.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Domain.Events;

    public class PricingModelCreatedEvent : DomainEvent
    {
        public PricingModelCreatedEvent(PricingModel item)
        {
            Item = item;
        }

        public PricingModel Item { get; }
    }

