//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Domain event for when a pricingmodel is updated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Domain.Events;


    public class PricingModelUpdatedEvent : DomainEvent
    {
        public PricingModelUpdatedEvent(PricingModel item)
        {
            Item = item;
        }

        public PricingModel Item { get; }
    }

