//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Domain event for when a new project is created.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Domain.Events;

    public class ProjectCreatedEvent : DomainEvent
    {
        public ProjectCreatedEvent(Project item)
        {
            Item = item;
        }

        public Project Item { get; }
    }

