//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Domain event for when a projecttask is updated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Domain.Events;


    public class ProjectTaskUpdatedEvent : DomainEvent
    {
        public ProjectTaskUpdatedEvent(ProjectTask item)
        {
            Item = item;
        }

        public ProjectTask Item { get; }
    }

