//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Domain event for when a purchaseorder is deleted.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Domain.Events;

    public class PurchaseOrderDeletedEvent : DomainEvent
    {
        public PurchaseOrderDeletedEvent(PurchaseOrder item)
        {
            Item = item;
        }

        public PurchaseOrder Item { get; }
    }

