//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Domain event for when a new quoteattachment is created.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Domain.Events;

    public class QuoteAttachmentCreatedEvent : DomainEvent
    {
        public QuoteAttachmentCreatedEvent(QuoteAttachment item)
        {
            Item = item;
        }

        public QuoteAttachment Item { get; }
    }

