//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Domain event for when a new quote is created.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Domain.Events;

    public class QuoteCreatedEvent : DomainEvent
    {
        public QuoteCreatedEvent(Quote item)
        {
            Item = item;
        }

        public Quote Item { get; }
    }

