//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Domain event for when a new quoteversion is created.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Domain.Events;

    public class QuoteVersionCreatedEvent : DomainEvent
    {
        public QuoteVersionCreatedEvent(QuoteVersion item)
        {
            Item = item;
        }

        public QuoteVersion Item { get; }
    }

