//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Domain event for when a quote is deleted.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Domain.Events;

    public class QuoteDeletedEvent : DomainEvent
    {
        public QuoteDeletedEvent(Quote item)
        {
            Item = item;
        }

        public Quote Item { get; }
    }

