//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Domain event for when a new service is created.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Domain.Events;

    public class ServiceCreatedEvent : DomainEvent
    {
        public ServiceCreatedEvent(Service item)
        {
            Item = item;
        }

        public Service Item { get; }
    }

