//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Domain event for when a new servicevariant is created.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Domain.Events;

    public class ServiceVariantCreatedEvent : DomainEvent
    {
        public ServiceVariantCreatedEvent(ServiceVariant item)
        {
            Item = item;
        }

        public ServiceVariant Item { get; }
    }

