//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Domain event for when a servicevariant is updated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Domain.Events;


    public class ServiceVariantUpdatedEvent : DomainEvent
    {
        public ServiceVariantUpdatedEvent(ServiceVariant item)
        {
            Item = item;
        }

        public ServiceVariant Item { get; }
    }

