//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Domain event for when a servicevariant is deleted.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Domain.Events;

    public class ServiceVariantDeletedEvent : DomainEvent
    {
        public ServiceVariantDeletedEvent(ServiceVariant item)
        {
            Item = item;
        }

        public ServiceVariant Item { get; }
    }

