//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Domain event for when a servicecategory is updated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Domain.Events;


    public class ServiceCategoryUpdatedEvent : DomainEvent
    {
        public ServiceCategoryUpdatedEvent(ServiceCategory item)
        {
            Item = item;
        }

        public ServiceCategory Item { get; }
    }

