//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Domain event for when a new servicecategory is created.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Domain.Events;

    public class ServiceCategoryCreatedEvent : DomainEvent
    {
        public ServiceCategoryCreatedEvent(ServiceCategory item)
        {
            Item = item;
        }

        public ServiceCategory Item { get; }
    }

