//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Domain event for when a new vendor is created.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Domain.Events;

    public class VendorCreatedEvent : DomainEvent
    {
        public VendorCreatedEvent(Vendor item)
        {
            Item = item;
        }

        public Vendor Item { get; }
    }

