//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under one or more agreements.
//     The .NET Foundation licenses this file to you under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-03-27
//     Last Modified: 2025-03-27
//     Description: 
//       This file defines the validation rules for the AddEditPurchaseInvoiceCommand 
//       used to add or edit PurchaseInvoice entities within the CleanArchitecture.Blazor 
//       application. It enforces maximum field lengths and required properties 
//       to maintain data integrity and validation standards.
//     
//     Documentation:
//       https://docs.cleanarchitectureblazor.com/features/purchaseinvoice
// </auto-generated>
//------------------------------------------------------------------------------

// Usage:
// This validator enforces constraints on the AddEditPurchaseInvoiceCommand, such as
// maximum field length for ...

namespace CleanArchitecture.Blazor.Application.Features.PurchaseInvoices.Commands.AddEdit;

public class AddEditPurchaseInvoiceCommandValidator : AbstractValidator<AddEditPurchaseInvoiceCommand>
{
    public AddEditPurchaseInvoiceCommandValidator()
    {
                RuleFor(v => v.SupplierId).NotNull(); 
    RuleFor(v => v.InvoiceNumber).MaximumLength(255); 
    RuleFor(v => v.InvoiceDate).NotNull(); 
    RuleFor(v => v.InvoiceType).MaximumLength(255); 
    RuleFor(v => v.TotalAmount).NotNull(); 
    RuleFor(v => v.VATAmount).NotNull(); 
    RuleFor(v => v.PaymentStatus).MaximumLength(255); 
    RuleFor(v => v.PaymentMethod).MaximumLength(255); 
    RuleFor(v => v.IBAN).MaximumLength(255); 
    RuleFor(v => v.SWIFT).MaximumLength(255); 
    RuleFor(v => v.Notes).MaximumLength(255); 

     }

}

