//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Handles QuoteVersionCreatedEvent: triggered when a new quoteversion is created.
// Extendable for additional actions (e.g., notifications, system updates).
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Application.Features.QuoteVersions.EventHandlers;

public class QuoteVersionCreatedEventHandler : INotificationHandler<QuoteVersionCreatedEvent>
{
        private readonly ILogger<QuoteVersionCreatedEventHandler> _logger;

        public QuoteVersionCreatedEventHandler(
            ILogger<QuoteVersionCreatedEventHandler> logger
            )
        {
            _logger = logger;
        }
        public Task Handle(QuoteVersionCreatedEvent notification, CancellationToken cancellationToken)
        {
            _logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
            return Task.CompletedTask;
        }
}
