//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Handles QuoteVersionUpdatedEvent: triggered when a quoteversion is updated.
// Extendable for additional actions (e.g., notifications, system updates).
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Application.Features.QuoteVersions.EventHandlers;

    public class QuoteVersionUpdatedEventHandler : INotificationHandler<QuoteVersionUpdatedEvent>
    {
        private readonly ILogger<QuoteVersionUpdatedEventHandler> _logger;

        public QuoteVersionUpdatedEventHandler(
            ILogger<QuoteVersionUpdatedEventHandler> logger
            )
        {
            _logger = logger;
        }
        public Task Handle(QuoteVersionUpdatedEvent notification, CancellationToken cancellationToken)
        {
            _logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
            return Task.CompletedTask;
        }
    }
