//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Handles QuoteVersionDeletedEvent: triggered when a quoteversion is deleted.
// Extendable for additional actions (e.g., notifications, system updates).
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Application.Features.QuoteVersions.EventHandlers;

    public class QuoteVersionDeletedEventHandler : INotificationHandler<QuoteVersionDeletedEvent>
    {
        private readonly ILogger<QuoteVersionDeletedEventHandler> _logger;

        public QuoteVersionDeletedEventHandler(
            ILogger<QuoteVersionDeletedEventHandler> logger
            )
        {
            _logger = logger;
        }
        public Task Handle(QuoteVersionDeletedEvent notification, CancellationToken cancellationToken)
        {
            _logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
            return Task.CompletedTask;
        }
    }
