//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Handles ServiceVariantDeletedEvent: triggered when a servicevariant is deleted.
// Extendable for additional actions (e.g., notifications, system updates).
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Application.Features.ServiceVariants.EventHandlers;

    public class ServiceVariantDeletedEventHandler : INotificationHandler<ServiceVariantDeletedEvent>
    {
        private readonly ILogger<ServiceVariantDeletedEventHandler> _logger;

        public ServiceVariantDeletedEventHandler(
            ILogger<ServiceVariantDeletedEventHandler> logger
            )
        {
            _logger = logger;
        }
        public Task Handle(ServiceVariantDeletedEvent notification, CancellationToken cancellationToken)
        {
            _logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
            return Task.CompletedTask;
        }
    }
