//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-09-24
//     Last Modified: 2025-09-24
//     Description: 
//       Defines a query to retrieve a quote by its ID. The result is cached 
//       to optimize performance for repeated retrievals of the same quote.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Quotes.DTOs;
using CleanArchitecture.Blazor.Application.Features.Quotes.Caching;
using CleanArchitecture.Blazor.Application.Features.Quotes.Specifications;

namespace CleanArchitecture.Blazor.Application.Features.Quotes.Queries.GetById;

public class GetQuoteByIdQuery : ICacheableRequest<Result<QuoteDto>>
{
   public required int Id { get; set; }
   public string CacheKey => QuoteCacheKey.GetByIdCacheKey($"{Id}");
   public IEnumerable<string>? Tags => QuoteCacheKey.Tags;
}

public class GetQuoteByIdQueryHandler :
     IRequestHandler<GetQuoteByIdQuery, Result<QuoteDto>>
{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    private readonly IMapper _mapper;
    public GetQuoteByIdQueryHandler(
        IMapper mapper,
        IApplicationDbContextFactory dbContextFactory)
    {
        _mapper = mapper;
        _dbContextFactory = dbContextFactory;
    }

    public async Task<Result<QuoteDto>> Handle(GetQuoteByIdQuery request, CancellationToken cancellationToken)
    {
        await using var _context = await _dbContextFactory.CreateAsync(cancellationToken);
        var data = await _context.Quotes.ApplySpecification(new QuoteByIdSpecification(request.Id))
                                                .ProjectTo<QuoteDto>(_mapper.ConfigurationProvider)
                                                .FirstAsync(cancellationToken) ?? throw new NotFoundException($"Quote with id: [{request.Id}] not found.");
        return await Result<QuoteDto>.SuccessAsync(data);
    }
}
