////------------------------------------------------------------------------------
//// <auto-generated>
//// CleanArchitecture.Blazor - MIT Licensed.
//// Author: neozhu
//// Created/Modified: 2025-09-24
//// Import command & template for quotes.
//// Validates Excel data, prevents duplicates, and provides a template for bulk entry.
//// Docs: https://docs.cleanarchitectureblazor.com/features/quote
//// </auto-generated>
////------------------------------------------------------------------------------
//#nullable enable
//#nullable disable warnings

//using CleanArchitecture.Blazor.Application.Features.Quotes.DTOs;
//using CleanArchitecture.Blazor.Application.Features.Quotes.Caching;

//namespace CleanArchitecture.Blazor.Application.Features.Quotes.Commands.Import;

//    public class ImportQuotesCommand: ICacheInvalidatorRequest<Result<int>>
//    {
//        public string FileName { get; set; }
//        public byte[] Data { get; set; }
//        public string CacheKey => QuoteCacheKey.GetAllCacheKey;
//        public IEnumerable<string>? Tags => QuoteCacheKey.Tags;
//        public ImportQuotesCommand(string fileName,byte[] data)
//        {
//           FileName = fileName;
//           Data = data;
//        }
//    }
//    public record class CreateQuotesTemplateCommand : IRequest<Result<byte[]>>
//    {
 
//    }

//    public class ImportQuotesCommandHandler : 
//                 IRequestHandler<CreateQuotesTemplateCommand, Result<byte[]>>,
//                 IRequestHandler<ImportQuotesCommand, Result<int>>
//    {
//        private readonly IApplicationDbContext _context;
//        private readonly IStringLocalizer<ImportQuotesCommandHandler> _localizer;
//        private readonly IExcelService _excelService;
//        private readonly QuoteDto _dto = new();
//        private readonly IMapper _mapper;
//        public ImportQuotesCommandHandler(
//            IApplicationDbContext context,
//            IMapper mapper,
//            IExcelService excelService,
//            IStringLocalizer<ImportQuotesCommandHandler> localizer)
//        {
//            _context = context;
//            _localizer = localizer;
//            _excelService = excelService;
//            _mapper = mapper;
//        }
//        #nullable disable warnings
//        public async Task<Result<int>> Handle(ImportQuotesCommand request, CancellationToken cancellationToken)
//        {

//           var result = await _excelService.ImportAsync(request.Data, mappers: new Dictionary<string, Func<DataRow, QuoteDto, object?>>
//            {
//                                { _localizer[_dto.GetMemberDescription(x=>x.CompanyId)], (row, item) => item.CompanyId =Convert.ToInt32(row[_localizer[_dto.GetMemberDescription(x=>x.CompanyId)]]) }, 
//                { _localizer[_dto.GetMemberDescription(x=>x.Title)], (row, item) => item.Title = row[_localizer[_dto.GetMemberDescription(x=>x.Title)]].ToString() }, 
//                { _localizer[_dto.GetMemberDescription(x=>x.OwnerId)], (row, item) => item.OwnerId =Convert.ToInt32(row[_localizer[_dto.GetMemberDescription(x=>x.OwnerId)]]) }, 
//                { _localizer[_dto.GetMemberDescription(x=>x.Status)], (row, item) => item.Status = Enum.Parse<QuoteStatus>(row[_localizer[_dto.GetMemberDescription(x=>x.Status)]].ToString()) }, 
//                { _localizer[_dto.GetMemberDescription(x=>x.ValidUntil)], (row, item) => item.ValidUntil =DateTime.Parse(row[_localizer[_dto.GetMemberDescription(x=>x.ValidUntil)]].ToString()) }, 
//                { _localizer[_dto.GetMemberDescription(x=>x.Currency)], (row, item) => item.Currency = row[_localizer[_dto.GetMemberDescription(x=>x.Currency)]].ToString() }, 
//                { _localizer[_dto.GetMemberDescription(x=>x.TotalAmount)], (row, item) => item.TotalAmount =Convert.ToDecimal(row[_localizer[_dto.GetMemberDescription(x=>x.TotalAmount)]]) }, 
//                { _localizer[_dto.GetMemberDescription(x=>x.MarginPct)], (row, item) => item.MarginPct =Convert.ToDecimal(row[_localizer[_dto.GetMemberDescription(x=>x.MarginPct)]]) }, 

//            }, _localizer[_dto.GetClassDescription()]);
//            if (result.Succeeded && result.Data is not null)
//            {
//                foreach (var dto in result.Data)
//                {
//                    var exists = await _context.Quotes.AnyAsync(x => x.Name == dto.Name, cancellationToken);
//                    if (!exists)
//                    {
//                        var item = _mapper.Map<Quote>(dto);
//                        // add create domain events if this entity implement the IHasDomainEvent interface
//				        // item.AddDomainEvent(new QuoteCreatedEvent(item));
//                        await _context.Quotes.AddAsync(item, cancellationToken);
//                    }
//                 }
//                 await _context.SaveChangesAsync(cancellationToken);
//                 return await Result<int>.SuccessAsync(result.Data.Count());
//           }
//           else
//           {
//               return await Result<int>.FailureAsync(result.Errors);
//           }
//        }
//        public async Task<Result<byte[]>> Handle(CreateQuotesTemplateCommand request, CancellationToken cancellationToken)
//        {
//            // TODO: Implement ImportQuotesCommandHandler method 
//            var fields = new string[] {
//                   // TODO: Define the fields that should be generate in the template, for example:
//                   _localizer[_dto.GetMemberDescription(x=>x.CompanyId)], 
//_localizer[_dto.GetMemberDescription(x=>x.Title)], 
//_localizer[_dto.GetMemberDescription(x=>x.OwnerId)], 
//_localizer[_dto.GetMemberDescription(x=>x.ValidUntil)], 
//_localizer[_dto.GetMemberDescription(x=>x.Currency)], 
//_localizer[_dto.GetMemberDescription(x=>x.TotalAmount)], 
//_localizer[_dto.GetMemberDescription(x=>x.MarginPct)], 

//                };
//            var result = await _excelService.CreateTemplateAsync(fields, _localizer[_dto.GetClassDescription()]);
//            return await Result<byte[]>.SuccessAsync(result);
//        }
//    }

