//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Handles PricingModelCreatedEvent: triggered when a new pricingmodel is created.
// Extendable for additional actions (e.g., notifications, system updates).
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Application.Features.PricingModels.EventHandlers;

public class PricingModelCreatedEventHandler : INotificationHandler<PricingModelCreatedEvent>
{
        private readonly ILogger<PricingModelCreatedEventHandler> _logger;

        public PricingModelCreatedEventHandler(
            ILogger<PricingModelCreatedEventHandler> logger
            )
        {
            _logger = logger;
        }
        public Task Handle(PricingModelCreatedEvent notification, CancellationToken cancellationToken)
        {
            _logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
            return Task.CompletedTask;
        }
}
