//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Validator for AddEditEquipmentItemCommand: enforces field length and required property rules for EquipmentItem entities.
// Docs: https://docs.cleanarchitectureblazor.com/features/equipmentitem
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings


namespace CleanArchitecture.Blazor.Application.Features.EquipmentItems.Commands.AddEdit;

public class AddEditEquipmentItemCommandValidator : AbstractValidator<AddEditEquipmentItemCommand>
{
    public AddEditEquipmentItemCommandValidator()
    {
                RuleFor(v => v.Name).MaximumLength(50).NotEmpty(); 
    RuleFor(v => v.Category).MaximumLength(255); 

     }

}

