//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-09-24
//     Last Modified: 2025-09-24
//     Description: 
//       Defines a query to retrieve all costitems from the database. The result 
//       is cached to improve performance and reduce database load for repeated 
//       queries.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.CostItems.DTOs;
using CleanArchitecture.Blazor.Application.Features.CostItems.Caching;

namespace CleanArchitecture.Blazor.Application.Features.CostItems.Queries.GetAll;

public class GetAllCostItemsQuery : ICacheableRequest<IEnumerable<CostItemDto>>
{
   public string CacheKey => CostItemCacheKey.GetAllCacheKey;
   public IEnumerable<string>? Tags => CostItemCacheKey.Tags;
}

public class GetAllCostItemsQueryHandler :
     IRequestHandler<GetAllCostItemsQuery, IEnumerable<CostItemDto>>
{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    private readonly IMapper _mapper;
    public GetAllCostItemsQueryHandler(
        IMapper mapper,
        IApplicationDbContextFactory dbContextFactory)
    {
        _mapper = mapper;
        _dbContextFactory = dbContextFactory;
    }

    public async Task<IEnumerable<CostItemDto>> Handle(GetAllCostItemsQuery request, CancellationToken cancellationToken)
    {
        await using var _context = await _dbContextFactory.CreateAsync(cancellationToken);
        var data = await _context.CostItems.ProjectTo<CostItemDto>(_mapper.ConfigurationProvider)
                                                .AsNoTracking()
                                                .ToListAsync(cancellationToken);
        return data;
    }
}


