//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Command and handler for deleting Employee entities.
// Implements cache invalidation and triggers domain events.
// Docs: https://docs.cleanarchitectureblazor.com/features/employee
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Employees.Caching;

namespace CleanArchitecture.Blazor.Application.Features.Employees.Commands.Delete;

public class DeleteEmployeeCommand:  ICacheInvalidatorRequest<Result>
{
  public int[] Id {  get; }
  public string CacheKey => EmployeeCacheKey.GetAllCacheKey;
  public IEnumerable<string>? Tags => EmployeeCacheKey.Tags;
  public DeleteEmployeeCommand(int[] id)
  {
    Id = id;
  }
}

public class DeleteEmployeeCommandHandler : 
             IRequestHandler<DeleteEmployeeCommand, Result>

{
    private readonly IApplicationDbContext _context;
    public DeleteEmployeeCommandHandler(
        IApplicationDbContext context)
    {
        _context = context;
    }
    public async Task<Result> Handle(DeleteEmployeeCommand request, CancellationToken cancellationToken)
    {
        var items = await _context.Employees.Where(x=>request.Id.Contains(x.Id)).ToListAsync(cancellationToken);
        foreach (var item in items)
        {
		    // raise a delete domain event
			item.AddDomainEvent(new EmployeeDeletedEvent(item));
            _context.Employees.Remove(item);
        }
        await _context.SaveChangesAsync(cancellationToken);
        return await Result.SuccessAsync();
    }

}

