////------------------------------------------------------------------------------
//// <auto-generated>
//// CleanArchitecture.Blazor - MIT Licensed.
//// Author: neozhu
//// Created/Modified: 2025-09-24
//// Import command & template for employees.
//// Validates Excel data, prevents duplicates, and provides a template for bulk entry.
//// Docs: https://docs.cleanarchitectureblazor.com/features/employee
//// </auto-generated>
////------------------------------------------------------------------------------
//#nullable enable
//#nullable disable warnings

//using CleanArchitecture.Blazor.Application.Features.Employees.DTOs;
//using CleanArchitecture.Blazor.Application.Features.Employees.Caching;

//namespace CleanArchitecture.Blazor.Application.Features.Employees.Commands.Import;

//    public class ImportEmployeesCommand: ICacheInvalidatorRequest<Result<int>>
//    {
//        public string FileName { get; set; }
//        public byte[] Data { get; set; }
//        public string CacheKey => EmployeeCacheKey.GetAllCacheKey;
//        public IEnumerable<string>? Tags => EmployeeCacheKey.Tags;
//        public ImportEmployeesCommand(string fileName,byte[] data)
//        {
//           FileName = fileName;
//           Data = data;
//        }
//    }
//    public record class CreateEmployeesTemplateCommand : IRequest<Result<byte[]>>
//    {
 
//    }

//    public class ImportEmployeesCommandHandler : 
//                 IRequestHandler<CreateEmployeesTemplateCommand, Result<byte[]>>,
//                 IRequestHandler<ImportEmployeesCommand, Result<int>>
//    {
//        private readonly IApplicationDbContextFactory _dbContextFactory;;
//        private readonly IStringLocalizer<ImportEmployeesCommandHandler> _localizer;
//        private readonly IExcelService _excelService;
//        private readonly EmployeeDto _dto = new();
//        private readonly IMapper _mapper;
//        public ImportEmployeesCommandHandler(
//            IApplicationDbContext context,
//            IMapper mapper,
//            IExcelService excelService,
//            IStringLocalizer<ImportEmployeesCommandHandler> localizer)
//        {
//            _context = context;
//            _localizer = localizer;
//            _excelService = excelService;
//            _mapper = mapper;
//        }
//        #nullable disable warnings
//        public async Task<Result<int>> Handle(ImportEmployeesCommand request, CancellationToken cancellationToken)
//        {

//           var result = await _excelService.ImportAsync(request.Data, mappers: new Dictionary<string, Func<DataRow, EmployeeDto, object?>>
//            {
//                                { _localizer[_dto.GetMemberDescription(x=>x.FirstName)], (row, item) => item.FirstName = row[_localizer[_dto.GetMemberDescription(x=>x.FirstName)]].ToString() }, 
//                { _localizer[_dto.GetMemberDescription(x=>x.LastName)], (row, item) => item.LastName = row[_localizer[_dto.GetMemberDescription(x=>x.LastName)]].ToString() }, 
//                { _localizer[_dto.GetMemberDescription(x=>x.Email)], (row, item) => item.Email = row[_localizer[_dto.GetMemberDescription(x=>x.Email)]].ToString() }, 
//                { _localizer[_dto.GetMemberDescription(x=>x.Phone)], (row, item) => item.Phone = row[_localizer[_dto.GetMemberDescription(x=>x.Phone)]].ToString() }, 
//                { _localizer[_dto.GetMemberDescription(x=>x.Position)], (row, item) => item.Position = row[_localizer[_dto.GetMemberDescription(x=>x.Position)]].ToString() }, 

//            }, _localizer[_dto.GetClassDescription()]);
//            if (result.Succeeded && result.Data is not null)
//            {
//                foreach (var dto in result.Data)
//                {
//                    var exists = await _context.Employees.AnyAsync(x => x.Name == dto.Name, cancellationToken);
//                    if (!exists)
//                    {
//                        var item = _mapper.Map<Employee>(dto);
//                        // add create domain events if this entity implement the IHasDomainEvent interface
//				        // item.AddDomainEvent(new EmployeeCreatedEvent(item));
//                        await _context.Employees.AddAsync(item, cancellationToken);
//                    }
//                 }
//                 await _context.SaveChangesAsync(cancellationToken);
//                 return await Result<int>.SuccessAsync(result.Data.Count());
//           }
//           else
//           {
//               return await Result<int>.FailureAsync(result.Errors);
//           }
//        }
//        public async Task<Result<byte[]>> Handle(CreateEmployeesTemplateCommand request, CancellationToken cancellationToken)
//        {
//            // TODO: Implement ImportEmployeesCommandHandler method 
//            var fields = new string[] {
//                   // TODO: Define the fields that should be generate in the template, for example:
//                   _localizer[_dto.GetMemberDescription(x=>x.FirstName)], 
//_localizer[_dto.GetMemberDescription(x=>x.LastName)], 
//_localizer[_dto.GetMemberDescription(x=>x.Email)], 
//_localizer[_dto.GetMemberDescription(x=>x.Phone)], 
//_localizer[_dto.GetMemberDescription(x=>x.Position)], 

//                };
//            var result = await _excelService.CreateTemplateAsync(fields, _localizer[_dto.GetClassDescription()]);
//            return await Result<byte[]>.SuccessAsync(result);
//        }
//    }

