//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-09-24
//     Last Modified: 2025-09-24
//     Description: 
//       Defines a query to retrieve all quoteapprovals from the database. The result 
//       is cached to improve performance and reduce database load for repeated 
//       queries.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.QuoteApprovals.DTOs;
using CleanArchitecture.Blazor.Application.Features.QuoteApprovals.Caching;

namespace CleanArchitecture.Blazor.Application.Features.QuoteApprovals.Queries.GetAll;

public class GetAllQuoteApprovalsQuery : ICacheableRequest<IEnumerable<QuoteApprovalDto>>
{
   public string CacheKey => QuoteApprovalCacheKey.GetAllCacheKey;
   public IEnumerable<string>? Tags => QuoteApprovalCacheKey.Tags;
}

public class GetAllQuoteApprovalsQueryHandler :
     IRequestHandler<GetAllQuoteApprovalsQuery, IEnumerable<QuoteApprovalDto>>
{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    private readonly IMapper _mapper;
    public GetAllQuoteApprovalsQueryHandler(
        IMapper mapper,
        IApplicationDbContextFactory dbContextFactory)
    {
        _mapper = mapper;
        _dbContextFactory = dbContextFactory;
    }

    public async Task<IEnumerable<QuoteApprovalDto>> Handle(GetAllQuoteApprovalsQuery request, CancellationToken cancellationToken)
    {
        await using var _context = await _dbContextFactory.CreateAsync(cancellationToken);
        var data = await _context.QuoteApprovals.ProjectTo<QuoteApprovalDto>(_mapper.ConfigurationProvider)
                                                .AsNoTracking()
                                                .ToListAsync(cancellationToken);
        return data;
    }
}


