//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-09-23
//     Last Modified: 2025-09-23
//     Description: 
//       Defines a specification for filtering a Venue entity by its ID.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.Venues.Specifications;
#nullable disable warnings
/// <summary>
/// Specification class for filtering Venues by their ID.
/// </summary>
public class VenueByIdSpecification : Specification<Venue>
{
    public VenueByIdSpecification(int id)
    {
       Query.Where(q => q.Id == id);
    }
}