//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// ServiceCategoryDto: transfers servicecategory data between layers.
// Docs: https://docs.cleanarchitectureblazor.com/features/servicecategory
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings


namespace CleanArchitecture.Blazor.Application.Features.ServiceCategories.DTOs;

[Description("ServiceCategories")]
public class ServiceCategoryDto
{
    [Description("Id")]
    public int Id { get; set; }
        [Description("Name")]
    public string Name {get;set;} 
    [Description("Description")]
    public string? Description {get;set;} 
    [Description("Services")]
    public List<ServiceDto>? Services {get;set;} 


    private class Mapping : Profile
    {
        public Mapping()
        {
            CreateMap<ServiceCategory, ServiceCategoryDto>(MemberList.None);
            CreateMap<ServiceCategoryDto, ServiceCategory>(MemberList.None)

            .ForMember(dest => dest.DomainEvents, opt => opt.Ignore());
        }
    }
}

