//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-23
// Validator for AddEditAssignmentCommand: enforces field length and required property rules for Assignment entities.
// Docs: https://docs.cleanarchitectureblazor.com/features/assignment
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings


namespace CleanArchitecture.Blazor.Application.Features.Assignments.Commands.AddEdit;

public class AddEditAssignmentCommandValidator : AbstractValidator<AddEditAssignmentCommand>
{
    public AddEditAssignmentCommandValidator()
    {
                RuleFor(v => v.ProjectId).NotNull(); 
    RuleFor(v => v.EmployeeId).NotNull(); 
    RuleFor(v => v.Role).MaximumLength(255); 

     }

}

