//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Handles ServiceDeletedEvent: triggered when a service is deleted.
// Extendable for additional actions (e.g., notifications, system updates).
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Application.Features.Services.EventHandlers;

    public class ServiceDeletedEventHandler : INotificationHandler<ServiceDeletedEvent>
    {
        private readonly ILogger<ServiceDeletedEventHandler> _logger;

        public ServiceDeletedEventHandler(
            ILogger<ServiceDeletedEventHandler> logger
            )
        {
            _logger = logger;
        }
        public Task Handle(ServiceDeletedEvent notification, CancellationToken cancellationToken)
        {
            _logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
            return Task.CompletedTask;
        }
    }
