//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Handles ServiceCreatedEvent: triggered when a new service is created.
// Extendable for additional actions (e.g., notifications, system updates).
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Application.Features.Services.EventHandlers;

public class ServiceCreatedEventHandler : INotificationHandler<ServiceCreatedEvent>
{
        private readonly ILogger<ServiceCreatedEventHandler> _logger;

        public ServiceCreatedEventHandler(
            ILogger<ServiceCreatedEventHandler> logger
            )
        {
            _logger = logger;
        }
        public Task Handle(ServiceCreatedEvent notification, CancellationToken cancellationToken)
        {
            _logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
            return Task.CompletedTask;
        }
}
