//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Validator for AddEditServiceCommand: enforces field length and required property rules for Service entities.
// Docs: https://docs.cleanarchitectureblazor.com/features/service
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings


namespace CleanArchitecture.Blazor.Application.Features.Services.Commands.AddEdit;

public class AddEditServiceCommandValidator : AbstractValidator<AddEditServiceCommand>
{
    public AddEditServiceCommandValidator()
    {
                RuleFor(v => v.ServiceCategoryId).NotNull(); 
    RuleFor(v => v.Name).MaximumLength(50).NotEmpty(); 
    RuleFor(v => v.Description).MaximumLength(255); 
    RuleFor(v => v.DefaultPricingModel).NotNull(); 

     }

}

