//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-23
// Handles AssignmentDeletedEvent: triggered when a assignment is deleted.
// Extendable for additional actions (e.g., notifications, system updates).
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Application.Features.Assignments.EventHandlers;

    public class AssignmentDeletedEventHandler : INotificationHandler<AssignmentDeletedEvent>
    {
        private readonly ILogger<AssignmentDeletedEventHandler> _logger;

        public AssignmentDeletedEventHandler(
            ILogger<AssignmentDeletedEventHandler> logger
            )
        {
            _logger = logger;
        }
        public Task Handle(AssignmentDeletedEvent notification, CancellationToken cancellationToken)
        {
            _logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
            return Task.CompletedTask;
        }
    }
