//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-23
// Handles AssignmentUpdatedEvent: triggered when a assignment is updated.
// Extendable for additional actions (e.g., notifications, system updates).
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Application.Features.Assignments.EventHandlers;

    public class AssignmentUpdatedEventHandler : INotificationHandler<AssignmentUpdatedEvent>
    {
        private readonly ILogger<AssignmentUpdatedEventHandler> _logger;

        public AssignmentUpdatedEventHandler(
            ILogger<AssignmentUpdatedEventHandler> logger
            )
        {
            _logger = logger;
        }
        public Task Handle(AssignmentUpdatedEvent notification, CancellationToken cancellationToken)
        {
            _logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
            return Task.CompletedTask;
        }
    }
