//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-23
// Handles AssignmentCreatedEvent: triggered when a new assignment is created.
// Extendable for additional actions (e.g., notifications, system updates).
// </auto-generated>
//------------------------------------------------------------------------------


namespace CleanArchitecture.Blazor.Application.Features.Assignments.EventHandlers;

public class AssignmentCreatedEventHandler : INotificationHandler<AssignmentCreatedEvent>
{
        private readonly ILogger<AssignmentCreatedEventHandler> _logger;

        public AssignmentCreatedEventHandler(
            ILogger<AssignmentCreatedEventHandler> logger
            )
        {
            _logger = logger;
        }
        public Task Handle(AssignmentCreatedEvent notification, CancellationToken cancellationToken)
        {
            _logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
            return Task.CompletedTask;
        }
}
