//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under one or more agreements.
//     The .NET Foundation licenses this file to you under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-02-04
//     Last Modified: 2025-02-04
//     Description: 
//       This file defines the UpdateStepCommand and its handler for updating 
//       an existing Step entity within the CleanArchitecture.Blazor application. 
//       It includes caching invalidation logic to maintain data consistency and 
//       raises a domain event upon successful update to notify other parts of the system.
//     
//     Documentation:
//       https://docs.cleanarchitectureblazor.com/features/step
// </auto-generated>
//------------------------------------------------------------------------------

// Usage:
// Use `UpdateStepCommand` to update an existing step entity in the system. 
// The handler ensures that if the entity is found, the changes are applied and 
// the necessary domain event (`StepUpdatedEvent`) is raised. Caching is also 
// invalidated to keep the step list consistent.

using CleanArchitecture.Blazor.Application.Features.Invoices.DTOs;
using CleanArchitecture.Blazor.Application.Features.Steps.Caching;
using CleanArchitecture.Blazor.Application.Features.Steps.Mappers;

namespace CleanArchitecture.Blazor.Application.Features.Steps.Commands.Update;

public class UpdateStepCommand: ICacheInvalidatorRequest<Result<int>>
{
      [Description("Id")]
      public int Id { get; set; }
            [Description("Name")]
    public string Name {get;set;} 
    [Description("Invoice id")]
    public int? InvoiceId {get;set;} 
    [Description("Is completed")]
    public bool IsCompleted {get;set;} 
    [Description("Step order")]
    public int StepOrder {get;set;} 
    //[Description("Comments")]
    //public List<CommentDtoDto>? Comments {get;set;} 
    [Description("Invoice")]
    public InvoiceDto Invoice {get;set;} 

      public string CacheKey => StepCacheKey.GetAllCacheKey;
      public IEnumerable<string>? Tags => StepCacheKey.Tags;

}

public class UpdateStepCommandHandler : IRequestHandler<UpdateStepCommand, Result<int>>
{
    private readonly IApplicationDbContext _context;
    public UpdateStepCommandHandler(
        IApplicationDbContext context)
    {
        _context = context;
    }
    public async Task<Result<int>> Handle(UpdateStepCommand request, CancellationToken cancellationToken)
    {

       var item = await _context.Steps.FindAsync(request.Id, cancellationToken);
       if (item == null)
       {
           return await Result<int>.FailureAsync($"Step with id: [{request.Id}] not found.");
       }
       StepMapper.ApplyChangesFrom(request, item);
	    // raise a update domain event
	   //item.AddDomainEvent(new StepUpdatedEvent(item));
       await _context.SaveChangesAsync(cancellationToken);
       return await Result<int>.SuccessAsync(item.Id);
    }
}

