//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Validator for CreateDocumentCommand: enforces max lengths and required fields for Document entities.
// Docs: https://docs.cleanarchitectureblazor.com/features/document
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.Documents.Commands.Create;

public class CreateDocumentCommandValidator : AbstractValidator<CreateDocumentCommand>
{
        public CreateDocumentCommandValidator()
        {
                RuleFor(v => v.Title).MaximumLength(255); 
    RuleFor(v => v.Description).MaximumLength(255); 
    RuleFor(v => v.Status).NotNull(); 
    RuleFor(v => v.Content).MaximumLength(255); 
    RuleFor(v => v.URL).MaximumLength(255); 
    RuleFor(v => v.DocumentType).NotNull(); 
    RuleFor(v => v.TenantId).MaximumLength(255); 

        }
       
}

