//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under one or more agreements.
//     The .NET Foundation licenses this file to you under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-03-27
//     Last Modified: 2025-03-27
//     Description: 
//       This file defines the UpdatePurchaseInvoiceCommand and its handler for updating 
//       an existing PurchaseInvoice entity within the CleanArchitecture.Blazor application. 
//       It includes caching invalidation logic to maintain data consistency and 
//       raises a domain event upon successful update to notify other parts of the system.
//     
//     Documentation:
//       https://docs.cleanarchitectureblazor.com/features/purchaseinvoice
// </auto-generated>
//------------------------------------------------------------------------------

// Usage:
// Use `UpdatePurchaseInvoiceCommand` to update an existing purchaseinvoice entity in the system. 
// The handler ensures that if the entity is found, the changes are applied and 
// the necessary domain event (`PurchaseInvoiceUpdatedEvent`) is raised. Caching is also 
// invalidated to keep the purchaseinvoice list consistent.

using CleanArchitecture.Blazor.Application.Features.PurchaseInvoices.Caching;
using CleanArchitecture.Blazor.Application.Features.PurchaseInvoices.Mappers;
using CleanArchitecture.Blazor.Application.Features.PurchaseItems.DTOs;
using CleanArchitecture.Blazor.Application.Features.Suppliers.DTOs;

namespace CleanArchitecture.Blazor.Application.Features.PurchaseInvoices.Commands.Update;

public class UpdatePurchaseInvoiceCommand: ICacheInvalidatorRequest<Result<int>>
{
      [Description("Id")]
      public int Id { get; set; }
            [Description("Supplier id")]
    public int SupplierId {get;set;} 
    [Description("Invoice number")]
    public string? InvoiceNumber {get;set;} 
    [Description("Invoice date")]
    public DateTime? InvoiceDate {get;set;} 
    [Description("Invoice type")]
    public string? InvoiceType {get;set;} 
    [Description("Total amount")]
    public decimal TotalAmount {get;set;} 
    [Description("Vat amount")]
    public decimal VATAmount {get;set;} 
    [Description("Payment status")]
    public string? PaymentStatus {get;set;} 
    [Description("Payment method")]
    public string? PaymentMethod {get;set;} 
    [Description("Iban")]
    public string? IBAN {get;set;} 
    [Description("Swift")]
    public string? SWIFT {get;set;} 
    [Description("Notes")]
    public string? Notes {get;set;} 
    [Description("Supplier")]
    public SupplierDto Supplier {get;set;} 
    [Description("Items")]
    public List<PurchaseItemDto>? Items {get;set;} 

      public string CacheKey => PurchaseInvoiceCacheKey.GetAllCacheKey;
      public IEnumerable<string>? Tags => PurchaseInvoiceCacheKey.Tags;

}

public class UpdatePurchaseInvoiceCommandHandler : IRequestHandler<UpdatePurchaseInvoiceCommand, Result<int>>
{
    private readonly IApplicationDbContext _context;
    public UpdatePurchaseInvoiceCommandHandler(
        IApplicationDbContext context)
    {
        _context = context;
    }
    public async Task<Result<int>> Handle(UpdatePurchaseInvoiceCommand request, CancellationToken cancellationToken)
    {

       var item = await _context.PurchaseInvoices.FindAsync(request.Id, cancellationToken);
       if (item == null)
       {
           return await Result<int>.FailureAsync($"PurchaseInvoice with id: [{request.Id}] not found.");
       }
       PurchaseInvoiceMapper.ApplyChangesFrom(request, item);
	    // raise a update domain event
	   //item.AddDomainEvent(new PurchaseInvoiceUpdatedEvent(item));
       await _context.SaveChangesAsync(cancellationToken);
       return await Result<int>.SuccessAsync(item.Id);
    }
}

