//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Command for adding/editing a vendor entity with validation, mapping,
// domain events, and cache invalidation.
// Documentation: https://docs.cleanarchitectureblazor.com/features/vendor
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings


using CleanArchitecture.Blazor.Application.Features.Vendors.Caching;
using CleanArchitecture.Blazor.Application.Features.Vendors.DTOs;
namespace CleanArchitecture.Blazor.Application.Features.Vendors.Commands.AddEdit;

public class AddEditVendorCommand: ICacheInvalidatorRequest<Result<int>>
{
      [Description("Id")]
      public int Id { get; set; }
          [Description("Company id")]
    public int CompanyId {get;set;} 
    [Description("Company")]
    public CompanyDto? Company {get;set;} 
    [Description("Service category id")]
    public int? ServiceCategoryId {get;set;} 
    [Description("Service category")]
    public ServiceCategoryDto? ServiceCategory {get;set;} 
    [Description("Terms")]
    public string? Terms {get;set;} 


      public string CacheKey => VendorCacheKey.GetAllCacheKey;
      public IEnumerable<string>? Tags => VendorCacheKey.Tags;
    private class Mapping : Profile
    {
        public Mapping()
        {
            CreateMap<VendorDto, AddEditVendorCommand>(MemberList.None);
            CreateMap<AddEditVendorCommand, Vendor>(MemberList.None);
        }
    }
}

public class AddEditVendorCommandHandler : IRequestHandler<AddEditVendorCommand, Result<int>>
{
    private readonly IMapper _mapper;
    private readonly IApplicationDbContext _context;
    public AddEditVendorCommandHandler(
        IMapper mapper,
        IApplicationDbContext context)
    {
        _mapper = mapper;
        _context = context;
    }
    public async Task<Result<int>> Handle(AddEditVendorCommand request, CancellationToken cancellationToken)
    {
        if (request.Id > 0)
        {
            var item = await _context.Vendors.FindAsync(request.Id, cancellationToken);
            if (item == null)
            {
                return await Result<int>.FailureAsync($"Vendor with id: [{request.Id}] not found.");
            }
            item = _mapper.Map(request, item);
			// raise a update domain event
			item.AddDomainEvent(new VendorUpdatedEvent(item));
            await _context.SaveChangesAsync(cancellationToken);
            return await Result<int>.SuccessAsync(item.Id);
        }
        else
        {
            var item = _mapper.Map<Vendor>(request);
            // raise a create domain event
			item.AddDomainEvent(new VendorCreatedEvent(item));
            _context.Vendors.Add(item);
            await _context.SaveChangesAsync(cancellationToken);
            return await Result<int>.SuccessAsync(item.Id);
        }
       
    }
}

