//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Command and handler for deleting PricingModel entities.
// Implements cache invalidation and triggers domain events.
// Docs: https://docs.cleanarchitectureblazor.com/features/pricingmodel
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.PricingModels.Caching;

namespace CleanArchitecture.Blazor.Application.Features.PricingModels.Commands.Delete;

public class DeletePricingModelCommand:  ICacheInvalidatorRequest<Result>
{
  public int[] Id {  get; }
  public string CacheKey => PricingModelCacheKey.GetAllCacheKey;
  public IEnumerable<string>? Tags => PricingModelCacheKey.Tags;
  public DeletePricingModelCommand(int[] id)
  {
    Id = id;
  }
}

public class DeletePricingModelCommandHandler : 
             IRequestHandler<DeletePricingModelCommand, Result>

{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    public DeletePricingModelCommandHandler(
        IApplicationDbContextFactory dbContextFactory)
    {
        _dbContextFactory = dbContextFactory;
    }
    public async Task<Result> Handle(DeletePricingModelCommand request, CancellationToken cancellationToken)
    {
        await using var _context = await _dbContextFactory.CreateAsync(cancellationToken);
        var items = await _context.PricingModels.Where(x=>request.Id.Contains(x.Id)).ToListAsync(cancellationToken);
        foreach (var item in items)
        {
		    // raise a delete domain event
			item.AddDomainEvent(new PricingModelDeletedEvent(item));
            _context.PricingModels.Remove(item);
        }
        await _context.SaveChangesAsync(cancellationToken);
        return await Result.SuccessAsync();
    }

}

