//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-09-24
// Validator for DeletePricingModelCommand: ensures the ID list for pricingmodel is not null and contains only positive IDs.
// Docs: https://docs.cleanarchitectureblazor.com/features/pricingmodel
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.PricingModels.Commands.Delete;

public class DeletePricingModelCommandValidator : AbstractValidator<DeletePricingModelCommand>
{
        public DeletePricingModelCommandValidator()
        {
          
            RuleFor(v => v.Id).NotNull().ForEach(v=>v.GreaterThan(0));
          
        }
}
    

