//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-09-24
//     Last Modified: 2025-09-24
//     Description: 
//       Defines a query to export quoteversion data to an Excel file. This query 
//       applies advanced filtering options and generates an Excel file with 
//       the specified quoteversion details.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.QuoteVersions.DTOs;
using CleanArchitecture.Blazor.Application.Features.QuoteVersions.Caching;
using CleanArchitecture.Blazor.Application.Features.QuoteVersions.Specifications;

namespace CleanArchitecture.Blazor.Application.Features.QuoteVersions.Queries.Export;

public class ExportQuoteVersionsQuery : QuoteVersionAdvancedFilter, ICacheableRequest<Result<byte[]>>
{
      public QuoteVersionAdvancedSpecification Specification => new QuoteVersionAdvancedSpecification(this);
      public IEnumerable<string>? Tags => QuoteVersionCacheKey.Tags;
    public override string ToString()
    {
        return $"Listview:{ListView}:{CurrentUser?.UserId}, Search:{Keyword}, {OrderBy}, {SortDirection}";
    }
    public string CacheKey => QuoteVersionCacheKey.GetExportCacheKey($"{this}");
}
    
public class ExportQuoteVersionsQueryHandler :
         IRequestHandler<ExportQuoteVersionsQuery, Result<byte[]>>
{
        private readonly IMapper _mapper;
        private readonly IApplicationDbContextFactory _dbContextFactory;
        private readonly IExcelService _excelService;
        private readonly IStringLocalizer<ExportQuoteVersionsQueryHandler> _localizer;
        private readonly QuoteVersionDto _dto = new();
        public ExportQuoteVersionsQueryHandler(
            IMapper mapper,
            IApplicationDbContextFactory dbContextFactory,
            IExcelService excelService,
            IStringLocalizer<ExportQuoteVersionsQueryHandler> localizer
            )
        {
            _mapper = mapper;
            _dbContextFactory = dbContextFactory;
            _excelService = excelService;
            _localizer = localizer;
        }
        #nullable disable warnings
        public async Task<Result<byte[]>> Handle(ExportQuoteVersionsQuery request, CancellationToken cancellationToken)
        {
        await using var _context = await _dbContextFactory.CreateAsync(cancellationToken);
        var data = await _context.QuoteVersions.ApplySpecification(request.Specification)
                       .OrderBy($"{request.OrderBy} {request.SortDirection}")
                       .ProjectTo<QuoteVersionDto>(_mapper.ConfigurationProvider)
                       .AsNoTracking()
                       .ToListAsync(cancellationToken);
            var result = await _excelService.ExportAsync(data,
                new Dictionary<string, Func<QuoteVersionDto, object?>>()
                {
                    // TODO: Define the fields that should be exported, for example:
                                     {_localizer[_dto.GetMemberDescription(x=>x.QuoteId)],item => item.QuoteId}, 
                 {_localizer[_dto.GetMemberDescription(x=>x.VersionNumber)],item => item.VersionNumber}, 
                 {_localizer[_dto.GetMemberDescription(x=>x.CreatedAtUtc)],item => item.CreatedAtUtc}, 
                 {_localizer[_dto.GetMemberDescription(x=>x.CreatedByEmployeeId)],item => item.CreatedByEmployeeId}, 

                }
                , _localizer[_dto.GetClassDescription()]);
            return await Result<byte[]>.SuccessAsync(result);
        }
}
